"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { SettingDefinition, SettingValue, SettingValues, SystemSettingsState, discardSettingsDraft, loadSystemSettings, publishSettingsDraft, saveSettingsDraft, validateSystemSettings } from "./system-settings-client";

type Tab = "General" | "Operational defaults" | "Notifications" | "Security & data" | "Versions" | "Activity" | "Safety";
const tabs: Tab[] = ["General", "Operational defaults", "Notifications", "Security & data", "Versions", "Activity", "Safety"];
const dateTime = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Never";
const heading = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

function Icon({ name, size = 16 }: { name: string; size?: number }) {
  const paths: Record<string, React.ReactNode> = {
    alert: <><path d="M10.3 3.6 2.8 17a2 2 0 0 0 1.7 3h15a2 2 0 0 0 1.7-3L13.7 3.6a2 2 0 0 0-3.4 0Z"/><path d="M12 9v4M12 17h.01"/></>,
    check: <path d="m5 12 4 4L19 6"/>, close: <><path d="m6 6 12 12M18 6 6 18"/></>,
    database: <><ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5v6c0 1.7 4 3 9 3s9-1.3 9-3V5M3 11v6c0 1.7 4 3 9 3s9-1.3 9-3v-6"/></>,
    publish: <><path d="M12 16V3M7 8l5-5 5 5"/><path d="M5 14v6h14v-6"/></>,
    refresh: <><path d="M20 11a8 8 0 1 0-2.34 5.66"/><path d="M20 4v7h-7"/></>,
    save: <><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2Z"/><path d="M17 21v-8H7v8M7 3v5h8"/></>,
    shield: <><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></>,
  };
  return <svg aria-hidden="true" fill="none" height={size} stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" viewBox="0 0 24 24" width={size}>{paths[name] ?? paths.shield}</svg>;
}

function Kpi({ label, note, value, warning = false }: { label: string; note: string; value: string; warning?: boolean }) {
  return <article className="rounded-2xl border border-[#e2e8e5] bg-white p-5"><div className="flex items-start justify-between"><div><p className="text-[7px] font-bold uppercase tracking-[.12em] text-[#7c8983]">{label}</p><strong className="mt-4 block text-[21px] tracking-tight text-[#182720]">{value}</strong></div><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${warning ? "bg-amber-50 text-amber-700" : "bg-[#edf3f4] text-[#477579]"}`}><Icon name={warning ? "alert" : "database"}/></span></div><p className="mt-4 border-t border-[#edf0ee] pt-3 text-[7px] leading-4 text-[#87928d]">{note}</p></article>;
}

function Status({ ready }: { ready: boolean }) {
  return <span className={`rounded-full px-2 py-1 text-[6.5px] font-bold ring-1 ring-inset ${ready ? "bg-emerald-50 text-emerald-700 ring-emerald-200" : "bg-slate-100 text-slate-600 ring-slate-200"}`}>{ready ? "Ready" : "Separate setup"}</span>;
}

function SettingControl({ definition, onChange, value }: { definition: SettingDefinition; onChange: (value: SettingValue) => void; value: SettingValue }) {
  const disabled = definition.isProtected;
  return <article className={`rounded-2xl border p-4 ${disabled ? "border-amber-200 bg-amber-50/30" : "border-[#e1e7e4] bg-white"}`}><div className="flex min-h-16 items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><b className="text-[9px] text-[#405049]">{definition.label}</b>{disabled && <span className="rounded-full bg-amber-100 px-2 py-1 text-[6px] font-bold text-amber-800">Protected</span>}</div><p className="mt-2 max-w-xl text-[7px] leading-4 text-[#7d8983]">{definition.description}</p></div>{definition.inputType === "toggle" && <button aria-label={`${definition.label}: ${value ? "on" : "off"}`} className={`relative mt-1 h-6 w-11 shrink-0 rounded-full transition ${value ? "bg-[#3b646d]" : "bg-[#cfd8d4]"} disabled:cursor-not-allowed disabled:opacity-55`} disabled={disabled} onClick={() => onChange(!Boolean(value))} type="button"><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${value ? "left-6" : "left-1"}`}/></button>}</div>{definition.inputType !== "toggle" && (definition.inputType === "select" ? <select className="mt-3 h-10 w-full rounded-xl border border-[#dce4e0] bg-white px-3 text-[9px] text-[#405049] outline-none disabled:opacity-60" disabled={disabled} onChange={(event) => onChange(event.target.value)} value={String(value ?? "")}>{definition.options.map((option) => <option key={option} value={option}>{option}</option>)}</select> : <input className="mt-3 h-10 w-full rounded-xl border border-[#dce4e0] bg-white px-3 text-[9px] text-[#405049] outline-none focus:border-[#9eb7b4] disabled:opacity-60" disabled={disabled} onChange={(event) => onChange(event.target.value)} type={definition.inputType === "email" ? "email" : "text"} value={String(value ?? "")}/>)}</article>;
}

function Modal({ children, onClose, title }: { children: React.ReactNode; onClose: () => void; title: string }) {
  return <div className="fixed inset-0 z-[150] flex items-center justify-center bg-[#17231f]/35 p-4 backdrop-blur-sm" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><section className="w-full max-w-xl overflow-hidden rounded-2xl bg-white shadow-[0_30px_90px_rgba(17,35,30,.24)]"><header className="flex items-start justify-between border-b p-5"><div><p className="text-[8px] font-bold uppercase tracking-[.14em] text-[#3b646d]">Protected publish</p><h2 className="mt-1.5 text-[18px] font-bold text-[#23322b]">{title}</h2></div><button className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#f2f5f3]" onClick={onClose}><Icon name="close"/></button></header>{children}</section></div>;
}

export function LiveSettingsWorkspace() {
  const [state, setState] = useState<SystemSettingsState | null>(null);
  const [settingValues, setSettingValues] = useState<SettingValues>({});
  const [tab, setTab] = useState<Tab>("General");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [publishOpen, setPublishOpen] = useState(false);
  const [publishReason, setPublishReason] = useState("");
  const [confirmed, setConfirmed] = useState(false);

  const setFromState = (next: SystemSettingsState) => { setState(next); setSettingValues(next.draftSettings ?? next.activeSettings); };
  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 4200); };
  const refresh = useCallback(async () => { setLoading(true); setError(""); try { setFromState(await loadSystemSettings()); } catch (problem) { setError(problem instanceof Error ? problem.message : "System settings could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void refresh(), 0); return () => window.clearTimeout(timer); }, [refresh]);

  const baseline = useMemo(() => state?.draftSettings ?? state?.activeSettings ?? {}, [state?.activeSettings, state?.draftSettings]);
  const localDirtyKeys = useMemo(() => Object.keys(settingValues).filter((key) => settingValues[key] !== baseline[key]), [baseline, settingValues]);
  const hasLocalChanges = localDirtyKeys.length > 0;
  const definitions = useMemo(() => (state?.definitions ?? []).filter((item) => item.categoryName === tab), [state?.definitions, tab]);
  const runAction = async (operation: () => Promise<{ message: string; state: SystemSettingsState }>, close?: () => void) => { setSaving(true); setError(""); try { const result = await operation(); setFromState(result.state); close?.(); flash(result.message); } catch (problem) { setError(problem instanceof Error ? problem.message : "The settings action could not be completed."); } finally { setSaving(false); } };
  const saveDraft = () => void runAction(() => saveSettingsDraft(settingValues));
  const validate = async () => { setSaving(true); setError(""); try { const result = await validateSystemSettings(settingValues); setState(result.state); flash(result.message); } catch (problem) { setError(problem instanceof Error ? problem.message : "Safe validation could not be completed."); } finally { setSaving(false); } };
  const discard = () => void runAction(discardSettingsDraft);
  const publish = () => void runAction(() => publishSettingsDraft(publishReason), () => { setPublishOpen(false); setPublishReason(""); setConfirmed(false); });
  const summary = state?.summary;

  return <div className="space-y-5">
    <section className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500"/><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#3b646d]">Control plane</p></div><h1 className="mt-2 text-[28px] font-bold tracking-[-.035em] text-[#17231f] sm:text-[32px]">Settings command center</h1><p className="mt-1.5 max-w-3xl text-[12.5px] leading-5 text-[#66736d]">Manage business identity, operational defaults, notifications and security preferences through recoverable drafts and audited versions.</p></div><div className="flex flex-wrap gap-2"><button className="flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-[9px] font-bold text-[#596962]" onClick={() => void refresh()}><Icon name="refresh"/>Refresh</button><button className="flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-[9px] font-bold text-[#3b646d] disabled:opacity-40" disabled={saving || !state} onClick={validate}><Icon name="shield"/>Run safe validation</button><button className="flex h-10 items-center gap-2 rounded-xl border border-[#3b646d] bg-white px-4 text-[9px] font-bold text-[#3b646d] disabled:opacity-40" disabled={!hasLocalChanges || saving} onClick={saveDraft}><Icon name="save"/>Save draft</button><button className="flex h-10 items-center gap-2 rounded-xl bg-[#3b646d] px-4 text-[9px] font-bold text-white disabled:opacity-40" disabled={!state?.draftSettings || hasLocalChanges || saving} onClick={() => { setConfirmed(false); setPublishReason(""); setPublishOpen(true); }}><Icon name="publish"/>Publish</button></div></section>

    {error && <div className="flex items-center justify-between rounded-2xl border border-rose-200 bg-rose-50 px-5 py-4 text-[8px] font-bold text-rose-700"><span>{error}</span><button className="underline" onClick={() => void refresh()}>Try again</button></div>}
    {notice && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-[8px] font-bold text-emerald-700">{notice}</div>}
    {state && !state.validation.valid && <div className="rounded-2xl border border-amber-200 bg-amber-50 px-5 py-4 text-[8px] font-bold text-amber-800">Validation needs attention: {state.validation.issues.join(" ")}</div>}

    <section className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_auto]"><article className="flex flex-col gap-3 rounded-2xl border border-[#d9e4e1] bg-white p-4 sm:flex-row sm:items-center"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#edf3f4] text-[#3b646d]"><Icon name="database"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-[9px] text-[#405049]">Configuration registry</b><span className="rounded-full bg-emerald-50 px-2 py-1 text-[6.5px] font-bold text-emerald-700">MySQL connected</span><span className="rounded-full bg-[#f2f4f3] px-2 py-1 text-[6.5px] font-bold text-[#65736c]">{state?.engine.timezone || "Asia/Dhaka"}</span></div><p className="mt-1.5 text-[7px] text-[#87928d]">Last validation {dateTime(state?.engine.lastValidationAt ?? null)} · current version published {dateTime(state?.engine.lastPublishedAt ?? null)}</p></div></article><div className="flex items-center gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3"><Icon name="check"/><div><b className="block text-[8px] text-[#405049]">No retroactive mutation</b><span className="mt-1 block text-[6.5px] text-[#718079]">Old orders and records are never rewritten</span></div></div></section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Kpi label="Active version" note="Published configuration snapshot" value={`v${summary?.activeVersion ?? 0}`}/><Kpi label="Draft changes" note="Saved changes waiting to publish" value={String(summary?.draftChanges ?? 0)} warning={(summary?.draftChanges ?? 0) > 0}/><Kpi label="Settings" note="Verified configuration definitions" value={String(summary?.settingsCount ?? 0)}/><Kpi label="Protected" note="Safety controls locked in this screen" value={String(summary?.protectedControls ?? 0)} warning/><Kpi label="Validations · 30D" note="Recorded safe validation checks" value={String(summary?.validations30d ?? 0)}/><Kpi label="Changes · 30D" note="Draft, discard and publish evidence" value={String(summary?.changes30d ?? 0)}/></section>

    <section className="grid gap-4 xl:grid-cols-[minmax(0,1.3fr)_minmax(330px,.7fr)]"><article className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-[8px] font-bold uppercase tracking-[.12em] text-[#84908a]">Draft readiness</p><h2 className="mt-1 text-[14px] font-bold text-[#33423b]">Configuration lifecycle</h2></div><span className="rounded-full bg-[#edf3f4] px-2 py-1 text-[7px] font-bold text-[#3b646d]">Registry only</span></div><div className="mt-4 grid gap-2 sm:grid-cols-4">{[["1","Edit locally"],["2","Save draft"],["3","Validate"],["4","Publish with reason"]].map(([step,label]) => <div className="rounded-xl border p-3" key={step}><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#edf3f4] text-[8px] font-bold text-[#3b646d]">{step}</span><b className="mt-3 block text-[8px] text-[#405049]">{label}</b></div>)}</div>{state?.draftSettings && <button className="mt-4 text-[7px] font-bold text-rose-700 underline disabled:opacity-40" disabled={saving || hasLocalChanges} onClick={discard}>Discard saved draft</button>}</article><article className="rounded-2xl border border-[#d6e2df] bg-[#edf3f4] p-5"><p className="text-[8px] font-bold uppercase tracking-[.12em] text-[#5e7875]">Verified dependencies</p><h2 className="mt-1 text-[14px] font-bold text-[#304d4d]">Control readiness</h2><div className="mt-4 space-y-2">{[["Admin authentication",state?.capabilities.adminAuth],["Access registry",state?.capabilities.accessRegistry],["Audit ledger",state?.capabilities.audit],["Integrations",state?.capabilities.integrations]].map(([name,ready]) => <div className="flex items-center justify-between rounded-xl bg-white p-3" key={String(name)}><b className="text-[8px] text-[#405049]">{String(name)}</b><Status ready={Boolean(ready)}/></div>)}</div><p className="mt-4 text-[7px] leading-4 text-[#647b77]">Integration secrets stay in the separate Integrations module and are never returned by this settings API.</p></article></section>

    <section className="overflow-hidden rounded-2xl border border-[#e2e8e5] bg-white"><div className="flex gap-1 overflow-x-auto border-b p-4">{tabs.map((item) => <button className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-[9px] font-bold ${tab === item ? "bg-[#3b646d] text-white" : "bg-[#f3f6f4] text-[#68766f]"}`} key={item} onClick={() => setTab(item)}>{item}{item === "Versions" ? ` ${state?.versions.length ?? 0}` : ""}</button>)}</div>
      {loading && !state ? <div className="flex min-h-96 items-center justify-center text-[9px] font-semibold text-[#87928d]">Loading settings registry…</div> : null}
      {definitions.length > 0 && <div className="grid gap-3 p-5 md:grid-cols-2">{definitions.map((definition) => <SettingControl definition={definition} key={definition.key} onChange={(value) => setSettingValues((current) => ({ ...current, [definition.key]: value }))} value={settingValues[definition.key] ?? ""}/>)}</div>}
      {tab === "Versions" && state && <div className="divide-y">{state.versions.map((item) => <div className="grid gap-2 px-5 py-4 text-[8px] sm:grid-cols-[1fr_auto_auto]" key={item.id}><div><b className="text-[#405049]">Settings version v{item.version}</b><p className="mt-1 text-[#718079]">{item.reason}</p></div><span>{item.createdBy}</span><span>{dateTime(item.createdAt)}</span></div>)}</div>}
      {tab === "Activity" && state && <div className="divide-y">{state.activity.length ? state.activity.map((item) => <div className="grid gap-2 px-5 py-4 text-[8px] sm:grid-cols-[1fr_auto]" key={item.id}><div><b className="text-[#405049]">{heading(item.eventType)}</b><p className="mt-1 text-[#718079]">{item.note}</p>{item.settingKeys.length > 0 && <p className="mt-1 font-mono text-[6.5px] text-[#8a9590]">{item.settingKeys.join(", ")}</p>}</div><span>{item.actorName} · {dateTime(item.createdAt)}</span></div>) : <div className="flex min-h-64 items-center justify-center text-[8px] text-[#87928d]">No settings activity recorded yet.</div>}</div>}
      {tab === "Safety" && <div className="grid gap-3 p-5 md:grid-cols-2"><Kpi label="Registry ≠ retroactive rewrite" note="Publishing a setting never rewrites historical orders, inventory, finance or customer records." value="Explicit"/><Kpi label="Protected controls" note="Oversell prevention, COD approval, restore-on-cancel, backup and sensitive approvals are locked here." value="Guarded" warning/><Kpi label="Draft before publish" note="Edits stay local until a full validated draft is saved and published with an audit reason." value="Required"/><Kpi label="Secrets stay separate" note="API keys and tokens belong to Integrations and are not present in settings responses." value="Isolated"/></div>}
    </section>

    {publishOpen && <Modal onClose={() => setPublishOpen(false)} title="Publish settings version"><div className="space-y-4 p-5"><p className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-[8px] leading-4 text-emerald-800">This publishes the saved configuration registry version. It will not rewrite historical orders, stock, finance records or customer data.</p><label className="block text-[8px] font-bold text-[#405049]">Audit reason<textarea className="mt-2 min-h-24 w-full resize-none rounded-xl border border-[#dce4e0] p-3 text-[9px] outline-none" onChange={(event) => setPublishReason(event.target.value)} placeholder="Explain why this configuration should go live…" value={publishReason}/></label><label className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-[8px] text-amber-800"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)}/><span>I reviewed the draft and understand publication changes only the versioned settings registry.</span></label></div><footer className="flex justify-end gap-2 border-t p-4"><button className="h-10 rounded-xl border px-4 text-[8px] font-bold" onClick={() => setPublishOpen(false)}>Cancel</button><button className="h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-40" disabled={!confirmed || !publishReason.trim() || saving} onClick={publish}>Publish version</button></footer></Modal>}
  </div>;
}
