"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type ControlState = { desired_enabled: boolean; effective_enabled: boolean; note: string | null; updated_by: string | null; updated_at: string | null };
type Dashboard = {
  controls: Record<string, ControlState>;
  metrics: Record<string, number>;
  environment: { messenger_send_env_enabled: boolean; order_creation_env_enabled: boolean; automatic_reply_build_available: boolean };
  safety: Record<string, boolean>;
  queues?: { support: Array<Record<string, unknown>>; handoffs: Array<Record<string, unknown>> };
  audit: Array<Record<string, unknown>>;
  generated_at: string;
};

const API_BASE=(process.env.NEXT_PUBLIC_BNB_API_BASE_URL || "http://localhost/BrandnBeauty/brandnbeauty-backend/php").replace(/\/$/, "");
const TOKEN_KEY="bnb_ai_commerce_admin_token";
const labels: Record<string,string>={
  maintenance_mode:"Maintenance mode",
  automatic_reply:"Automatic AI reply",
  messenger_send:"Messenger send",
  order_creation:"Bot order creation",
  recommendation:"Personalized recommendation",
  commercial_priority:"Commercial priority after eligibility",
};

function Badge({on,children}:{on:boolean;children:React.ReactNode}){return <span className={`rounded-full px-2.5 py-1 text-[11px] font-black uppercase tracking-[0.12em] ${on?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{children}</span>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">{label}</div><div className="mt-3 text-3xl font-black text-slate-950">{value}</div></div>}

export function AiCommerceControlCenter(){
  const [token,setToken]=useState("");const [username,setUsername]=useState("");const [password,setPassword]=useState("");
  const [dashboard,setDashboard]=useState<Dashboard|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>{setToken(window.localStorage.getItem(TOKEN_KEY)||"");},[]);
  const load=useCallback(async(currentToken?:string)=>{const t=currentToken||token;if(!t)return;setBusy(true);setError("");try{const res=await fetch(`${API_BASE}/messenger_bot_control_center_api.php`,{headers:{Authorization:`Bearer ${t}`},cache:"no-store"});if(res.status===401){window.localStorage.removeItem(TOKEN_KEY);setToken("");throw new Error("Backend admin session expired. Sign in again.");}const json=await res.json();if(!res.ok||!json.success)throw new Error("Control Center could not be loaded.");setDashboard(json.data);}catch(e){setError(e instanceof Error?e.message:"Control Center could not be loaded.");}finally{setBusy(false)}},[token]);
  useEffect(()=>{if(token)void load(token);},[token,load]);
  async function signIn(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const res=await fetch(`${API_BASE}/auth.php`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"admin_login",username,password})});const json=await res.json();if(!res.ok||!json.token)throw new Error("Backend admin sign-in failed.");window.localStorage.setItem(TOKEN_KEY,json.token);setToken(json.token);setPassword("");}catch(e){setError(e instanceof Error?e.message:"Sign-in failed.");}finally{setBusy(false)}}
  async function setControl(key:string,enabled:boolean){if(!token)return;setBusy(true);setError("");try{const res=await fetch(`${API_BASE}/messenger_bot_control_center_api.php`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({action:"set_control",control_key:key,enabled,confirmed:true,note:"Changed from AI Commerce Control Center"})});const json=await res.json();if(!res.ok||!json.success)throw new Error(json.message||json.error||"Control update failed.");setDashboard(json.data);}catch(e){setError(e instanceof Error?e.message:"Control update failed.");}finally{setBusy(false)}}
  const metrics=dashboard?.metrics||{};
  const safeMode=useMemo(()=>!dashboard?.controls?.automatic_reply?.effective_enabled && !dashboard?.controls?.messenger_send?.effective_enabled,[dashboard]);
  if(!token){return <div className="mx-auto max-w-xl rounded-[2rem] border border-slate-200 bg-white p-7 shadow-sm"><div className="text-xs font-black uppercase tracking-[0.2em] text-[#527B86]">AI Commerce Control Center</div><h1 className="mt-2 text-2xl font-black text-slate-950">Connect backend admin control</h1><p className="mt-2 text-sm leading-6 text-slate-500">Use the existing BrandnBeauty backend admin credentials. The token stays in this browser only.</p><form className="mt-6 space-y-3" onSubmit={signIn}><input className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm" placeholder="Admin email / username" value={username} onChange={e=>setUsername(e.target.value)} required/><input className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm" placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="w-full rounded-2xl bg-[#527B86] px-5 py-3 text-sm font-black text-white disabled:opacity-50" disabled={busy}>{busy?"Connecting...":"Connect Control Center"}</button></form>{error?<div className="mt-4 rounded-2xl bg-rose-50 p-3 text-sm font-bold text-rose-700">{error}</div>:null}</div>}
  return <div className="space-y-6">
    <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[0.2em] text-[#527B86]">Messenger AI Commerce</div><h1 className="mt-2 text-3xl font-black text-slate-950">AI Commerce Control Center</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Monitor queues, safety state and runtime controls without bypassing environment kill switches.</p></div><div className="flex items-center gap-2"><Badge on={safeMode}>{safeMode?"Safe mode":"Live-capable"}</Badge><button className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-black text-slate-600" onClick={()=>void load()} disabled={busy}>Refresh</button><button className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-black text-slate-500" onClick={()=>{localStorage.removeItem(TOKEN_KEY);setToken("");setDashboard(null)}}>Disconnect</button></div></div>{error?<div className="mt-4 rounded-2xl bg-rose-50 p-3 text-sm font-bold text-rose-700">{error}</div>:null}</section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Conversations" value={metrics.conversations_total||0}/><Metric label="Active Handoffs" value={metrics.active_handoffs||0}/><Metric label="Open Support" value={metrics.open_support_cases||0}/><Metric label="P0/P1 Cases" value={metrics.open_p0_p1_cases||0}/><Metric label="Bot Orders" value={metrics.bot_orders_created||0}/></section>
    <section className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]">
      <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><div className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Runtime Controls</div><h2 className="mt-1 text-xl font-black text-slate-950">Feature flags & kill switches</h2></div><Badge on={false}>Human approval first</Badge></div><div className="mt-5 divide-y divide-slate-100">{Object.entries(dashboard?.controls||{}).map(([key,state])=><div className="flex items-center justify-between gap-4 py-4" key={key}><div><div className="font-black text-slate-900">{labels[key]||key}</div><div className="mt-1 text-xs font-semibold text-slate-500">Desired: {state.desired_enabled?"ON":"OFF"} · Effective: {state.effective_enabled?"ON":"OFF"}</div></div><button className={`min-w-24 rounded-2xl px-4 py-2 text-xs font-black ${state.desired_enabled?"bg-[#527B86] text-white":"bg-slate-100 text-slate-600"}`} onClick={()=>void setControl(key,!state.desired_enabled)} disabled={busy}>{state.desired_enabled?"Turn off":"Turn on"}</button></div>)}</div></div>
      <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Hard Gates</div><h2 className="mt-1 text-xl font-black text-slate-950">Environment safety</h2><div className="mt-5 space-y-3 text-sm font-bold"><div className="flex justify-between rounded-2xl bg-stone-50 p-4"><span>Messenger send env</span><Badge on={!!dashboard?.environment?.messenger_send_env_enabled}>{dashboard?.environment?.messenger_send_env_enabled?"ON":"OFF"}</Badge></div><div className="flex justify-between rounded-2xl bg-stone-50 p-4"><span>Order creation env</span><Badge on={!!dashboard?.environment?.order_creation_env_enabled}>{dashboard?.environment?.order_creation_env_enabled?"ON":"OFF"}</Badge></div><div className="flex justify-between rounded-2xl bg-stone-50 p-4"><span>Automatic reply build</span><Badge on={!!dashboard?.environment?.automatic_reply_build_available}>{dashboard?.environment?.automatic_reply_build_available?"READY":"LOCKED"}</Badge></div></div><p className="mt-4 text-xs leading-5 text-slate-500">Database controls may disable features instantly, but cannot override environment kill switches.</p></div>
    </section>
    <section className="grid gap-6 xl:grid-cols-2">{([['Support Queue',dashboard?.queues?.support||[]],['Human Handoff Queue',dashboard?.queues?.handoffs||[]]] as const).map(([title,rows])=><div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm" key={title}><div className="flex items-center justify-between"><h2 className="text-lg font-black text-slate-950">{title}</h2><span className="text-xs font-black text-slate-400">{rows.length} visible</span></div><div className="mt-4 space-y-2">{rows.length?rows.map((row,i)=><div className="rounded-2xl bg-stone-50 p-4 text-sm" key={i}><div className="font-black text-slate-900">{String(row.title||row.reason_code||`Conversation ${row.conversation_id||""}`)}</div><div className="mt-1 text-xs font-semibold text-slate-500">Priority {String(row.priority||"-")} · {String(row.status||"-")}</div></div>):<div className="rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">No active items.</div>}</div></div>)}</section>
    <section className="rounded-[2rem] border border-amber-200 bg-amber-50 p-5 text-sm font-semibold leading-6 text-amber-800">Automatic AI reply remains intentionally unavailable in Phase 11. Live Messenger sending and bot order creation also remain blocked unless both this Control Center and the environment kill switch allow them.</section>
  </div>;
}
