"use client";

import { useCallback, useEffect, useState, type ReactNode } from "react";

import { loadStorefrontExecution, type StorefrontExecutionState } from "./storefront-execution-client";

type Props = { onNavigate: (page: string) => void };
type IconName = "arrow" | "check" | "database" | "external" | "mobile" | "refresh" | "search" | "store";
const paths: Record<IconName, ReactNode> = {
  arrow: <><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></>, check: <path d="m5 12 4 4L19 6"/>,
  database: <><ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v6c0 1.7 3.6 3 8 3s8-1.3 8-3V5M4 11v6c0 1.7 3.6 3 8 3s8-1.3 8-3v-6"/></>,
  external: <><path d="M14 3h7v7"/><path d="m10 14 11-11"/><path d="M21 14v5a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5"/></>,
  mobile: <><rect x="6" y="2" width="12" height="20" rx="2"/><path d="M10 18h4"/></>,
  refresh: <><path d="M20 11a8 8 0 1 0-2.3 5.7"/><path d="M20 4v7h-7"/></>,
  search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,
  store: <><path d="M3 9 5 3h14l2 6"/><path d="M5 13v8h14v-8M9 21v-6h6v6"/><path d="M3 9a3 3 0 0 0 6 0 3 3 0 0 0 6 0 3 3 0 0 0 6 0"/></>,
};
function Icon({ name, size = 16 }: { name: IconName; size?: number }) { return <svg aria-hidden="true" fill="none" height={size} stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" viewBox="0 0 24 24" width={size}>{paths[name]}</svg>; }
function Kpi({ helper, icon, label, value }: { helper: string; icon: IconName; label: string; value: string | number }) { return <article className="rounded-2xl border border-[#dfe6e2] bg-white p-4"><div className="flex items-start justify-between"><div><p className="text-[8px] font-bold uppercase tracking-[.1em] text-[#7b8781]">{label}</p><p className="mt-3 text-[24px] font-bold tracking-[-.04em] text-[#17231f]">{value}</p></div><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#edf3f4] text-[#416e72]"><Icon name={icon} size={15}/></span></div><p className="mt-3 border-t border-[#edf1ef] pt-2.5 text-[7px] leading-4 text-[#849089]">{helper}</p></article>; }

export function LiveStorefrontExecutionWorkspace({ onNavigate }: Props) {
  const [state, setState] = useState<StorefrontExecutionState | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setState(await loadStorefrontExecution()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Storefront preview evidence could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { const task = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(task); }, [load]);
  const openPreview = () => window.open("/storefront-preview", "_blank", "noopener,noreferrer");
  const feedsReady = state?.connectedFeeds === state?.totalFeeds;

  return <div className="space-y-5">
    <section className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500"/><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#3b646d]">Phase 72 · live product discovery</p></div><h1 className="mt-2 text-[28px] font-bold tracking-[-.035em] text-[#17231f] sm:text-[32px]">Storefront execution command center</h1><p className="mt-1.5 max-w-3xl text-[12.5px] leading-5 text-[#66736d]">Search, filter and open stock-safe details from the real public catalog before cart, checkout, DNS or tracking are connected.</p></div><div className="flex flex-wrap gap-2"><button className="flex h-10 items-center gap-2 rounded-xl border border-[#dce4e0] bg-white px-4 text-[9px] font-bold text-[#596962] disabled:opacity-50" disabled={loading} onClick={() => void load()}><Icon name="refresh"/>Refresh evidence</button><button className="flex h-10 items-center gap-2 rounded-xl bg-[#3b646d] px-4 text-[9px] font-bold text-white" onClick={openPreview}><Icon name="external"/>Open live preview</button></div></section>

    <section className="rounded-2xl border border-[#d3e2df] bg-[#edf4f4] p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white text-[#416f73]"><Icon name="database"/></span><div><b className="block text-[9px] text-[#35524f]">Products + collections + CMS + SEO public feeds · MySQL connected</b><p className="mt-1 text-[7px] leading-4 text-[#72827c]">Preview reads existing public data only. It creates no sample product, order, cart, customer, stock movement or tracking event.</p></div></div><span className="w-fit rounded-full bg-white px-3 py-2 text-[7px] font-bold text-[#496b68]">Preview → mobile proof → cart bridge</span></div></section>

    {error ? <div className="flex items-center justify-between rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-[9px] font-semibold text-rose-800"><span>{error}</span><button className="underline" onClick={() => void load()}>Try again</button></div> : null}

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi helper="Required public endpoints responding" icon="database" label="Public feeds" value={`${state?.connectedFeeds ?? 0}/${state?.totalFeeds ?? 8}`}/><Kpi helper="Active product records only" icon="store" label="Live products" value={state?.products ?? 0}/><Kpi helper="Active discovery groups" icon="search" label="Collections" value={state?.collections ?? 0}/><Kpi helper="Published homepage media" icon="check" label="Active heroes" value={state?.activeHeroes ?? 0}/><Kpi helper="Target mobile acceptance sizes" icon="mobile" label="Mobile widths" value="4"/></section>

    <section className="grid gap-4 xl:grid-cols-[minmax(0,1.35fr)_minmax(330px,.65fr)]"><article className="overflow-hidden rounded-2xl border border-[#dfe6e2] bg-white"><header className="border-b border-[#e8ecea] p-5"><p className="text-[7px] font-bold uppercase tracking-[.12em] text-[#3b646d]">Launch-first sequence</p><h2 className="mt-1.5 text-[16px] font-bold text-[#2c3e37]">What this phase proves</h2></header><div className="divide-y divide-[#edf1ef]">{[
      ["Live customer-facing route", "/storefront-preview opens from the existing one-click local admin runtime.", true],
      ["Real public data", "Product, collection, homepage, header, footer, review, offer and SEO feeds are read without seed data.", feedsReady],
      ["Search and filters", "Product, brand, category and SKU search plus brand, category, stock and price controls are live.", true],
      ["Stock-safe detail", "Offer price, description, related products and unavailable-product states read live data without reserving stock.", true],
      ["SEO-safe preview", "Preview stays noindex while metadata and customer-facing page structure are prepared for production.", state?.seoConnected ?? false],
      ["Commerce mutation boundary", "Cart, checkout, order creation, stock reservation and payment remain disabled until the controlled Phase 73 bridge.", true],
    ].map(([title, body, ready]) => <div className="grid gap-3 p-5 sm:grid-cols-[34px_minmax(0,1fr)_110px] sm:items-center" key={String(title)}><span className={`flex h-8 w-8 items-center justify-center rounded-xl ${ready ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}><Icon name={ready ? "check" : "refresh"} size={14}/></span><div><b className="block text-[9px] text-[#364740]">{String(title)}</b><p className="mt-1 text-[7px] leading-4 text-[#7b8882]">{String(body)}</p></div><span className={`w-fit rounded-full px-2 py-1 text-[6.5px] font-bold ${ready ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{ready ? "Ready" : "Needs live feed"}</span></div>)}</div></article>

      <aside className="rounded-2xl border border-[#dfe6e2] bg-white p-5"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#edf3f4] text-[#416e72]"><Icon name="mobile" size={20}/></div><h2 className="mt-4 text-[16px] font-bold text-[#2c3e37]">Mobile acceptance targets</h2><p className="mt-1 text-[7px] leading-4 text-[#7d8984]">Designed first for Facebook and Instagram in-app visitors.</p><div className="mt-5 grid grid-cols-2 gap-2">{[360,375,390,412].map((width) => <div className="rounded-xl border border-[#e4eae7] bg-[#fafbfa] p-3" key={width}><span className="text-[6px] uppercase tracking-[.08em] text-[#87938d]">Viewport</span><b className="mt-1 block text-[11px] text-[#52655d]">{width}px</b></div>)}</div><button className="mt-4 flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-[#3b646d] text-[8px] font-bold text-white" onClick={openPreview}>Open customer preview<Icon name="external" size={13}/></button><button className="mt-2 flex h-10 w-full items-center justify-center gap-2 rounded-xl border border-[#dce4e0] text-[8px] font-bold text-[#4f6760]" onClick={() => onNavigate("SEO & Storefront Health")}>Open SEO workspace<Icon name="arrow" size={13}/></button><div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><b className="text-[8px] text-amber-800">Tracking intentionally deferred</b><p className="mt-2 text-[7px] leading-4 text-amber-700">GTM, GA4, Meta Pixel and CAPI move to Phase 77. Only real IDs will be used; no dummy identifiers are stored.</p></div></aside></section>

    <section className="grid gap-3 md:grid-cols-3"><div className="rounded-2xl border border-[#e1e8e5] bg-white p-4"><p className="text-[7px] font-bold uppercase tracking-[.1em] text-[#7b8882]">Source of truth</p><b className="mt-2 block text-[9px] text-[#3f5149]">Existing public MySQL feeds</b><p className="mt-2 text-[7px] leading-4 text-[#849089]">No browser-only catalog state and no invented storefront success.</p></div><div className="rounded-2xl border border-[#e1e8e5] bg-white p-4"><p className="text-[7px] font-bold uppercase tracking-[.1em] text-[#7b8882]">Next controlled bridge</p><b className="mt-2 block text-[9px] text-[#3f5149]">Cart, checkout and order bridge</b><p className="mt-2 text-[7px] leading-4 text-[#849089]">Connect progressively without changing existing order or stock truth.</p></div><div className="rounded-2xl border border-[#d5e3e0] bg-[#edf4f4] p-4"><p className="text-[7px] font-bold uppercase tracking-[.1em] text-[#607873]">Safety boundary</p><b className="mt-2 block text-[9px] text-[#3c5b56]">No live deploy or tracking send</b><p className="mt-2 text-[7px] leading-4 text-[#6e817c]">Preview is noindex and cannot create carts, orders, payments or stock movements.</p></div></section>
  </div>;
}
