"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CommerceConversation, CommerceProduct, CommerceState, createConversationEvidence, createReplyDraft, fetchCommerce, prepareOrderDraft, recordIdentityReview, updateCommerceStage } from "./conversational-commerce-client";

const empty:CommerceState={generated_at:"",conversations:[],products:[],quality:{},summary:{attributed:0,delivered:0,needs_review:0,open:0,order_drafts:0,reply_drafts:0,total:0}};
const stageTone:Record<string,string>={new_inquiry:"bg-sky-50 text-sky-700",interested:"bg-violet-50 text-violet-700",order_draft:"bg-amber-50 text-amber-700",order_created:"bg-cyan-50 text-cyan-700",purchased:"bg-emerald-50 text-emerald-700",delivered:"bg-emerald-100 text-emerald-800",closed:"bg-slate-100 text-slate-600"};
const human=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
const money=(value:number|null)=>value===null?"—":`৳${value.toLocaleString("en-BD")}`;

export function LiveConversationalCommerceWorkspace(_props:{onNavigate:(page:string)=>void}) {
  void _props;
  const [state,setState]=useState(empty),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[query,setQuery]=useState(""),[stage,setStage]=useState("all"),[focusedId,setFocusedId]=useState(""),[mode,setMode]=useState<"intake"|"reply"|"identity"|"order"|"stage"|null>(null),[saving,setSaving]=useState(false);
  const load=useCallback(async(signal?:AbortSignal)=>{setError("");try{const next=await fetchCommerce(signal);setState(next);setFocusedId(current=>next.conversations.some(item=>item.id===current)?current:next.conversations[0]?.id||"")}catch(reason){if(!(reason instanceof DOMException&&reason.name==="AbortError"))setError(reason instanceof Error?reason.message:"Conversational commerce is temporarily unavailable.")}finally{if(!signal?.aborted)setLoading(false)}},[]);
  useEffect(()=>{const controller=new AbortController();queueMicrotask(()=>void load(controller.signal));return()=>controller.abort()},[load]);
  const filtered=useMemo(()=>state.conversations.filter(item=>(stage==="all"||item.lead_stage===stage)&&(!query||`${item.channel} ${item.intent_summary} ${item.thread_reference} ${item.contact_reference} ${item.campaign_reference} ${item.ad_reference}`.toLowerCase().includes(query.toLowerCase()))),[query,stage,state.conversations]);
  const focused=state.conversations.find(item=>item.id===focusedId)||null;
  async function commit(operation:()=>Promise<CommerceState>,message:string){setSaving(true);setError("");try{const next=await operation();setState(next);setMode(null);setFocusedId(current=>next.conversations.some(item=>item.id===current)?current:next.conversations[0]?.id||"");setNotice(message)}catch(reason){setError(reason instanceof Error?reason.message:"The evidence could not be saved.")}finally{setSaving(false)}}
  const stats=[["Total threads",state.summary.total,"Real conversation evidence"],["Open",state.summary.open,"Active human queue"],["Needs review",state.summary.needs_review,"Consent, window or identity"],["Reply drafts",state.summary.reply_drafts,"Saved—not sent"],["Order drafts",state.summary.order_drafts,"No stock movement"],["Attributed",state.summary.attributed,"Campaign or ad reference"]] as const;
  return <div className="space-y-5">
    <section className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[9px] font-extrabold uppercase tracking-[.16em] text-[#167a67]">● Live governed commerce evidence</p><h1 className="mt-2 text-[28px] font-bold tracking-[-.035em] text-[#17231f] sm:text-[32px]">Conversational commerce command center</h1><p className="mt-1.5 max-w-4xl text-[12px] leading-5 text-[#66736d]">Unify Messenger, WhatsApp, Instagram and website-chat evidence while keeping identity, replies, lead stages and order creation under human control.</p></div><div className="flex gap-2"><button className="h-11 rounded-xl border bg-white px-4 text-[9px] font-bold" onClick={()=>void load()}>↻ Refresh</button><button className="h-11 rounded-xl bg-[#426d72] px-4 text-[9px] font-bold text-white" onClick={()=>setMode("intake")}>+ Record conversation</button></div></section>
    <section className="flex flex-col gap-3 rounded-2xl border border-[#d9e4e1] bg-[#edf5f5] p-5 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-[9px] text-[#315a58]">Conversation evidence ledger · MySQL connected</b><p className="mt-1 text-[7px] text-[#69817b]">Channel credentials are not assumed. Contact and thread references are hashed before storage.</p></div><span className="w-fit rounded-full bg-white px-3 py-2 text-[7px] font-bold text-[#426d72]">Evidence → human review → controlled draft</span></section>
    {error&&<Alert bad>{error}</Alert>}{notice&&<Alert>{notice}</Alert>}
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-6">{stats.map(([label,value,note])=><div className="rounded-2xl border bg-white p-4" key={label}><span className="text-[7px] font-bold uppercase tracking-[.1em] text-[#8c9892]">{label}</span><b className="mt-3 block text-[22px]">{loading?"—":value}</b><p className="mt-3 border-t pt-3 text-[6.5px] text-[#89948f]">{note}</p></div>)}</section>
    <section className="grid min-h-[760px] gap-4 lg:grid-cols-[1.35fr_.85fr]"><div className="overflow-hidden rounded-2xl border bg-white"><div className="flex gap-2 border-b p-4"><input className="h-10 min-w-0 flex-1 rounded-xl border px-3 text-[9px]" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search channel, intent, campaign or protected reference..."/><select className="h-10 rounded-xl border px-3 text-[8px]" value={stage} onChange={event=>setStage(event.target.value)}><option value="all">All stages</option>{["new_inquiry","interested","order_draft","order_created","purchased","delivered","closed"].map(value=><option value={value} key={value}>{human(value)}</option>)}</select></div>{filtered.length?<div className="divide-y">{filtered.map(item=><button key={item.id} onClick={()=>setFocusedId(item.id)} className={`grid w-full grid-cols-[1fr_auto] gap-3 p-4 text-left ${focusedId===item.id?"bg-[#f2f7f6]":""}`}><span><b className="text-[9px]">{human(item.channel)} · {item.intent_summary}</b><small className="mt-1 block text-[6.5px] text-[#89948f]">{item.contact_reference} · {item.thread_reference} · owner {item.owner}</small><small className="mt-1 block text-[6.5px] text-[#89948f]">Consent {item.contact_consent} · window {item.messaging_window} · identity {item.identity_status}</small></span><Stage value={item.lead_stage}/></button>)}</div>:<Empty/>}</div>
      <div className="rounded-2xl border bg-white p-5">{focused?<Inspector item={focused} open={setMode}/>:<div className="flex min-h-[690px] items-center justify-center text-center"><span><b className="text-[10px]">Select a conversation</b><p className="mt-2 text-[7px] text-[#89948f]">Choose real evidence or record the first governed thread.</p></span></div>}</div></section>
    <section className="grid gap-3 md:grid-cols-3"><Info title="Source of truth" text="MySQL conversation evidence plus live catalog price and stock snapshots."/><Info title="Human control" text="Replies, identity reviews, lead stages and order drafts require explicit confirmation."/><Info title="Safety boundary" text="Zero automatic send, customer merge, discount, order, stock movement or Meta event."/></section>
    {mode==="intake"&&<Intake saving={saving} close={()=>setMode(null)} save={input=>commit(()=>createConversationEvidence(input),"Conversation evidence recorded; no message was sent.")}/>} 
    {mode==="reply"&&focused&&<Reply item={focused} saving={saving} close={()=>setMode(null)} save={input=>commit(()=>createReplyDraft(input),"Human-approved reply draft saved; it was not sent.")}/>} 
    {mode==="identity"&&focused&&<Identity item={focused} saving={saving} close={()=>setMode(null)} save={input=>commit(()=>recordIdentityReview(input),"Identity review saved; no customer records were merged.")}/>} 
    {mode==="order"&&focused&&<Order item={focused} products={state.products} saving={saving} close={()=>setMode(null)} save={input=>commit(()=>prepareOrderDraft(input),"Order draft saved from live price and stock; no order was created.")}/>} 
    {mode==="stage"&&focused&&<StageUpdate item={focused} saving={saving} close={()=>setMode(null)} save={input=>commit(()=>updateCommerceStage(input),"Evidence-backed stage saved; no external event was sent.")}/>} 
  </div>;
}

function Inspector({item,open}:{item:CommerceConversation;open:(mode:"reply"|"identity"|"order"|"stage")=>void}){const replyBlocked=item.contact_consent!=="active"||item.messaging_window!=="open"||item.permitted_purpose==="unknown";return <><div className="flex items-start justify-between gap-3"><div><p className="text-[7px] font-bold uppercase text-[#7b8781]">Conversation inspector</p><h2 className="mt-2 text-[18px] font-bold">{human(item.channel)}</h2><p className="mt-1 text-[7px] text-[#89948f]">{item.contact_reference} · {item.owner}</p></div><Stage value={item.lead_stage}/></div><div className="mt-5 rounded-xl bg-[#f6f8f7] p-4"><b className="text-[8px]">Customer intent</b><p className="mt-2 text-[7px] leading-4 text-[#65736c]">{item.intent_summary}</p></div><div className="mt-4 grid grid-cols-2 gap-2"><Metric label="Consent" value={human(item.contact_consent)}/><Metric label="Window" value={human(item.messaging_window)}/><Metric label="Identity" value={human(item.identity_status)}/><Metric label="Latest draft" value={money(item.latest_draft_total)}/><Metric label="Campaign" value={item.campaign_reference||"Not recorded"}/><Metric label="Ad" value={item.ad_reference||"Not recorded"}/></div><div className="mt-5 grid gap-2 sm:grid-cols-2"><Action label="Human reply draft" disabled={replyBlocked} onClick={()=>open("reply")}/><Action label="Review identity" onClick={()=>open("identity")}/><Action label="Prepare order draft" disabled={item.identity_status!=="verified"} onClick={()=>open("order")}/><Action label="Update lead stage" onClick={()=>open("stage")}/></div>{replyBlocked&&<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-[7px] leading-4 text-amber-800">Outbound draft remains blocked until consent, permitted purpose and messaging window are verified.</div>}<div className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-[7px] leading-4 text-rose-700"><b>Safety boundary:</b> saving here never sends a message, merges a profile, creates an order, changes stock or transmits a Meta event.</div></>}
function Action({disabled=false,label,onClick}:{disabled?:boolean;label:string;onClick:()=>void}){return <button disabled={disabled} onClick={onClick} className="h-10 rounded-xl border bg-white text-[8px] font-bold text-[#426d72] disabled:cursor-not-allowed disabled:opacity-35">{label}</button>}
function Stage({value}:{value:string}){return <span className={`h-fit rounded-full px-2.5 py-1 text-[7px] font-bold ${stageTone[value]||stageTone.new_inquiry}`}>{human(value)}</span>}
function Alert({bad=false,children}:{bad?:boolean;children:React.ReactNode}){return <div className={`rounded-xl border p-3 text-[8px] font-bold ${bad?"border-rose-200 bg-rose-50 text-rose-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{children}</div>}
function Empty(){return <div className="flex min-h-[610px] flex-col items-center justify-center text-center"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#edf3f4] text-xl">↔</span><b className="mt-4 text-[10px]">No conversation evidence found</b><p className="mt-2 max-w-sm text-[7px] text-[#89948f]">Record a real thread only when its channel, purpose and source are known. No sample conversation is seeded.</p></div>}
function Metric({label,value}:{label:string;value:React.ReactNode}){return <div className="min-w-0 rounded-xl border p-3"><small className="text-[6px] font-bold uppercase text-[#89948f]">{label}</small><b className="mt-1.5 block truncate text-[9px]">{value}</b></div>}
function Info({title,text}:{title:string;text:string}){return <div className="rounded-2xl border bg-white p-4"><b className="text-[7px] uppercase">{title}</b><p className="mt-2 text-[7px] leading-4 text-[#89948f]">{text}</p></div>}
function Modal({children,close,title}:{children:React.ReactNode;close:()=>void;title:string}){return <div className="fixed inset-0 z-[120] flex items-center justify-center bg-[#17231f]/40 p-3"><section className="max-h-[94vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white"><header className="flex items-center justify-between border-b p-5"><h2 className="text-[17px] font-bold">{title}</h2><button className="rounded-xl border px-3 py-2 text-[8px]" onClick={close}>Close</button></header>{children}</section></div>}
function Input({label,set,value,placeholder=""}:{label:string;set:(value:string)=>void;value:string;placeholder?:string}){return <label className="block"><span className="mb-1 block text-[7px] font-bold uppercase">{label}</span><input className="h-10 w-full rounded-xl border px-3 text-[9px]" placeholder={placeholder} value={value} onChange={event=>set(event.target.value)}/></label>}
function Select({children,label,set,value}:{children:React.ReactNode;label:string;set:(value:string)=>void;value:string}){return <label className="block"><span className="mb-1 block text-[7px] font-bold uppercase">{label}</span><select className="h-10 w-full rounded-xl border bg-white px-3 text-[9px]" value={value} onChange={event=>set(event.target.value)}>{children}</select></label>}
function Confirm({checked,children,set}:{checked:boolean;children:React.ReactNode;set:(value:boolean)=>void}){return <label className="flex gap-2 rounded-xl bg-amber-50 p-3 text-[7px] leading-4 text-amber-800"><input type="checkbox" checked={checked} onChange={event=>set(event.target.checked)}/>{children}</label>}
function Save({children,disabled,onClick}:{children:React.ReactNode;disabled:boolean;onClick:()=>void}){return <button className="h-10 w-full rounded-xl bg-[#426d72] text-[8px] font-bold text-white disabled:opacity-40" disabled={disabled} onClick={onClick}>{children}</button>}

function Intake({close,save,saving}:{close:()=>void;save:(input:Record<string,unknown>)=>void;saving:boolean}){const[channel,setChannel]=useState("messenger"),[thread,setThread]=useState(""),[contact,setContact]=useState(""),[intent,setIntent]=useState(""),[purpose,setPurpose]=useState("sales_service"),[consent,setConsent]=useState("unknown"),[window,setWindow]=useState("unknown"),[campaign,setCampaign]=useState(""),[ad,setAd]=useState(""),[owner,setOwner]=useState("Commerce Review"),[reason,setReason]=useState(""),[confirmed,setConfirmed]=useState(false);return <Modal title="Record real conversation evidence" close={close}><div className="grid gap-3 p-5 sm:grid-cols-2"><Select label="Channel" value={channel} set={setChannel}><option value="messenger">Messenger</option><option value="whatsapp">WhatsApp</option><option value="instagram">Instagram</option><option value="website_chat">Website chat</option><option value="other">Other</option></Select><Select label="Permitted purpose" value={purpose} set={setPurpose}><option value="sales_service">Sales / service</option><option value="support">Support</option><option value="unknown">Unknown</option></Select><Input label="Real channel thread reference *" value={thread} set={setThread}/><Input label="Real contact reference *" value={contact} set={setContact}/><div className="sm:col-span-2"><Input label="Customer intent summary *" value={intent} set={setIntent}/></div><Select label="Contact consent" value={consent} set={setConsent}><option value="unknown">Unknown</option><option value="active">Active</option><option value="withdrawn">Withdrawn</option></Select><Select label="Messaging window" value={window} set={setWindow}><option value="unknown">Unknown</option><option value="open">Open</option><option value="closed">Closed</option></Select><Input label="Campaign reference" value={campaign} set={setCampaign}/><Input label="Ad reference" value={ad} set={setAd}/><Input label="Accountable owner *" value={owner} set={setOwner}/><Input label="Audit reason *" value={reason} set={setReason}/><div className="sm:col-span-2"><Confirm checked={confirmed} set={setConfirmed}>This records evidence only. It does not message the contact, merge a customer, create an order or send an ad-platform event.</Confirm></div><div className="sm:col-span-2"><Save disabled={!confirmed||!thread||!contact||intent.length<8||reason.length<12||saving} onClick={()=>save({actor:owner,ad_reference:ad,campaign_reference:campaign,channel,contact_consent:consent,contact_reference:contact,intent_summary:intent,messaging_window:window,owner,permitted_purpose:purpose,reason,thread_reference:thread})}>{saving?"Saving...":"Record evidence"}</Save></div></div></Modal>}
function Reply({close,item,save,saving}:{close:()=>void;item:CommerceConversation;save:(input:Record<string,unknown>)=>void;saving:boolean}){const[language,setLanguage]=useState("bangla"),[text,setText]=useState(""),[reason,setReason]=useState(""),[facts,setFacts]=useState(false),[approved,setApproved]=useState(false),[confirmed,setConfirmed]=useState(false);return <Modal title="Prepare human-approved reply draft" close={close}><div className="space-y-3 p-5"><Select label="Language" value={language} set={setLanguage}><option value="bangla">Bangla</option><option value="banglish">Banglish</option><option value="english">English</option></Select><textarea className="min-h-32 w-full rounded-xl border p-3 text-[9px]" placeholder="Exact reply text..." value={text} onChange={event=>setText(event.target.value)}/><Input label="Audit reason *" value={reason} set={setReason}/><Confirm checked={facts} set={setFacts}>Published product facts, price and stock claims have been verified.</Confirm><Confirm checked={approved} set={setApproved}>A human owner approved this exact text.</Confirm><Confirm checked={confirmed} set={setConfirmed}>Save as a draft only. Nothing will be sent automatically.</Confirm><Save disabled={!confirmed||!facts||!approved||text.length<20||reason.length<12||saving} onClick={()=>save({actor:item.owner,conversation_id:item.id,exact_text:text,facts_verified:true,human_approved:true,language,reason})}>{saving?"Saving...":"Save reply draft"}</Save></div></Modal>}
function Identity({close,item,save,saving}:{close:()=>void;item:CommerceConversation;save:(input:Record<string,unknown>)=>void;saving:boolean}){const[decision,setDecision]=useState("held"),[candidate,setCandidate]=useState(""),[reason,setReason]=useState(""),[confirmed,setConfirmed]=useState(false);return <Modal title="Review customer identity" close={close}><div className="space-y-3 p-5"><Select label="Human decision" value={decision} set={setDecision}><option value="held">Hold for review</option><option value="unresolved">Unresolved</option><option value="suggested">Suggested match</option><option value="verified">Verified customer reference</option></Select><Input label="Candidate customer reference" value={candidate} set={setCandidate}/><Input label="Decision reason *" value={reason} set={setReason}/><Confirm checked={confirmed} set={setConfirmed}>This records a review decision only; it does not merge or rewrite customer profiles.</Confirm><Save disabled={!confirmed||reason.length<12||(decision==="verified"&&!candidate)||saving} onClick={()=>save({actor:item.owner,candidate_customer_reference:candidate,conversation_id:item.id,decision,reason})}>{saving?"Saving...":"Record identity review"}</Save></div></Modal>}
function Order({close,item,products,save,saving}:{close:()=>void;item:CommerceConversation;products:CommerceProduct[];save:(input:Record<string,unknown>)=>void;saving:boolean}){const eligible=products.filter(product=>product.status==="active"&&product.price>0&&product.stock>0),[productId,setProductId]=useState(eligible[0]?.id||""),[quantity,setQuantity]=useState("1"),[zone,setZone]=useState("dhaka_city"),[reason,setReason]=useState(""),[confirmed,setConfirmed]=useState(false);const product=eligible.find(value=>value.id===productId);const charge=zone==="dhaka_city"?60:zone==="dhaka_sub_area"?80:120,total=product?product.price*Number(quantity||0)+charge:0;return <Modal title="Prepare reviewable order draft" close={close}><div className="space-y-3 p-5"><Select label="Live eligible product" value={productId} set={setProductId}>{eligible.length?<>{eligible.map(value=><option value={value.id} key={value.id}>{value.name} · ৳{value.price} · stock {value.stock}</option>)}</>:<option value="">No active in-stock product</option>}</Select><Input label="Quantity" value={quantity} set={setQuantity}/><Select label="Delivery zone" value={zone} set={setZone}><option value="dhaka_city">Dhaka City · ৳60</option><option value="dhaka_sub_area">Dhaka Sub Area · ৳80</option><option value="outside_dhaka">Outside Dhaka · ৳120</option></Select><div className="rounded-xl bg-[#f6f8f7] p-3 text-[8px]">Server-verified draft total: <b>{money(total)}</b></div><Input label="Audit reason *" value={reason} set={setReason}/><Confirm checked={confirmed} set={setConfirmed}>Create a reviewable draft only. No order, discount, stock deduction, courier booking, COD or customer message.</Confirm><Save disabled={!confirmed||!productId||Number(quantity)<1||reason.length<12||saving} onClick={()=>save({actor:item.owner,conversation_id:item.id,delivery_zone:zone,product_id:productId,quantity:Number(quantity),reason})}>{saving?"Saving...":"Prepare order draft"}</Save></div></Modal>}
function StageUpdate({close,item,save,saving}:{close:()=>void;item:CommerceConversation;save:(input:Record<string,unknown>)=>void;saving:boolean}){const[next,setNext]=useState(item.lead_stage),[order,setOrder]=useState(item.order_reference),[delivery,setDelivery]=useState(item.delivery_reference),[reason,setReason]=useState(""),[confirmed,setConfirmed]=useState(false);const needsOrder=["order_created","purchased","delivered"].includes(next),needsDelivery=next==="delivered";return <Modal title="Update evidence-backed lead stage" close={close}><div className="space-y-3 p-5"><Select label="Lead stage" value={next} set={setNext}>{["new_inquiry","interested","order_draft","order_created","purchased","delivered","closed"].map(value=><option value={value} key={value}>{human(value)}</option>)}</Select>{needsOrder&&<Input label="Existing order reference *" value={order} set={setOrder}/>} {needsDelivery&&<Input label="Courier-confirmed delivery reference *" value={delivery} set={setDelivery}/>}<Input label="Stage evidence / reason *" value={reason} set={setReason}/><Confirm checked={confirmed} set={setConfirmed}>This saves internal evidence only. Meta/CAPI events and order status remain separate controlled workflows.</Confirm><Save disabled={!confirmed||reason.length<12||(needsOrder&&!order)||(needsDelivery&&!delivery)||saving} onClick={()=>save({actor:item.owner,conversation_id:item.id,delivery_reference:delivery,lead_stage:next,order_reference:order,reason})}>{saving?"Saving...":"Save stage evidence"}</Save></div></Modal>}
