"use client";
import Link from "next/link";
import { formatBdt, useLiveDashboard } from "@/features/dashboard/use-live-dashboard";

const labels:Record<string,string>={pending:"New",pending_sourcing:"Need sourcing",confirmed:"Confirmed",processing:"Packing",packed:"Packed",shipped:"Shipped",delivered:"Delivered",cancelled:"Cancelled",returned:"Returned"};
function Card({label,value,helper,href}:{label:string;value:string;helper:string;href:string}){return <Link href={href} className="group rounded-3xl border border-slate-200/80 bg-white p-5 shadow-[0_14px_34px_rgba(15,23,42,0.045)] transition hover:-translate-y-0.5 hover:border-[#5E7F85]/35"><div className="text-[0.68rem] font-black uppercase tracking-[0.18em] text-slate-400">{label}</div><div className="mt-3 text-3xl font-black tracking-[-0.045em] text-slate-950">{value}</div><div className="mt-4 flex items-center justify-between gap-3 text-xs font-bold text-slate-500"><span>{helper}</span><span className="text-[#527B86] transition group-hover:translate-x-1">Open →</span></div></Link>}
function Step({label,count,href}:{label:string;count:number;href:string}){return <Link href={href} className="rounded-2xl border border-slate-200 bg-white px-4 py-4 transition hover:border-[#5E7F85]/40 hover:bg-[#5E7F85]/5"><div className="text-xs font-bold text-slate-500">{label}</div><div className="mt-2 text-2xl font-black text-slate-950">{count.toLocaleString("en-BD")}</div></Link>}
function priorityHref(key:string){if(key==="cod_mismatch")return"/finance/reconciliation";if(key==="low_stock"||key==="out_of_stock")return"/inventory";if(key==="courier_queue")return"/dispatch-control";return"/orders"}
function dateText(value:string){const d=new Date(value);return !value||Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("en-BD",{dateStyle:"medium",timeStyle:"short"}).format(d)}

export function LiveOwnerDashboard(){
 const{data,owner,error,status,updatedAt,refresh}=useLiveDashboard();
 const maxSales=Math.max(1,...owner.trend.map(r=>r.sales));
 return <div className="space-y-6">
  <section className="flex flex-col gap-4 rounded-[2rem] border border-slate-200/80 bg-white p-6 shadow-[0_16px_40px_rgba(15,23,42,0.05)] lg:flex-row lg:items-end lg:justify-between">
   <div><div className="flex items-center gap-2 text-[0.68rem] font-black uppercase tracking-[0.2em] text-[#527B86]"><span className={`h-2 w-2 rounded-full ${status==="connected"?"bg-emerald-500":status==="error"?"bg-rose-500":"bg-amber-400"}`}/>{status==="connected"?"Live production data":status==="error"?"Dashboard needs attention":"Refreshing production data"}</div><h2 className="mt-3 text-3xl font-black tracking-[-0.05em] text-slate-950">Owner Control Dashboard</h2><p className="mt-2 max-w-3xl text-sm font-medium leading-6 text-slate-500">Real orders, fulfilment, COD, inventory and catalog signals. Every operational card opens the module that owns the data.</p></div>
   <div className="flex flex-wrap items-center gap-3"><span className="text-xs font-bold text-slate-400">{updatedAt?`Updated ${updatedAt.toLocaleTimeString("en-BD",{hour:"2-digit",minute:"2-digit"})}`:"Waiting for first refresh"}</span><button type="button" disabled={status==="loading"} onClick={()=>void refresh()} className="rounded-2xl bg-[#527B86] px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">{status==="loading"?"Refreshing…":"Refresh"}</button></div>
  </section>
  {error?<section className="rounded-2xl border border-rose-200 bg-rose-50 px-5 py-4 text-sm font-bold text-rose-700">{error}</section>:null}
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
   <Card label="Today Orders" value={owner.today.orders.toLocaleString("en-BD")} helper="Open Orders" href="/orders"/>
   <Card label="Booked Revenue" value={formatBdt(data.totalRevenue)} helper="Gross value excluding cancelled" href="/orders"/>
   <Card label="COD Due" value={formatBdt(data.codDue)} helper="Open receivable" href="/finance/reconciliation"/>
   <Card label="Products" value={data.totalProducts.toLocaleString("en-BD")} helper="Manage catalog" href="/products"/>
  </section>
  <section className="rounded-[2rem] border border-slate-200/80 bg-white p-5 shadow-[0_14px_34px_rgba(15,23,42,0.045)]">
   <div className="flex items-end justify-between gap-4"><div><div className="text-[0.68rem] font-black uppercase tracking-[0.18em] text-slate-400">Fulfilment pipeline</div><h3 className="mt-1.5 text-xl font-black text-slate-950">Order movement right now</h3></div><Link href="/orders" className="text-sm font-black text-[#527B86]">Open order command center →</Link></div>
   <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">
    <Step label="New" count={owner.pipeline.new} href="/orders"/><Step label="Confirmed" count={owner.pipeline.confirmed} href="/orders"/><Step label="Packing" count={owner.pipeline.packing} href="/packing"/><Step label="Packed" count={owner.pipeline.packed} href="/packing"/><Step label="Courier ready" count={owner.pipeline.courier_ready} href="/courier"/><Step label="Shipped" count={owner.pipeline.shipped} href="/delivery-monitoring"/><Step label="Delivered" count={owner.pipeline.delivered} href="/orders"/><Step label="Return / cancel" count={owner.pipeline.return_cancel} href="/returns/receiving"/>
   </div>
  </section>
  <section className="grid gap-4 xl:grid-cols-[1.25fr_0.75fr]">
   <article className="rounded-[2rem] border border-slate-200/80 bg-white p-5 shadow-[0_14px_34px_rgba(15,23,42,0.045)]"><div className="text-[0.68rem] font-black uppercase tracking-[0.18em] text-slate-400">7-day trend</div><h3 className="mt-1.5 text-xl font-black text-slate-950">Booked sales and order volume</h3><div className="mt-6 grid h-64 grid-cols-7 items-end gap-2">{owner.trend.map(row=>{const h=Math.max(8,(row.sales/maxSales)*100);return <div key={row.date} className="flex h-full flex-col justify-end gap-2"><div className="text-center text-[0.66rem] font-black text-slate-500">{row.orders}</div><div className="w-full rounded-t-2xl bg-[#5E7F85]/85" style={{height:`${h}%`}} title={`${row.label}: ${formatBdt(row.sales)} · ${row.orders} orders`}/><div className="text-center text-[0.65rem] font-black text-slate-400">{row.label}</div></div>})}</div></article>
   <div className="space-y-4">
    <Link href="/inventory" className="block rounded-[2rem] border border-slate-200/80 bg-white p-5 shadow-[0_14px_34px_rgba(15,23,42,0.045)]"><div className="text-[0.68rem] font-black uppercase tracking-[0.18em] text-slate-400">Inventory attention</div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-amber-50 p-4"><b className="text-2xl text-amber-800">{data.lowStockProducts}</b><div className="mt-1 text-xs font-bold text-amber-700">Low stock</div></div><div className="rounded-2xl bg-rose-50 p-4"><b className="text-2xl text-rose-800">{data.outOfStockProducts}</b><div className="mt-1 text-xs font-bold text-rose-700">Out of stock</div></div></div><div className="mt-4 text-sm font-black text-[#527B86]">Open Inventory →</div></Link>
    <Link href="/finance/reconciliation" className="block rounded-[2rem] border border-slate-200/80 bg-white p-5 shadow-[0_14px_34px_rgba(15,23,42,0.045)]"><div className="text-[0.68rem] font-black uppercase tracking-[0.18em] text-slate-400">COD control</div><div className="mt-3 flex items-end justify-between"><div><b className="text-2xl text-slate-950">{formatBdt(data.codSettled)}</b><div className="mt-1 text-xs font-bold text-slate-500">Settled</div></div><div className="text-right"><b className="text-2xl text-rose-700">{data.codMismatchCount}</b><div className="mt-1 text-xs font-bold text-slate-500">Mismatches</div></div></div></Link>
   </div>
  </section>
  <section className="grid gap-4 xl:grid-cols-2">
   <article className="rounded-[2rem] border border-slate-200/80 bg-white p-5 shadow-[0_14px_34px_rgba(15,23,42,0.045)]"><div className="text-[0.68rem] font-black uppercase tracking-[0.18em] text-slate-400">Priority today</div><h3 className="mt-1.5 text-xl font-black text-slate-950">Exceptions before routine work</h3><div className="mt-5 space-y-3">{owner.priorities.length?owner.priorities.map(p=><Link key={p.key} href={priorityHref(p.key)} className={`flex items-center justify-between rounded-2xl border px-4 py-3.5 ${p.severity==="high"?"border-rose-200 bg-rose-50 text-rose-800":"border-amber-200 bg-amber-50 text-amber-800"}`}><span className="text-sm font-black">{p.label}</span><b className="rounded-full bg-white/80 px-3 py-1.5">{p.count}</b></Link>):<div className="rounded-2xl bg-emerald-50 px-4 py-5 text-sm font-bold text-emerald-700">No active dashboard exception.</div>}</div></article>
   <article className="rounded-[2rem] border border-slate-200/80 bg-white p-5 shadow-[0_14px_34px_rgba(15,23,42,0.045)]"><div className="flex items-end justify-between"><div><div className="text-[0.68rem] font-black uppercase tracking-[0.18em] text-slate-400">Recent orders</div><h3 className="mt-1.5 text-xl font-black text-slate-950">Latest production activity</h3></div><Link href="/orders" className="text-sm font-black text-[#527B86]">All orders →</Link></div><div className="mt-5 divide-y divide-slate-100">{owner.recent_orders.map(o=><Link key={o.id} href="/orders" className="flex items-center justify-between gap-4 py-3.5 hover:bg-stone-50"><div className="min-w-0"><div className="truncate text-sm font-black text-slate-900">{o.order_number} · {o.customer}</div><div className="mt-1 text-xs font-semibold text-slate-400">{dateText(o.created_at)} · {labels[o.status]||o.status}</div></div><div className="shrink-0 text-sm font-black text-slate-700">{formatBdt(o.total)}</div></Link>)}</div></article>
  </section>
  <section className="grid gap-4 xl:grid-cols-[1fr_0.7fr]">
   <article className="rounded-[2rem] border border-slate-200/80 bg-white p-5 shadow-[0_14px_34px_rgba(15,23,42,0.045)]"><div className="flex items-end justify-between"><div><div className="text-[0.68rem] font-black uppercase tracking-[0.18em] text-slate-400">Top products</div><h3 className="mt-1.5 text-xl font-black text-slate-950">Demand from real orders</h3></div><Link href="/products" className="text-sm font-black text-[#527B86]">Catalog →</Link></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[580px] text-left"><thead className="text-[0.65rem] font-black uppercase tracking-[0.14em] text-slate-400"><tr><th className="pb-3">Product</th><th className="pb-3">Qty</th><th className="pb-3">Sales</th><th className="pb-3">Stock</th></tr></thead><tbody className="divide-y divide-slate-100 text-sm">{owner.top_products.map(p=><tr key={p.id}><td className="py-3.5 font-black text-slate-800">{p.name}</td><td className="py-3.5 font-bold text-slate-500">{p.quantity_sold}</td><td className="py-3.5 font-bold text-slate-700">{formatBdt(p.sales)}</td><td className="py-3.5 font-bold text-slate-500">{p.stock_quantity}</td></tr>)}</tbody></table></div></article>
   <article className="rounded-[2rem] border border-slate-200/80 bg-white p-5 shadow-[0_14px_34px_rgba(15,23,42,0.045)]"><div className="text-[0.68rem] font-black uppercase tracking-[0.18em] text-slate-400">Customer base</div><h3 className="mt-1.5 text-xl font-black text-slate-950">Retention signal</h3><div className="mt-5 grid gap-3"><Link href="/customers" className="rounded-2xl bg-stone-50 p-4"><b className="text-2xl text-slate-950">{owner.retention.known_customers}</b><div className="mt-1 text-xs font-bold text-slate-500">Known customers</div></Link><div className="grid grid-cols-2 gap-3"><Link href="/customers/growth" className="rounded-2xl bg-stone-50 p-4"><b className="text-xl text-slate-950">{owner.retention.new_customers}</b><div className="mt-1 text-xs font-bold text-slate-500">Single-order</div></Link><Link href="/customers/growth" className="rounded-2xl bg-stone-50 p-4"><b className="text-xl text-slate-950">{owner.retention.repeat_customers}</b><div className="mt-1 text-xs font-bold text-slate-500">Repeat</div></Link></div></div></article>
  </section>
  <p className="px-1 text-xs font-semibold leading-5 text-slate-400">Booked revenue = order value excluding cancelled orders. COD comes from reconciliation. Profit is intentionally not shown as a headline until direct-cost and ad-spend coverage is complete.</p>
 </div>
}
