"use client";
/* eslint-disable @next/next/no-img-element -- legacy product image URLs are served by the existing PHP catalog */
import {useCallback,useEffect,useMemo,useState} from "react";
import {fetchReplenishment,recordReview,saveControls,Signal,State} from "./replenishment-client";
const empty:State={controls:{due_lead_days:3,minimum_delivered_cycles:2,outreach_cooldown_days:21},generated_at:"",quality:{consent_connected:false,order_items_connected:false,orders_connected:false,privacy_boundary:"",products_connected:false,routine_connected:false},signals:[],summary:{blocked:0,due_now:0,due_soon:0,observed:0,ready:0}};
const labels={due_now:"Due now",due_soon:"Due soon",paused:"Paused",watch:"Watch"};
const tones={due_now:"bg-rose-50 text-rose-700",due_soon:"bg-amber-50 text-amber-700",paused:"bg-slate-100 text-slate-700",watch:"bg-sky-50 text-sky-700"};
export function LiveReplenishmentEngineWorkspace({onNavigate}:{onNavigate:(page:string)=>void}){
 const[state,setState]=useState(empty),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[focusedKey,setFocusedKey]=useState(""),[controlsOpen,setControlsOpen]=useState(false),[review,setReview]=useState<Signal|null>(null),[saving,setSaving]=useState(false);
 const load=useCallback(async(signal?:AbortSignal)=>{setError("");try{const next=await fetchReplenishment(signal);setState(next);setFocusedKey(key=>next.signals.some(item=>item.signal_key===key)?key:next.signals[0]?.signal_key||"")}catch(caught){if(!(caught instanceof DOMException&&caught.name==="AbortError"))setError(caught instanceof Error?caught.message:"Replenishment evidence is temporarily unavailable.")}finally{if(!signal?.aborted)setLoading(false)}},[]);
 useEffect(()=>{const controller=new AbortController();queueMicrotask(()=>void load(controller.signal));return()=>controller.abort()},[load]);
 const filtered=useMemo(()=>state.signals.filter(item=>{const text=`${item.customer_reference} ${item.product_name} ${item.sku} ${item.last_order_reference}`.toLowerCase();return(!query||text.includes(query.toLowerCase()))&&(filter==="all"||item.stage===filter||(filter==="blocked"&&!item.ready_for_outreach))}),[filter,query,state.signals]);
 const focused=state.signals.find(item=>item.signal_key===focusedKey)||null;
 async function doControls(values:{actor:string;cooldown:number;cycles:number;due:number;reason:string}){setSaving(true);try{setState(await saveControls(values));setControlsOpen(false);setNotice("Governed controls saved; automatic actions remain disabled.")}catch(e){setError(e instanceof Error?e.message:"Controls could not be saved.")}finally{setSaving(false)}}
 async function doReview(action:"close"|"hold"|"snooze",actor:string,reason:string){if(!review)return;setSaving(true);try{setState(await recordReview(review.signal_key,action,actor,reason));setReview(null);setNotice("Human review recorded; no reminder, cart or order was created.")}catch(e){setError(e instanceof Error?e.message:"Review could not be recorded.")}finally{setSaving(false)}}
 const stats=[["Observed signals",state.summary.observed,"Repeat delivered product history"],["Ready queue",state.summary.ready,"Every outreach gate passed"],["Due now",state.summary.due_now,"Observed cycle reached"],["Due soon",state.summary.due_soon,"Inside controlled lead window"],["Blocked / paused",state.summary.blocked,"Customer protection active"]] as const;
 return <div className="space-y-5"><section className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[9px] font-extrabold uppercase tracking-[.16em] text-[#167a67]">● Live governed replenishment evidence</p><h1 className="mt-2 text-[28px] font-bold tracking-[-.035em] text-[#17231f] sm:text-[32px]">Customer replenishment & reorder command center</h1><p className="mt-1.5 max-w-4xl text-[12px] leading-5 text-[#66736d]">Observe repeat delivered purchases, live stock and timing while blocking outreach until consent, routine context and human review are complete.</p></div><div className="flex gap-2"><button className="h-11 rounded-xl border bg-white px-4 text-[9px] font-bold" onClick={()=>void load()}>↻ Refresh</button><button className="h-11 rounded-xl bg-[#426d72] px-4 text-[9px] font-bold text-white" onClick={()=>setControlsOpen(true)}>Engine controls</button></div></section>
 <section className="flex items-center justify-between gap-4 rounded-2xl border border-[#d9e4e1] bg-[#edf5f5] p-5"><div><b className="text-[9px] text-[#315a58]">Delivered orders + order items + live products · MySQL connected</b><p className="mt-1 text-[7px] text-[#69817b]">Page load is read-only. Customer identity is hashed server-side and never returned.</p></div><span className="rounded-full bg-white px-3 py-2 text-[7px] font-bold text-[#426d72]">Evidence → gates → human queue</span></section>
 {error&&<Alert tone="rose">{error}</Alert>}{notice&&<Alert tone="emerald">{notice}</Alert>}
 <section className="grid grid-cols-2 gap-3 lg:grid-cols-5">{stats.map(([label,value,note])=><div className="rounded-2xl border bg-white p-4" key={label}><span className="text-[7px] font-bold uppercase tracking-[.1em] text-[#8c9892]">{label}</span><b className="mt-3 block text-[22px] text-[#26352f]">{loading?"—":value}</b><p className="mt-3 border-t pt-3 text-[6.5px] text-[#89948f]">{note}</p></div>)}</section>
 <section className="grid min-h-[720px] gap-4 lg:grid-cols-[1.35fr_.85fr]"><div className="overflow-hidden rounded-2xl border bg-white"><div className="flex flex-col gap-2 border-b p-4 sm:flex-row"><input className="h-10 flex-1 rounded-xl border px-3 text-[9px] outline-none" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search customer reference, product, SKU or order..."/><div className="flex gap-1 overflow-x-auto">{[["all","All"],["due_now","Due now"],["due_soon","Due soon"],["watch","Watch"],["blocked","Blocked"]].map(([key,label])=><button className={`rounded-xl px-3 text-[8px] font-bold ${filter===key?"bg-[#426d72] text-white":"bg-[#f2f5f3]"}`} key={key} onClick={()=>setFilter(key)}>{label}</button>)}</div></div>{filtered.length?<div className="divide-y">{filtered.map(item=><button className={`grid w-full grid-cols-[1fr_auto] gap-3 p-4 text-left hover:bg-[#fafcfb] ${focusedKey===item.signal_key?"bg-[#f2f7f6]":""}`} key={item.signal_key} onClick={()=>setFocusedKey(item.signal_key)}><span><b className="text-[9px] text-[#35443e]">{item.product_name}</b><small className="mt-1 block text-[6.5px] text-[#89948f]">{item.customer_reference} · {item.sku||`Product #${item.product_id}`} · {item.purchases} delivered purchases</small><small className="mt-1 block text-[6.5px] text-[#89948f]">Last {item.last_delivered_at} · {item.cycle_days}-day cycle · stock {item.stock}</small></span><Badge signal={item}/></button>)}</div>:<Empty/>}</div>
 <div className="rounded-2xl border bg-white p-5">{focused?<><div className="flex items-start justify-between gap-3"><div><p className="text-[7px] font-extrabold uppercase tracking-[.12em] text-[#7b8781]">Signal inspector</p><h2 className="mt-2 text-[18px] font-bold">{focused.product_name}</h2><p className="mt-1 text-[7px] text-[#89948f]">{focused.customer_reference} · {focused.last_order_reference}</p></div><Badge signal={focused}/></div>{focused.image&&<img alt="" className="mt-5 h-44 w-full rounded-2xl bg-[#f1f5f3] object-contain" src={focused.image}/>}<div className="mt-5 grid grid-cols-2 gap-2">{[["Observed cycle",`${focused.cycle_days} days`],["Due",focused.due_in_days<=0?`${Math.abs(focused.due_in_days)} days overdue`:`in ${focused.due_in_days} days`],["Live stock",focused.stock],["Current price",`BDT ${focused.current_price}`]].map(([label,value])=><Metric key={label as string} label={label as string} value={value}/>)}</div><div className="mt-5 space-y-2"><b className="text-[8px]">Outreach gates</b>{focused.gates.map(gate=><div className="flex gap-2 rounded-xl bg-[#f6f8f7] p-3" key={gate.key}><span className={gate.state==="pass"?"text-emerald-600":"text-amber-600"}>{gate.state==="pass"?"✓":"△"}</span><span><b className="block text-[7px]">{gate.label}</b>{gate.detail&&<small className="mt-1 block text-[6.5px] text-[#89948f]">{gate.detail}</small>}</span></div>)}</div><button className="mt-5 h-10 w-full rounded-xl border text-[8px] font-bold text-[#426d72]" onClick={()=>setReview(focused)}>Record safe review</button><button className="mt-2 h-10 w-full rounded-xl bg-[#426d72] text-[8px] font-bold text-white" onClick={()=>onNavigate("Inventory")}>Open live inventory</button><div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-[7px] text-amber-800"><b>No automatic action:</b> reminder, discount, cart and order creation remain disabled.</div></>:<div className="flex min-h-[650px] items-center justify-center text-center"><span><b className="text-[10px]">Select a replenishment signal</b><p className="mt-2 text-[7px] text-[#8b9691]">Choose real evidence when it exists.</p></span></div>}</div></section>
 {controlsOpen&&<Controls controls={state.controls} onClose={()=>setControlsOpen(false)} onSave={doControls} saving={saving}/>} {review&&<Review onClose={()=>setReview(null)} onSave={doReview} saving={saving}/>}<section className="grid gap-3 md:grid-cols-3"><Info title="Source of truth" text="Delivered orders, order items and live product stock."/><Info title="Privacy boundary" text="Customer identity is hashed; no contact detail is returned."/><Info title="Safety boundary" text="Zero automatic reminder, discount, cart, order or customer mutation."/></section></div>
}
function Alert({children,tone}:{children:React.ReactNode;tone:"emerald"|"rose"}){return <div className={`rounded-xl border p-3 text-[8px] font-bold ${tone==="rose"?"border-rose-200 bg-rose-50 text-rose-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{children}</div>}
function Badge({signal}:{signal:Signal}){return <span className={`h-fit rounded-full px-2.5 py-1 text-[7px] font-bold ${tones[signal.stage]}`}>{labels[signal.stage]}</span>}
function Empty(){return <div className="flex min-h-[570px] flex-col items-center justify-center text-center"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#edf3f4] text-xl text-[#426d72]">↻</span><b className="mt-4 text-[10px]">No replenishment signal found</b><p className="mt-2 max-w-sm text-[7px] text-[#8b9691]">Signals require repeat real delivered purchases for the same customer and product. No sample signal is seeded.</p></div>}
function Metric({label,value}:{label:string;value:React.ReactNode}){return <div className="rounded-xl border p-3"><small className="text-[6px] font-bold uppercase text-[#8b9691]">{label}</small><b className="mt-1.5 block text-[9px]">{value}</b></div>}
function Info({text,title}:{text:string;title:string}){return <div className="rounded-2xl border bg-white p-4"><b className="text-[7px] uppercase tracking-[.1em]">{title}</b><p className="mt-2 text-[7px] text-[#89948f]">{text}</p></div>}
function Modal({children,onClose,title}:{children:React.ReactNode;onClose:()=>void;title:string}){return <div className="fixed inset-0 z-[120] flex items-center justify-center bg-[#17231f]/40 p-3"><section className="w-full max-w-lg rounded-2xl bg-white"><header className="flex items-center justify-between border-b p-5"><h2 className="text-[17px] font-bold">{title}</h2><button className="rounded-xl border px-3 py-2 text-[8px]" onClick={onClose}>Close</button></header>{children}</section></div>}
function Controls({controls,onClose,onSave,saving}:{controls:State["controls"];onClose:()=>void;onSave:(v:{actor:string;cooldown:number;cycles:number;due:number;reason:string})=>void;saving:boolean}){const[due,setDue]=useState(controls.due_lead_days),[cycles,setCycles]=useState(controls.minimum_delivered_cycles),[cooldown,setCooldown]=useState(controls.outreach_cooldown_days),[reason,setReason]=useState(""),[confirmed,setConfirmed]=useState(false);return <Modal title="Governed engine controls" onClose={onClose}><div className="space-y-3 p-5"><Num label="Due lead days" value={due} set={setDue}/><Num label="Minimum delivered purchases" value={cycles} set={setCycles}/><Num label="Outreach cooldown days" value={cooldown} set={setCooldown}/><textarea className="min-h-24 w-full rounded-xl border p-3 text-[9px]" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Audit reason (at least 12 characters)"/><Confirm checked={confirmed} set={setConfirmed}>Consent, routine context, human approval and automatic-action blocks stay enabled.</Confirm><button className="h-10 w-full rounded-xl bg-[#426d72] text-[8px] font-bold text-white disabled:opacity-40" disabled={!confirmed||reason.trim().length<12||saving} onClick={()=>onSave({actor:"Admin",cooldown,cycles,due,reason})}>{saving?"Saving...":"Save controlled settings"}</button></div></Modal>}
function Review({onClose,onSave,saving}:{onClose:()=>void;onSave:(a:"close"|"hold"|"snooze",b:string,c:string)=>void;saving:boolean}){const[action,setAction]=useState<"close"|"hold"|"snooze">("snooze"),[reason,setReason]=useState(""),[confirmed,setConfirmed]=useState(false);return <Modal title="Record safe human review" onClose={onClose}><div className="space-y-3 p-5"><select className="h-10 w-full rounded-xl border px-3 text-[9px]" value={action} onChange={e=>setAction(e.target.value as typeof action)}><option value="snooze">Snooze signal</option><option value="hold">Keep on hold</option><option value="close">Close signal</option></select><textarea className="min-h-24 w-full rounded-xl border p-3 text-[9px]" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Review reason (at least 12 characters)"/><Confirm checked={confirmed} set={setConfirmed}>No customer contact, reminder, cart or order is created.</Confirm><button className="h-10 w-full rounded-xl bg-[#426d72] text-[8px] font-bold text-white disabled:opacity-40" disabled={!confirmed||reason.trim().length<12||saving} onClick={()=>onSave(action,"Customer Care",reason)}>{saving?"Recording...":"Record review evidence"}</button></div></Modal>}
function Num({label,set,value}:{label:string;set:(v:number)=>void;value:number}){return <label className="block"><span className="mb-1 block text-[7px] font-bold uppercase">{label}</span><input className="h-10 w-full rounded-xl border px-3 text-[9px]" min={0} type="number" value={value} onChange={e=>set(Number(e.target.value))}/></label>}
function Confirm({checked,children,set}:{checked:boolean;children:React.ReactNode;set:(v:boolean)=>void}){return <label className="flex gap-2 rounded-xl bg-amber-50 p-3 text-[7px] text-amber-800"><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)}/>{children}</label>}
