"use client";

import { useEffect, useState } from "react";
import type { ReactNode } from "react";
import { advancePrivacyRequest, createPrivacyRequest, loadPrivacyCenter, reviewPrivacyPolicy, runPrivacyConsentTest } from "./privacy-center-client";
import type { PrivacyCenterState, PrivacyRequest, PrivacyRetentionPolicy } from "./privacy-center-client";

type Tab = "Privacy requests" | "Retention policies" | "Consent ledger" | "Activity" | "Safety";
const tabs: Tab[] = ["Privacy requests", "Retention policies", "Consent ledger", "Activity", "Safety"];
const input = "mt-1.5 h-10 w-full rounded-xl border border-[#dce4e0] bg-white px-3 text-[9px] text-[#405049] outline-none focus:border-[#9eb7b4]";
const area = "mt-1.5 min-h-24 w-full resize-none rounded-xl border border-[#dce4e0] bg-white p-3 text-[9px] text-[#405049] outline-none focus:border-[#9eb7b4]";
const dateTime = (value: string | null) => { if (!value) return "Never"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(date); };
const human = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

function Icon({ name, size = 16 }: { name: string; size?: number }) {
  const paths: Record<string, ReactNode> = {
    privacy: <><path d="M12 3 4.5 6v5c0 4.8 3.2 8.3 7.5 10 4.3-1.7 7.5-5.2 7.5-10V6L12 3Z"/><path d="M9 12h6M12 9v6"/></>,
    refresh: <><path d="M20 11a8 8 0 1 0-2.34 5.66"/><path d="M20 4v7h-7"/></>,
    cookie: <><path d="M20 12.5A8.5 8.5 0 1 1 11.5 4c0 2 1.5 3.5 3.5 3.5 0 2 1.5 3.5 3.5 3.5.5 0 1-.1 1.5-.3v1.8Z"/><path d="M8 11h.01M11 16h.01M7 16h.01"/></>,
    request: <><path d="M6 3h9l3 3v15H6V3Z"/><path d="M15 3v4h4M9 12h6M9 16h4"/></>,
    close: <><path d="m6 6 12 12M18 6 6 18"/></>,
    check: <path d="m5 12 4 4L19 6"/>,
    warning: <><path d="M10.3 3.6 2.8 17a2 2 0 0 0 1.7 3h15a2 2 0 0 0 1.7-3L13.7 3.6a2 2 0 0 0-3.4 0Z"/><path d="M12 9v4M12 17h.01"/></>,
  };
  return <svg aria-hidden="true" fill="none" height={size} stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" viewBox="0 0 24 24" width={size}>{paths[name] ?? paths.privacy}</svg>;
}

function Tone({ value }: { value: string }) {
  const key = value.toLowerCase();
  const tone = ["approved","completed","storefront","ready"].includes(key) ? "bg-emerald-50 text-emerald-700 ring-emerald-200" : ["erasure","rejected","cancelled"].includes(key) ? "bg-rose-50 text-rose-700 ring-rose-200" : ["review_required","open","identity_verification","paused","admin_test"].includes(key) ? "bg-amber-50 text-amber-700 ring-amber-200" : "bg-slate-100 text-slate-600 ring-slate-200";
  return <span className={`${tone} inline-flex whitespace-nowrap rounded-full px-2 py-1 text-[7px] font-bold capitalize ring-1 ring-inset`}>{value.replaceAll("_", " ")}</span>;
}

function Kpi({ label, note, value, warning = false }: { label: string; note: string; value: string | number; warning?: boolean }) {
  return <article className="rounded-2xl border border-[#dfe6e2] bg-white p-5"><div className="flex items-start justify-between"><div><p className="text-[7px] font-bold uppercase tracking-[.12em] text-[#84908a]">{label}</p><b className="mt-4 block text-[22px] tracking-tight text-[#17231f]">{value}</b></div><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${warning ? "bg-amber-50 text-amber-700" : "bg-[#edf3f4] text-[#3b646d]"}`}><Icon name={warning ? "warning" : "privacy"}/></span></div><p className="mt-4 border-t pt-3 text-[7px] leading-4 text-[#87928d]">{note}</p></article>;
}

function Modal({ children, onClose, subtitle, titleText }: { children: ReactNode; onClose: () => void; subtitle: string; titleText: string }) {
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-[#17231f]/40 p-4 backdrop-blur-sm" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><section aria-modal="true" className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl" role="dialog"><header className="flex items-start justify-between border-b p-5"><div><p className="text-[7px] font-bold uppercase tracking-[.12em] text-[#3b646d]">{subtitle}</p><h2 className="mt-1 text-[17px] font-bold text-[#23322b]">{titleText}</h2></div><button aria-label="Close" className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#f2f5f3]" onClick={onClose}><Icon name="close"/></button></header>{children}</section></div>;
}

function nextRequestStatuses(status: string) {
  if (status === "open") return ["identity_verification", "cancelled"];
  if (status === "identity_verification") return ["approved", "rejected", "cancelled"];
  if (status === "approved") return ["completed", "cancelled"];
  return [];
}

export function LivePrivacyCenterWorkspace({ onNavigate }: { onNavigate: (page: string) => void }) {
  const [state, setState] = useState<PrivacyCenterState | null>(null);
  const [tab, setTab] = useState<Tab>("Privacy requests");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [requestOpen, setRequestOpen] = useState(false);
  const [requestType, setRequestType] = useState<"export" | "erasure">("export");
  const [subjectKind, setSubjectKind] = useState("phone");
  const [subjectReference, setSubjectReference] = useState("");
  const [requestNote, setRequestNote] = useState("");
  const [selectedRequest, setSelectedRequest] = useState<PrivacyRequest | null>(null);
  const [requestStatus, setRequestStatus] = useState("");
  const [decisionNote, setDecisionNote] = useState("");
  const [selectedPolicy, setSelectedPolicy] = useState<PrivacyRetentionPolicy | null>(null);
  const [retentionDays, setRetentionDays] = useState("");
  const [policyStatus, setPolicyStatus] = useState("review_required");
  const [policyReason, setPolicyReason] = useState("");
  const [policyConfirmed, setPolicyConfirmed] = useState(false);
  const [testOpen, setTestOpen] = useState(false);
  const [testAnalytics, setTestAnalytics] = useState(false);
  const [testMarketing, setTestMarketing] = useState(false);

  const refresh = async () => { setError(""); try { setState(await loadPrivacyCenter()); } catch (problem) { setError(problem instanceof Error ? problem.message : "Privacy Center is unavailable."); } };
  useEffect(() => { let active = true; void loadPrivacyCenter().then((value) => { if (active) setState(value); }).catch((problem: unknown) => { if (active) setError(problem instanceof Error ? problem.message : "Privacy Center is unavailable."); }); return () => { active = false; }; }, []);
  const act = async (operation: () => Promise<{ message: string; state: PrivacyCenterState }>, close?: () => void) => { setBusy(true); setError(""); try { const result = await operation(); setState(result.state); setNotice(result.message); close?.(); setTimeout(() => setNotice(""),5000); } catch (problem) { setError(problem instanceof Error ? problem.message : "The protected privacy action failed."); } finally { setBusy(false); } };
  const chart = state?.policies ?? [];

  const openPolicy = (policy: PrivacyRetentionPolicy) => { setSelectedPolicy(policy); setRetentionDays(String(policy.retentionDays)); setPolicyStatus(policy.status); setPolicyReason(""); setPolicyConfirmed(false); };
  const savePolicy = () => selectedPolicy && void act(() => reviewPrivacyPolicy(selectedPolicy.id,Number(retentionDays),policyStatus,policyReason),() => setSelectedPolicy(null));
  const openRequestReview = (request: PrivacyRequest) => { const options = nextRequestStatuses(request.status); if (!options.length) return; setSelectedRequest(request); setRequestStatus(options[0]); setDecisionNote(""); };

  return <div className="space-y-5">
    <section className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500"/><p className="text-[9px] font-bold uppercase tracking-[.16em] text-[#3b646d]">Customer privacy control plane</p></div><h1 className="mt-2 text-[28px] font-bold tracking-[-.035em] text-[#17231f] sm:text-[32px]">Privacy Center command center</h1><p className="mt-1.5 max-w-3xl text-[11px] leading-5 text-[#66736d]">Review retention, prove granular cookie choices and manage export or erasure requests—without silently deleting customer records or presenting operational defaults as legal advice.</p></div><div className="flex flex-wrap gap-2"><button className="flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-[8px] font-bold text-[#596962]" disabled={busy} onClick={() => void refresh()}><Icon name="refresh"/>Refresh</button><button className="flex h-10 items-center gap-2 rounded-xl border border-[#3b646d] bg-white px-4 text-[8px] font-bold text-[#3b646d]" disabled={busy} onClick={() => { setTestAnalytics(false); setTestMarketing(false); setTestOpen(true); }}><Icon name="cookie"/>Run cookie test</button><button className="flex h-10 items-center gap-2 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white" disabled={busy} onClick={() => setRequestOpen(true)}><Icon name="request"/>New privacy request</button></div></section>

    {error && <div className="flex items-center justify-between rounded-xl border border-rose-200 bg-rose-50 p-4 text-[8px] font-bold text-rose-700"><span>{error}</span><button className="underline" onClick={() => void refresh()}>Try again</button></div>}
    {notice && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-[8px] font-bold text-emerald-700">{notice}</div>}

    <section className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_auto]"><article className="flex flex-col gap-3 rounded-2xl border border-[#d8e4e1] bg-[#edf3f4] p-4 sm:flex-row sm:items-center"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white text-[#3b646d]"><Icon name="privacy"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-[9px] text-[#304d4d]">Human-controlled privacy operations · MySQL connected</b><span className="rounded-full bg-emerald-50 px-2 py-1 text-[6.5px] font-bold text-emerald-700">Masked identifiers</span><span className="rounded-full bg-white px-2 py-1 text-[6.5px] font-bold text-[#65736c]">Generated {dateTime(state?.generatedAt ?? null)}</span></div><p className="mt-1.5 text-[7px] text-[#647b77]">Essential consent remains on. Analytics and Marketing are optional, separate choices. Requests never trigger automatic deletion.</p></div></article><div className={`flex items-center gap-2 rounded-2xl border px-4 py-3 ${(state?.summary.openRequests ?? 0)>0?"border-amber-200 bg-amber-50":"border-emerald-200 bg-emerald-50"}`}><Icon name={(state?.summary.openRequests ?? 0)>0?"warning":"check"}/><div><b className="block text-[8px] text-[#405049]">{state?.summary.openRequests ?? 0} open request(s)</b><span className="mt-1 block text-[6.5px] text-[#718079]">Identity review required</span></div></div></section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Kpi label="Privacy requests" note="Export + erasure ledger" value={state?.summary.totalRequests ?? 0}/><Kpi label="Open requests" note="Human review queue" value={state?.summary.openRequests ?? 0} warning={Boolean(state?.summary.openRequests)}/><Kpi label="Export" note="Access-copy requests" value={state?.summary.exportRequests ?? 0}/><Kpi label="Erasure" note="No automatic deletion" value={state?.summary.erasureRequests ?? 0}/><Kpi label="Storefront consent" note="Real consent decisions" value={state?.summary.storefrontConsents ?? 0}/><Kpi label="Policy review" note="Defaults need approval" value={state?.summary.policiesReviewRequired ?? 0} warning={Boolean(state?.summary.policiesReviewRequired)}/></section>

    <section className="grid gap-4 xl:grid-cols-[minmax(0,1.2fr)_minmax(360px,.8fr)]"><article className="rounded-2xl border bg-white p-5"><div className="flex items-start justify-between"><div><p className="text-[8px] font-bold uppercase tracking-[.12em] text-[#84908a]">Retention posture</p><h2 className="mt-1 text-[14px] font-bold text-[#33423b]">Configured review periods</h2></div><span className="rounded-full bg-amber-50 px-2 py-1 text-[7px] font-bold text-amber-700">Not legal advice</span></div><div className="mt-6 flex h-44 items-end gap-3 border-b px-2">{chart.map((item) => <div className="group relative flex h-full flex-1 items-end" key={item.id}><div className={`${item.status==="approved"?"bg-[#5f8585]":item.status==="paused"?"bg-slate-300":"bg-amber-300"} w-full rounded-t`} style={{height:`${Math.max(8,Math.min(100,item.retentionDays/36.5))}%`}}/><span className="absolute -top-7 left-1/2 hidden -translate-x-1/2 whitespace-nowrap rounded bg-[#233f42] px-2 py-1 text-[6px] text-white group-hover:block">{item.retentionDays} days · v{item.version}</span></div>)}</div><p className="mt-4 text-[7px] leading-4 text-[#718079]">These are operational starting points. Confirm accounting, consumer-rights, tax and other obligations with qualified advisers before production approval.</p></article><article className="rounded-2xl border border-[#d6e2df] bg-[#edf3f4] p-5"><p className="text-[8px] font-bold uppercase tracking-[.12em] text-[#5e7875]">Cookie choices</p><h2 className="mt-1 text-[14px] font-bold text-[#304d4d]">Granular consent contract</h2><div className="mt-4 space-y-2">{state?.cookieConfig.categories.map((item) => <div className="flex items-center justify-between rounded-xl bg-white p-3" key={item.key}><div><b className="block text-[8px] text-[#405049]">{item.label}</b><span className="mt-1 block text-[6.5px] text-[#87928d]">{item.required?"Required for core storefront":"Optional · off by default"}</span></div><Tone value={item.required?"ready":"optional"}/></div>)}</div><div className="mt-4 grid grid-cols-3 divide-x rounded-xl bg-white p-3 text-center"><div><b className="block text-[11px]">{state?.consentBreakdown.essentialOnly ?? 0}</b><span className="text-[6px] text-[#87928d]">Essential only</span></div><div><b className="block text-[11px]">{state?.consentBreakdown.analytics ?? 0}</b><span className="text-[6px] text-[#87928d]">Analytics</span></div><div><b className="block text-[11px]">{state?.consentBreakdown.marketing ?? 0}</b><span className="text-[6px] text-[#87928d]">Marketing</span></div></div></article></section>

    <section className="overflow-hidden rounded-2xl border border-[#dfe6e2] bg-white"><header className="flex flex-col gap-3 border-b p-4 xl:flex-row xl:items-center xl:justify-between"><div className="flex flex-wrap gap-1">{tabs.map((item) => <button className={`h-10 rounded-xl px-4 text-[8px] font-bold ${tab===item?"bg-[#3b646d] text-white":"bg-[#f2f5f3] text-[#74817b]"}`} key={item} onClick={() => setTab(item)}>{item}{item==="Privacy requests"?` ${state?.requests.length ?? 0}`:""}</button>)}</div><span className="text-[7px] font-semibold text-[#87928d]">Retention automation: off</span></header>

      {tab==="Privacy requests" && <div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left"><thead className="bg-[#fafbfa] text-[6.5px] font-bold uppercase tracking-[.1em] text-[#8a9590]"><tr><th className="px-5 py-3">Request</th><th className="px-4 py-3">Masked subject</th><th className="px-4 py-3">Matches</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Requested</th><th className="px-5 py-3 text-right">Control</th></tr></thead><tbody className="divide-y">{state?.requests.map((item) => <tr className="text-[8px] text-[#596861]" key={item.id}><td className="px-5 py-4"><div className="flex items-center gap-2"><b className="text-[#35443d]">#{item.id} · {human(item.requestType)}</b><Tone value={item.requestType}/></div><span className="mt-1 block max-w-md text-[6.5px] leading-3.5 text-[#929d97]">{item.requestNote}</span></td><td className="px-4 py-4"><b>{item.subjectMask}</b><span className="mt-1 block text-[6.5px] text-[#929d97]">{human(item.subjectKind)}</span></td><td className="px-4 py-4">{item.matchCount} order record(s)</td><td className="px-4 py-4"><Tone value={item.status}/></td><td className="px-4 py-4">{dateTime(item.requestedAt)}</td><td className="px-5 py-4 text-right"><button className="h-8 rounded-lg border px-3 text-[7px] font-bold disabled:opacity-40" disabled={!nextRequestStatuses(item.status).length} onClick={() => openRequestReview(item)}>Review</button></td></tr>)}</tbody></table>{!state?.requests.length && <div className="flex min-h-64 flex-col items-center justify-center text-[8px] text-[#87928d]"><Icon name="request"/><b className="mt-3">No privacy request has been recorded.</b><span className="mt-1">Open an export or erasure request when a verified customer asks.</span></div>}</div>}

      {tab==="Retention policies" && <div className="divide-y">{state?.policies.map((item) => <div className="grid gap-3 p-5 text-[8px] lg:grid-cols-[220px_1fr_140px_140px_90px] lg:items-center" key={item.id}><div><b className="text-[#35443d]">{item.label}</b><span className="mt-1 block text-[6.5px] text-[#87928d]">{item.policyKey}</span></div><p className="leading-4 text-[#65736c]">{item.scope}</p><b>{item.retentionDays} days · v{item.version}</b><Tone value={item.status}/><button className="h-8 rounded-lg border px-3 text-[7px] font-bold" onClick={() => openPolicy(item)}>Review</button></div>)}</div>}

      {tab==="Consent ledger" && <div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left"><thead className="bg-[#fafbfa] text-[6.5px] font-bold uppercase tracking-[.1em] text-[#8a9590]"><tr><th className="px-5 py-3">Decision</th><th className="px-4 py-3">Essential</th><th className="px-4 py-3">Analytics</th><th className="px-4 py-3">Marketing</th><th className="px-4 py-3">Source</th><th className="px-5 py-3">Recorded</th></tr></thead><tbody className="divide-y">{state?.consents.map((item) => <tr className="text-[8px] text-[#596861]" key={item.id}><td className="px-5 py-4">Consent #{item.id} · policy v{item.policyVersion}</td><td className="px-4 py-4"><Tone value={item.essential?"ready":"blocked"}/></td><td className="px-4 py-4">{item.analytics?"Enabled":"Disabled"}</td><td className="px-4 py-4">{item.marketing?"Enabled":"Disabled"}</td><td className="px-4 py-4"><Tone value={item.source}/></td><td className="px-5 py-4">{dateTime(item.occurredAt)}</td></tr>)}</tbody></table>{!state?.consents.length && <p className="p-16 text-center text-[9px] text-[#87928d]">No storefront or acceptance-test consent decision exists.</p>}</div>}

      {tab==="Activity" && <div className="divide-y">{state?.events.length?state.events.map((item) => <div className="grid gap-3 p-5 text-[8px] lg:grid-cols-[210px_1fr_180px] lg:items-center" key={item.id}><div><b className="text-[#35443d]">{human(item.eventType)}</b><span className="mt-1 block text-[6.5px] text-[#87928d]">{item.subjectLabel}</span></div><p className="leading-4 text-[#65736c]">{item.note}</p><span>{item.actorName} · {dateTime(item.createdAt)}</span></div>):<p className="p-16 text-center text-[9px] text-[#87928d]">No Privacy Center event has been recorded.</p>}</div>}

      {tab==="Safety" && <div className="grid gap-3 p-5 sm:grid-cols-2"><Kpi label="Legal advice" note="Operational defaults require qualified legal and accounting review." value="Not provided"/><Kpi label="Automatic erasure" note="Requests move through identity verification and explicit human approval." value="Blocked"/><Kpi label="Raw identity response" note="Phone, email and order references are hashed and masked before storage responses." value="Blocked"/><Kpi label="Retention cron" note="No hosting or local cleanup schedule is configured by this installer." value="Not configured"/></div>}
    </section>

    <section className="flex flex-col gap-3 rounded-2xl border border-[#d8e4e1] bg-[#edf3f4] p-5 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-[10px] text-[#304d4d]">Privacy evidence remains connected to access, audit and recovery controls</b><p className="mt-1 text-[7px] text-[#647b77]">Use Security Audit for assurance evidence and Audit Logs for protected control history.</p></div><div className="flex gap-2"><button className="h-10 rounded-xl bg-white px-4 text-[8px] font-bold text-[#3b646d] ring-1 ring-[#cad9d5]" onClick={() => onNavigate("Security Audit")}>Security Audit</button><button className="h-10 rounded-xl bg-white px-4 text-[8px] font-bold text-[#3b646d] ring-1 ring-[#cad9d5]" onClick={() => onNavigate("Audit Logs")}>Audit Logs</button></div></section>

    {requestOpen && <Modal onClose={() => setRequestOpen(false)} subtitle="Customer-controlled privacy workflow" titleText="Open privacy request"><div className="grid gap-4 p-5 sm:grid-cols-2"><label className="block text-[8px] font-bold">Request type<select className={input} onChange={(event) => setRequestType(event.target.value as "export"|"erasure")} value={requestType}><option value="export">Data export</option><option value="erasure">Erasure review</option></select></label><label className="block text-[8px] font-bold">Subject reference type<select className={input} onChange={(event) => setSubjectKind(event.target.value)} value={subjectKind}><option value="phone">Phone</option><option value="email">Email</option><option value="order_reference">Order reference</option></select></label><label className="block text-[8px] font-bold sm:col-span-2">Customer-provided reference<input className={input} onChange={(event) => setSubjectReference(event.target.value)} placeholder="Used once to create a hash and masked reference" value={subjectReference}/></label><label className="block text-[8px] font-bold sm:col-span-2">Request note<textarea className={area} onChange={(event) => setRequestNote(event.target.value)} placeholder="How and when was this request received?" value={requestNote}/></label><p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-[8px] leading-4 text-amber-800 sm:col-span-2">Opening an erasure request never deletes customer, order, invoice or finance records. Identity, conflicting retention duties and owner approval must be reviewed first.</p></div><footer className="flex justify-end gap-2 border-t p-4"><button className="h-10 rounded-xl border px-4 text-[8px] font-bold" onClick={() => setRequestOpen(false)}>Cancel</button><button className="h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-40" disabled={busy||subjectReference.trim().length<3||requestNote.trim().length<8} onClick={() => void act(() => createPrivacyRequest(requestType,subjectKind,subjectReference,requestNote),() => { setRequestOpen(false); setSubjectReference(""); setRequestNote(""); })}>Open request</button></footer></Modal>}

    {selectedRequest && <Modal onClose={() => setSelectedRequest(null)} subtitle={`${human(selectedRequest.requestType)} request · ${selectedRequest.subjectMask}`} titleText={`Review privacy request #${selectedRequest.id}`}><div className="space-y-4 p-5"><div className="rounded-xl border bg-[#fafbfa] p-4 text-[8px]"><b>{selectedRequest.matchCount} matching order record(s)</b><p className="mt-2 leading-4 text-[#718079]">{selectedRequest.requestNote}</p></div><label className="block text-[8px] font-bold">Next status<select className={input} onChange={(event) => setRequestStatus(event.target.value)} value={requestStatus}>{nextRequestStatuses(selectedRequest.status).map((item) => <option key={item} value={item}>{human(item)}</option>)}</select></label><label className="block text-[8px] font-bold">Review note<textarea className={area} onChange={(event) => setDecisionNote(event.target.value)} value={decisionNote}/></label><p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-[8px] leading-4 text-amber-800">This records the accountable workflow stage only. It performs no automatic export, erasure or business-record mutation.</p></div><footer className="flex justify-end gap-2 border-t p-4"><button className="h-10 rounded-xl border px-4 text-[8px] font-bold" onClick={() => setSelectedRequest(null)}>Cancel</button><button className="h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-40" disabled={busy||decisionNote.trim().length<8} onClick={() => void act(() => advancePrivacyRequest(selectedRequest.id,requestStatus,decisionNote),() => setSelectedRequest(null))}>Record review</button></footer></Modal>}

    {selectedPolicy && <Modal onClose={() => setSelectedPolicy(null)} subtitle={`Retention policy · version ${selectedPolicy.version}`} titleText={selectedPolicy.label}><div className="space-y-4 p-5"><p className="rounded-xl border bg-[#fafbfa] p-4 text-[8px] leading-4 text-[#718079]">{selectedPolicy.scope}</p><div className="grid gap-4 sm:grid-cols-2"><label className="block text-[8px] font-bold">Retention days<input className={input} min="30" max="3650" onChange={(event) => setRetentionDays(event.target.value)} type="number" value={retentionDays}/></label><label className="block text-[8px] font-bold">Review status<select className={input} onChange={(event) => setPolicyStatus(event.target.value)} value={policyStatus}><option value="review_required">Review required</option><option value="approved">Approved operationally</option><option value="paused">Paused</option></select></label></div><label className="block text-[8px] font-bold">Change and review reason<textarea className={area} onChange={(event) => setPolicyReason(event.target.value)} value={policyReason}/></label><label className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-[8px] leading-4 text-amber-800"><input checked={policyConfirmed} onChange={(event) => setPolicyConfirmed(event.target.checked)} type="checkbox"/><span>I confirm this is an operational retention review, not legal advice, and it will not delete existing records automatically.</span></label></div><footer className="flex justify-end gap-2 border-t p-4"><button className="h-10 rounded-xl border px-4 text-[8px] font-bold" onClick={() => setSelectedPolicy(null)}>Cancel</button><button className="h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-40" disabled={busy||!policyConfirmed||policyReason.trim().length<12||Number(retentionDays)<30||Number(retentionDays)>3650} onClick={savePolicy}>Save reviewed version</button></footer></Modal>}

    {testOpen && <Modal onClose={() => setTestOpen(false)} subtitle="Synthetic acceptance check" titleText="Test cookie-consent choices"><div className="space-y-3 p-5"><label className="flex items-center justify-between rounded-xl border bg-[#fafbfa] p-4 text-[8px]"><span><b>Essential</b><small className="mt-1 block text-[#87928d]">Required for cart, checkout and security</small></span><input checked disabled type="checkbox"/></label><label className="flex items-center justify-between rounded-xl border p-4 text-[8px]"><span><b>Analytics</b><small className="mt-1 block text-[#87928d]">Optional measurement choice</small></span><input checked={testAnalytics} onChange={(event) => setTestAnalytics(event.target.checked)} type="checkbox"/></label><label className="flex items-center justify-between rounded-xl border p-4 text-[8px]"><span><b>Marketing</b><small className="mt-1 block text-[#87928d]">Optional advertising choice</small></span><input checked={testMarketing} onChange={(event) => setTestMarketing(event.target.checked)} type="checkbox"/></label><p className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-[8px] leading-4 text-emerald-800">The test is labelled admin_test and excluded from real storefront-consent totals.</p></div><footer className="flex justify-end gap-2 border-t p-4"><button className="h-10 rounded-xl border px-4 text-[8px] font-bold" onClick={() => setTestOpen(false)}>Cancel</button><button className="h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white" disabled={busy} onClick={() => void act(() => runPrivacyConsentTest(testAnalytics,testMarketing),() => setTestOpen(false))}>Record safe test</button></footer></Modal>}
  </div>;
}
