<?php
declare(strict_types=1);
require_once __DIR__.'/config/db.php'; require_once __DIR__.'/admin_auth.php'; require_once __DIR__.'/replenishment_engine_common.php';
$origin=$_SERVER['HTTP_ORIGIN']??''; if(preg_match('/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/',$origin)===1){header('Access-Control-Allow-Origin: '.$origin);header('Vary: Origin');}
header('Content-Type: application/json; charset=utf-8'); header('Access-Control-Allow-Methods: GET, POST, OPTIONS'); header('Access-Control-Allow-Headers: Content-Type, Authorization, X-Admin-Token'); header('X-Content-Type-Options: nosniff');
if(($_SERVER['REQUEST_METHOD']??'GET')==='OPTIONS'){http_response_code(204);exit;} requireAdminAuth();
function replenishmentJson(int $status,array $payload):never{http_response_code($status);echo json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
try{$pdo=getDatabaseConnection();ensureProductCatalogSchema($pdo);ensureReplenishmentSchema($pdo);$method=$_SERVER['REQUEST_METHOD']??'GET';if($method==='GET')replenishmentJson(200,array_merge(['success'=>true],readReplenishmentState($pdo)));if($method!=='POST')replenishmentJson(405,['success'=>false,'message'=>'Method not allowed.']);
$input=json_decode(file_get_contents('php://input')?:'',true);$input=is_array($input)?$input:[];if(!($input['confirmed']??false))replenishmentJson(422,['success'=>false,'message'=>'Explicit human confirmation is required.']);$action=replenishmentText($input['action']??'',50);$reason=replenishmentText($input['reason']??'',1000);$actor=replenishmentText($input['actor']??'Admin',190);if(strlen($reason)<12)replenishmentJson(422,['success'=>false,'message'=>'A clear audit reason is required.']);
if($action==='save_controls'){$due=max(0,min(30,(int)($input['due_lead_days']??3)));$cycles=max(2,min(20,(int)($input['minimum_delivered_cycles']??2)));$cool=max(1,min(365,(int)($input['outreach_cooldown_days']??21)));$pdo->beginTransaction();$save=$pdo->prepare("INSERT INTO replenishment_controls (id,due_lead_days,minimum_delivered_cycles,outreach_cooldown_days,require_consent,require_stock_price,require_routine_context,human_approval_required,automatic_reminder_enabled,automatic_cart_order_enabled,updated_by) VALUES (1,:due,:cycles,:cool,1,1,1,1,0,0,:actor) ON DUPLICATE KEY UPDATE due_lead_days=VALUES(due_lead_days),minimum_delivered_cycles=VALUES(minimum_delivered_cycles),outreach_cooldown_days=VALUES(outreach_cooldown_days),require_consent=1,require_stock_price=1,require_routine_context=1,human_approval_required=1,automatic_reminder_enabled=0,automatic_cart_order_enabled=0,updated_by=VALUES(updated_by)");$save->execute([':due'=>$due,':cycles'=>$cycles,':cool'=>$cool,':actor'=>$actor]);$version=$pdo->prepare('INSERT INTO replenishment_control_versions (controls_json,reason,created_by) VALUES (:json,:reason,:actor)');$version->execute([':json'=>json_encode(['due_lead_days'=>$due,'minimum_delivered_cycles'=>$cycles,'outreach_cooldown_days'=>$cool],JSON_UNESCAPED_SLASHES),':reason'=>$reason,':actor'=>$actor]);$pdo->commit();replenishmentJson(200,array_merge(['success'=>true,'message'=>'Governed engine controls saved; automatic actions remain disabled.'],readReplenishmentState($pdo)));}
if($action==='record_action'){$signalKey=replenishmentText($input['signal_key']??'',64);$name=replenishmentText($input['action_name']??'',40);$allowed=['snooze','hold','close'];if(!preg_match('/^[a-f0-9]{64}$/',$signalKey)||!in_array($name,$allowed,true))replenishmentJson(422,['success'=>false,'message'=>'Only safe pause, hold or close evidence can be recorded until consent and routine context are linked.']);$save=$pdo->prepare('INSERT INTO replenishment_action_events (signal_key,action_name,reason,actor) VALUES (:key,:action,:reason,:actor)');$save->execute([':key'=>$signalKey,':action'=>$name,':reason'=>$reason,':actor'=>$actor]);replenishmentJson(200,array_merge(['success'=>true,'message'=>'Human review evidence recorded. No reminder, cart or order was created.'],readReplenishmentState($pdo)));}replenishmentJson(400,['success'=>false,'message'=>'Unknown action.']);
}catch(Throwable $error){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();error_log('Replenishment engine error: '.$error->getMessage());replenishmentJson(500,['success'=>false,'message'=>'Replenishment evidence could not be loaded.']);}
