"use client";

import { useEffect, useMemo, useState } from "react";
import { loadCustomerGrowth, type CustomerGrowthQueueItem, type GrowthQueueReason } from "./customer-growth-client";

type GrowthState = Awaited<ReturnType<typeof loadCustomerGrowth>>;
const emptyState: GrowthState = { customers: [], queue: [], summary: { totalCustomers: 0, repeatCustomers: 0, deliveredCustomers: 0, returnRecovery: 0, activeCustomers: 0 } };

function money(amount:number){ return `৳${Number(amount||0).toLocaleString("en-BD",{maximumFractionDigits:0})}`; }
function dateText(value:string|null){ if(!value)return "Not available"; const d=new Date(value); return Number.isNaN(d.getTime())?"Not available":new Intl.DateTimeFormat("en-BD",{dateStyle:"medium"}).format(d); }
function priorityTone(p:CustomerGrowthQueueItem["priority"]){ return p==="high"?"bg-rose-50 text-rose-700":p==="medium"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-600"; }
function reasonTone(r:GrowthQueueReason){ return r==="Return recovery"?"bg-rose-50 text-rose-700":r==="Repeat customer"?"bg-emerald-50 text-emerald-700":r==="Active order"?"bg-sky-50 text-sky-700":"bg-violet-50 text-violet-700"; }

export function LiveCustomerGrowthWorkspace(){
 const [state,setState]=useState<GrowthState>(emptyState); const [query,setQuery]=useState(""); const [reason,setReason]=useState<"All"|GrowthQueueReason>("All"); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
 async function refresh(signal?:AbortSignal){ setLoading(true); setError(""); try{setState(await loadCustomerGrowth(signal));}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:"Customer growth data could not be loaded.");}finally{if(!signal?.aborted)setLoading(false);} }
 useEffect(()=>{const c=new AbortController(); void refresh(c.signal); return()=>c.abort();},[]);
 const filtered=useMemo(()=>{const n=query.trim().toLowerCase(); return state.queue.filter(item=>{if(reason!=="All"&&item.reason!==reason)return false; if(!n)return true; const c=item.customer; return `${c.name} ${c.phone} ${c.email||""} ${c.city||""} ${item.reason}`.toLowerCase().includes(n);});},[query,reason,state.queue]);
 async function copyPhone(phone:string){try{await navigator.clipboard.writeText(phone);setNotice("Phone number copied.");}catch{setNotice("Phone number could not be copied.");}window.setTimeout(()=>setNotice(""),2500);}
 const cards=[["Customers",state.summary.totalCustomers,"Unique buyers from canonical Orders"],["Repeat",state.summary.repeatCustomers,"Two or more recorded orders"],["Delivered",state.summary.deliveredCustomers,"At least one delivered order"],["Return recovery",state.summary.returnRecovery,"Customer has a recorded return"],["Active orders",state.summary.activeCustomers,"At least one active order"]] as const;
 return <div className="space-y-5">
  <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[9px] font-extrabold uppercase tracking-[.18em] text-[#547874]">CRM & CX · human-controlled follow-up</p><h1 className="mt-2 text-[28px] font-bold tracking-[-.04em] text-[#17231f]">Customer Growth & Follow-up</h1><p className="mt-1.5 max-w-4xl text-[10px] font-medium leading-5 text-[#74817b]">A prioritized owner/moderator queue built from live order history. It prepares follow-up opportunities only; it does not auto-send Messenger/WhatsApp messages or change customer/order records.</p></div><button className="rounded-xl border border-[#d9e2de] bg-white px-4 py-2.5 text-[8px] font-bold text-[#405049]" onClick={()=>void refresh()} type="button">Refresh</button></header>
  {error?<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-[9px] font-semibold text-rose-700">{error}</div>:null}
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label,value,helper])=><article className="rounded-2xl border border-[#dfe6e3] bg-white p-4" key={label}><p className="text-[7px] font-bold uppercase tracking-[.1em] text-[#87928d]">{label}</p><strong className="mt-3 block text-[22px] text-[#17231f]">{value}</strong><p className="mt-2 text-[7.5px] leading-4 text-[#87928d]">{helper}</p></article>)}</section>
  <section className="overflow-hidden rounded-2xl border border-[#dfe6e3] bg-white"><div className="grid gap-3 border-b p-4 lg:grid-cols-[1fr_190px]"><input className="h-10 rounded-xl border px-3 text-[9px] outline-none" onChange={e=>setQuery(e.target.value)} placeholder="Search customer, phone, email, city or reason" value={query}/><select className="h-10 rounded-xl border bg-white px-3 text-[8px]" onChange={e=>setReason(e.target.value as typeof reason)} value={reason}><option value="All">All opportunities</option><option value="Return recovery">Return recovery</option><option value="Repeat customer">Repeat customer</option><option value="Post-delivery">Post-delivery</option><option value="Active order">Active order</option></select></div>
  <div className="divide-y">{loading?<div className="p-10 text-center text-[9px] text-[#87928d]">Loading customer follow-up queue…</div>:filtered.length?filtered.map((item,index)=>{const c=item.customer; return <article className="p-4" key={`${c.id}-${item.reason}-${index}`}><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><b className="text-[10px] text-[#2d3d37]">{c.name}</b><span className={`rounded-full px-2 py-1 text-[6.5px] font-bold ${reasonTone(item.reason)}`}>{item.reason}</span><span className={`rounded-full px-2 py-1 text-[6.5px] font-bold uppercase ${priorityTone(item.priority)}`}>{item.priority}</span></div><p className="mt-1.5 text-[8px] text-[#7e8b85]">{c.phone} · {c.city||"No city"} · Last order {dateText(c.lastOrderAt)}</p></div><div className="flex flex-wrap gap-2">{c.phone!=="Not available"?<a className="rounded-lg bg-[#426d72] px-3 py-2 text-[8px] font-bold text-white" href={`tel:${c.phone}`}>Call</a>:null}<button className="rounded-lg border px-3 py-2 text-[8px] font-bold text-[#50635c]" onClick={()=>void copyPhone(c.phone)} type="button">Copy phone</button><a className="rounded-lg border px-3 py-2 text-[8px] font-bold text-[#50635c]" href={`/customers/profile?phone=${encodeURIComponent(c.phone)}`}>Customer profile</a></div></div><div className="mt-4 grid gap-3 md:grid-cols-4">{[["Orders",c.orderCount],["Delivered",c.deliveredCount],["Returns",c.returnedCount],["Net order value",money(c.netOrderValue)]].map(([l,v])=><div className="rounded-xl bg-[#f7f9f8] p-3" key={String(l)}><p className="text-[7px] font-bold text-[#82908a]">{l}</p><p className="mt-1 text-[11px] font-extrabold text-[#2b3b35]">{v}</p></div>)}</div><div className="mt-3 rounded-xl border border-[#e2e9e6] bg-[#fbfcfc] p-3"><p className="text-[7px] font-bold uppercase tracking-[.08em] text-[#7e8b85]">Suggested next step</p><p className="mt-1.5 text-[8px] leading-4 text-[#4c5e57]">{item.nextAction}</p></div></article>}):<div className="p-10 text-center text-[9px] text-[#87928d]">No follow-up opportunities match this view.</div>}</div></section>
  <section className="rounded-xl border border-sky-200 bg-sky-50 p-4 text-[8px] leading-4 text-sky-900"><b>Safety boundary:</b> this workspace is read-only and human-controlled. It does not auto-send Messenger/WhatsApp messages, create orders, issue refunds, or change customer/order status.</section>
  {notice?<div className="fixed bottom-6 right-6 z-50 rounded-xl bg-[#335e63] px-4 py-3 text-[9px] font-bold text-white shadow-xl">{notice}</div>:null}
 </div>;
}
