"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AccessAssignment, AccessRole, RolesPermissionsState, changeAssignmentStatus, changeRoleStatus, createRoleAssignment, createRoleDraft, loadRolesPermissions, updateRolePermissions } from "./roles-permissions-client";

type Tab = "Roles" | "Permission matrix" | "Assignments" | "Versions" | "Activity" | "Safety";
const field = "mt-1.5 h-10 w-full rounded-xl border border-[#dce4e0] bg-white px-3 text-[9px] text-[#405049] outline-none focus:border-[#9eb7b4]";
const area = "mt-1.5 min-h-24 w-full resize-none rounded-xl border border-[#dce4e0] bg-white p-3 text-[9px] text-[#405049] outline-none focus:border-[#9eb7b4]";
const title = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const dateTime = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Never";

function Icon({ name, size = 15 }: { name: string; size?: number }) {
  const paths: Record<string, React.ReactNode> = {
    alert: <><path d="M10.3 3.6 2.8 17a2 2 0 0 0 1.7 3h15a2 2 0 0 0 1.7-3L13.7 3.6a2 2 0 0 0-3.4 0Z"/><path d="M12 9v4M12 17h.01"/></>,
    check: <path d="m5 12 4 4L19 6"/>, close: <><path d="m6 6 12 12M18 6 6 18"/></>,
    plus: <><path d="M12 5v14M5 12h14"/></>, refresh: <><path d="M20 11a8 8 0 1 0-2.34 5.66"/><path d="M20 4v7h-7"/></>,
    search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, shield: <><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></>,
    users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>,
    key: <><circle cx="8" cy="15" r="4"/><path d="m11 12 9-9M18 5l2 2M15 8l2 2"/></>,
  };
  return <svg aria-hidden="true" fill="none" height={size} stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" viewBox="0 0 24 24" width={size}>{paths[name] ?? paths.shield}</svg>;
}

function Tone({ value }: { value: string }) {
  const tone = ["protected", "revoked", "archived"].includes(value) ? "bg-rose-50 text-rose-700 ring-rose-200" : ["paused", "draft", "sensitive"].includes(value) ? "bg-amber-50 text-amber-700 ring-amber-200" : value === "active" ? "bg-emerald-50 text-emerald-700 ring-emerald-200" : "bg-slate-100 text-slate-600 ring-slate-200";
  return <span className={`inline-flex rounded-full px-2 py-1 text-[6.5px] font-bold ring-1 ring-inset ${tone}`}>{title(value || "unknown")}</span>;
}

function Kpi({ label, note, value, warning = false }: { label: string; note: string; value: string; warning?: boolean }) {
  return <article className="rounded-2xl border border-[#e2e8e5] bg-white p-5"><div className="flex items-start justify-between"><div><p className="text-[7px] font-bold uppercase tracking-[.12em] text-[#7c8983]">{label}</p><strong className="mt-4 block text-[21px] tracking-tight text-[#182720]">{value}</strong></div><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${warning ? "bg-amber-50 text-amber-700" : "bg-[#edf3f4] text-[#477579]"}`}><Icon name={warning ? "alert" : "key"}/></span></div><p className="mt-4 border-t border-[#edf0ee] pt-3 text-[7px] leading-4 text-[#87928d]">{note}</p></article>;
}

function Modal({ children, onClose, subtitle, titleText }: { children: React.ReactNode; onClose: () => void; subtitle: string; titleText: string }) {
  return <div className="fixed inset-0 z-[140] flex items-center justify-center bg-[#17231f]/35 p-4 backdrop-blur-sm" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><section className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-[0_30px_90px_rgba(17,35,30,.24)]"><header className="flex items-start justify-between border-b p-5"><div><p className="text-[8px] font-bold uppercase tracking-[.14em] text-[#3b646d]">{subtitle}</p><h2 className="mt-1.5 text-[18px] font-bold text-[#23322b]">{titleText}</h2></div><button className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#f2f5f3]" onClick={onClose}><Icon name="close"/></button></header>{children}</section></div>;
}

export function LiveRolesPermissionsWorkspace() {
  const [state, setState] = useState<RolesPermissionsState | null>(null);
  const [tab, setTab] = useState<Tab>("Roles");
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [selectedRoleId, setSelectedRoleId] = useState<number | null>(null);
  const [roleOpen, setRoleOpen] = useState(false);
  const [roleDraft, setRoleDraft] = useState({ name: "", description: "", reason: "" });
  const [permissionRole, setPermissionRole] = useState<AccessRole | null>(null);
  const [permissionIds, setPermissionIds] = useState<number[]>([]);
  const [permissionReason, setPermissionReason] = useState("");
  const [statusRole, setStatusRole] = useState<AccessRole | null>(null);
  const [statusDraft, setStatusDraft] = useState({ status: "paused" as "active" | "paused" | "draft" | "archived", reason: "" });
  const [assignmentOpen, setAssignmentOpen] = useState(false);
  const [assignmentDraft, setAssignmentDraft] = useState({ subject_name: "", subject_ref: "", subject_type: "staff", role_id: 0, reason: "" });
  const [statusAssignment, setStatusAssignment] = useState<AccessAssignment | null>(null);
  const [assignmentStatusDraft, setAssignmentStatusDraft] = useState({ status: "paused" as "active" | "paused" | "revoked", reason: "" });
  const [confirmed, setConfirmed] = useState(false);

  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 3800); };
  const refresh = useCallback(async () => { setLoading(true); setError(""); try { const result = await loadRolesPermissions(); setState(result); setSelectedRoleId((current) => current ?? result.roles[0]?.id ?? null); } catch (problem) { setError(problem instanceof Error ? problem.message : "Roles and permissions could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void refresh(), 0); return () => window.clearTimeout(timer); }, [refresh]);
  const runAction = async (operation: () => Promise<{ message: string; state: RolesPermissionsState }>, close?: () => void) => { setSaving(true); setError(""); try { const result = await operation(); setState(result.state); close?.(); flash(result.message); } catch (problem) { setError(problem instanceof Error ? problem.message : "The access change could not be saved."); } finally { setSaving(false); } };

  const roles = useMemo(() => (state?.roles ?? []).filter((item) => `${item.name} ${item.description} ${item.status}`.toLowerCase().includes(query.toLowerCase())), [query, state?.roles]);
  const selectedRole = state?.roles.find((item) => item.id === selectedRoleId) ?? state?.roles[0] ?? null;
  const domains = useMemo(() => Array.from(new Set((state?.permissions ?? []).map((item) => item.domainName))), [state?.permissions]);
  const openPermissions = (role: AccessRole) => { setSelectedRoleId(role.id); setPermissionRole(role); setPermissionIds(role.permissionIds); setPermissionReason(""); setConfirmed(false); };
  const savePermissions = () => permissionRole && void runAction(() => updateRolePermissions(permissionRole.id, permissionIds, permissionReason), () => setPermissionRole(null));
  const openRoleStatus = (role: AccessRole) => { setStatusRole(role); setStatusDraft({ status: role.status === "active" ? "paused" : "active", reason: "" }); setConfirmed(false); };
  const saveRoleStatus = () => statusRole && void runAction(() => changeRoleStatus(statusRole.id, statusDraft.status, statusDraft.reason), () => setStatusRole(null));
  const openAssignment = () => { setAssignmentDraft({ subject_name: "", subject_ref: "", subject_type: "staff", role_id: state?.roles.find((item) => item.status === "active")?.id ?? 0, reason: "" }); setConfirmed(false); setAssignmentOpen(true); };
  const saveAssignment = () => void runAction(() => createRoleAssignment(assignmentDraft), () => setAssignmentOpen(false));
  const openAssignmentStatus = (item: AccessAssignment) => { setStatusAssignment(item); setAssignmentStatusDraft({ status: item.status === "active" ? "paused" : "active", reason: "" }); setConfirmed(false); };
  const saveAssignmentStatus = () => statusAssignment && void runAction(() => changeAssignmentStatus(statusAssignment.id, assignmentStatusDraft.status, assignmentStatusDraft.reason), () => setStatusAssignment(null));
  const summary = state?.summary;

  return <div className="space-y-5">
    <section className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500"/><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#3b646d]">Access governance</p></div><h1 className="mt-2 text-[28px] font-bold tracking-[-.035em] text-[#17231f] sm:text-[32px]">Roles & Permissions command center</h1><p className="mt-1.5 max-w-3xl text-[12.5px] leading-5 text-[#66736d]">Define least-privilege roles, record assignments and review every access change without risking an automatic admin lockout.</p></div><div className="flex flex-wrap gap-2"><button className="flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-[9px] font-bold text-[#596962]" onClick={() => void refresh()}><Icon name="refresh"/>Refresh</button><button className="flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-[9px] font-bold text-[#3b646d]" onClick={openAssignment}><Icon name="users"/>Assign role</button><button className="flex h-10 items-center gap-2 rounded-xl bg-[#3b646d] px-4 text-[9px] font-bold text-white" onClick={() => { setRoleDraft({ name: "", description: "", reason: "" }); setConfirmed(false); setRoleOpen(true); }}><Icon name="plus"/>New role draft</button></div></section>
    {error && <div className="flex items-center justify-between rounded-2xl border border-rose-200 bg-rose-50 px-5 py-4 text-[8px] font-bold text-rose-700"><span>{error}</span><button className="underline" onClick={() => void refresh()}>Try again</button></div>}
    {notice && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-[8px] font-bold text-emerald-700">{notice}</div>}

    <section className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_auto]"><article className="flex flex-col gap-3 rounded-2xl border border-[#d9e4e1] bg-white p-4 sm:flex-row sm:items-center"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#edf3f4] text-[#3b646d]"><Icon name="shield"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-[9px] text-[#405049]">Governance registry</b><span className="rounded-full bg-emerald-50 px-2 py-1 text-[6.5px] font-bold text-emerald-700">MySQL connected</span><span className="rounded-full bg-[#f2f4f3] px-2 py-1 text-[6.5px] font-bold text-[#65736c]">{state?.engine.timezone || "Asia/Dhaka"}</span></div><p className="mt-1.5 text-[7px] text-[#87928d]">Last access change {dateTime(state?.engine.lastChangeAt ?? null)} · every write creates audit evidence</p></div></article><div className="flex items-center gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3"><Icon name="check"/><div><b className="block text-[8px] text-[#405049]">No automatic lockout</b><span className="mt-1 block text-[6.5px] text-[#718079]">Current authentication remains unchanged</span></div></div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Kpi label="Total roles" note="Version-controlled role definitions" value={String(summary?.totalRoles ?? 0)}/><Kpi label="Active roles" note="Available for assignment registry" value={String(summary?.activeRoles ?? 0)}/><Kpi label="Permissions" note="Verified capability registry" value={String(summary?.permissions ?? 0)}/><Kpi label="Assignments" note="Recorded role assignments" value={String(summary?.assignments ?? 0)}/><Kpi label="Protected roles" note="Owner access cannot be disabled here" value={String(summary?.protectedRoles ?? 0)} warning/><Kpi label="Changes · 30D" note="Audited versions and assignments" value={String(summary?.changes30d ?? 0)}/></section>

    <section className="grid gap-4 xl:grid-cols-[minmax(0,1.25fr)_minmax(340px,.75fr)]"><article className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-[8px] font-bold uppercase tracking-[.12em] text-[#84908a]">Privilege coverage</p><h2 className="mt-1 text-[14px] font-bold text-[#33423b]">Permissions by domain</h2></div><span className="rounded-full bg-[#edf3f4] px-2 py-1 text-[7px] font-bold text-[#3b646d]">Registry only</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{domains.map((domain) => { const items = state?.permissions.filter((item) => item.domainName === domain) ?? []; return <div className="rounded-xl border p-3" key={domain}><div className="flex items-center justify-between"><b className="text-[8px] text-[#405049]">{domain}</b><span className="text-[7px] font-bold text-[#3b646d]">{items.length}</span></div><p className="mt-2 text-[6.5px] text-[#87928d]">{items.filter((item) => item.isSensitive).length} sensitive permission(s)</p></div>; })}</div></article><article className="rounded-2xl border border-[#d6e2df] bg-[#edf3f4] p-5"><p className="text-[8px] font-bold uppercase tracking-[.12em] text-[#5e7875]">Verified boundaries</p><h2 className="mt-1 text-[14px] font-bold text-[#304d4d]">Access source readiness</h2><div className="mt-4 space-y-2">{[["Admin authentication",state?.capabilities.adminAuth],["Governance registry",state?.capabilities.registry],["Audit ledger",state?.capabilities.audit],["User directory",state?.capabilities.userDirectory]].map(([name, ready]) => <div className="flex items-center justify-between rounded-xl bg-white p-3" key={String(name)}><b className="text-[8px] text-[#405049]">{String(name)}</b><Tone value={ready ? "active" : "not connected"}/></div>)}</div><p className="mt-4 text-[7px] leading-4 text-[#647b77]">The registry never invents staff identities. If no verified user directory is available, assignments stay explicit local records.</p></article></section>

    <section className="overflow-hidden rounded-2xl border border-[#e2e8e5] bg-white"><div className="flex flex-col gap-3 border-b p-4 xl:flex-row xl:items-center xl:justify-between"><div className="flex gap-1 overflow-x-auto">{(["Roles","Permission matrix","Assignments","Versions","Activity","Safety"] as Tab[]).map((item) => <button className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-[9px] font-bold ${tab === item ? "bg-[#3b646d] text-white" : "bg-[#f3f6f4] text-[#68766f]"}`} key={item} onClick={() => setTab(item)}>{item}{item === "Roles" ? ` ${state?.roles.length ?? 0}` : item === "Assignments" ? ` ${state?.assignments.length ?? 0}` : ""}</button>)}</div>{tab === "Roles" && <label className="relative min-w-72"><span className="absolute left-3 top-3 text-[#8a9590]"><Icon name="search"/></span><input className="h-10 w-full rounded-xl border pl-9 pr-3 text-[9px]" onChange={(event) => setQuery(event.target.value)} placeholder="Search role or status…" value={query}/></label>}</div>
      {loading && !state ? <div className="flex min-h-96 items-center justify-center text-[9px] font-semibold text-[#87928d]">Loading access registry…</div> : null}
      {tab === "Roles" && state && <div className="grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-3">{roles.map((role) => <article className={`rounded-xl border p-4 ${selectedRole?.id === role.id ? "border-[#8aa5a5] bg-[#f7faf9] ring-2 ring-[#edf3f4]" : "border-[#e2e8e5]"}`} key={role.id} onClick={() => setSelectedRoleId(role.id)}><div className="flex items-start justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#edf3f4] text-[#3b646d]"><Icon name={role.isProtected ? "shield" : "users"}/></span><div className="flex gap-1">{role.isProtected && <Tone value="protected"/>}<Tone value={role.status}/></div></div><b className="mt-4 block text-[10px] text-[#35443d]">{role.name}</b><p className="mt-2 min-h-8 text-[8px] leading-4 text-[#7d8983]">{role.description}</p><div className="mt-4 grid grid-cols-3 gap-2 border-t pt-3 text-center text-[7px]"><span><b className="block text-[9px] text-[#405049]">{role.permissionIds.length}</b>permissions</span><span><b className="block text-[9px] text-[#405049]">{role.assignmentCount}</b>assigned</span><span><b className="block text-[9px] text-[#405049]">v{role.version}</b>version</span></div><div className="mt-3 flex gap-2"><button className="flex-1 rounded-xl border px-3 py-2 text-[7px] font-bold" disabled={role.isProtected} onClick={(event) => { event.stopPropagation(); openPermissions(role); }}>Permissions</button><button className="flex-1 rounded-xl border px-3 py-2 text-[7px] font-bold" disabled={role.isProtected} onClick={(event) => { event.stopPropagation(); openRoleStatus(role); }}>Change state</button></div></article>)}</div>}
      {tab === "Permission matrix" && state && <div className="p-5"><div className="mb-4 flex flex-wrap gap-2">{state.roles.map((role) => <button className={`rounded-xl px-3 py-2 text-[8px] font-bold ${selectedRole?.id === role.id ? "bg-[#3b646d] text-white" : "bg-[#f3f6f4] text-[#65736c]"}`} key={role.id} onClick={() => setSelectedRoleId(role.id)}>{role.name}</button>)}</div><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[820px] text-left"><thead className="bg-[#fafbfa] text-[6.5px] uppercase tracking-[.1em] text-[#8a9590]"><tr><th className="px-4 py-3">Permission</th><th className="px-4 py-3">Domain</th><th className="px-4 py-3">Description</th><th className="px-4 py-3">Sensitivity</th><th className="px-4 py-3">Granted</th></tr></thead><tbody className="divide-y">{state.permissions.map((item) => <tr className="text-[8px] text-[#65736c]" key={item.id}><td className="px-4 py-3"><b className="text-[#405049]">{item.name}</b><span className="mt-1 block font-mono text-[6.5px]">{item.permissionKey}</span></td><td className="px-4 py-3">{item.domainName}</td><td className="px-4 py-3">{item.description}</td><td className="px-4 py-3"><Tone value={item.isSensitive ? "sensitive" : "standard"}/></td><td className="px-4 py-3"><Tone value={selectedRole?.permissionIds.includes(item.id) ? "active" : "not granted"}/></td></tr>)}</tbody></table></div>{selectedRole && <button className="mt-4 h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-40" disabled={selectedRole.isProtected} onClick={() => openPermissions(selectedRole)}>Edit {selectedRole.name}</button>}</div>}
      {tab === "Assignments" && state && <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead className="bg-[#fafbfa] text-[6.5px] uppercase tracking-[.1em] text-[#8a9590]"><tr><th className="px-5 py-3">Subject</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Created</th><th className="px-4 py-3">Control</th></tr></thead><tbody className="divide-y">{state.assignments.map((item) => <tr className="text-[8px] text-[#65736c]" key={item.id}><td className="px-5 py-4"><b className="text-[#405049]">{item.subjectName}</b><span className="mt-1 block text-[6.5px]">{item.subjectRef}</span></td><td className="px-4 py-4 font-bold">{item.roleName}</td><td className="px-4 py-4">{title(item.subjectType)}</td><td className="px-4 py-4"><Tone value={item.status}/></td><td className="px-4 py-4">{dateTime(item.createdAt)}</td><td className="px-4 py-4"><button className="rounded-xl border px-3 py-2 text-[7px] font-bold disabled:opacity-40" disabled={item.isProtected} onClick={() => openAssignmentStatus(item)}>Change state</button></td></tr>)}</tbody></table></div>}
      {tab === "Versions" && state && <div className="divide-y">{state.versions.map((item) => <div className="grid gap-2 px-5 py-4 text-[8px] sm:grid-cols-[1fr_auto_auto]" key={item.id}><div><b className="text-[#405049]">{item.roleName} · v{item.version}</b><p className="mt-1 text-[#718079]">{item.reason}</p></div><span>{item.createdBy}</span><span>{dateTime(item.createdAt)}</span></div>)}</div>}
      {tab === "Activity" && state && <div className="divide-y">{state.activity.map((item) => <div className="grid gap-2 px-5 py-4 text-[8px] sm:grid-cols-[1fr_auto]" key={item.id}><div><b className="text-[#405049]">{title(item.eventType)} · {item.subjectLabel}</b><p className="mt-1 text-[#718079]">{item.note}</p></div><span>{item.actorName} · {dateTime(item.createdAt)}</span></div>)}</div>}
      {tab === "Safety" && <div className="grid gap-3 p-5 md:grid-cols-2"><Kpi label="Registry ≠ enforcement" note="This phase records governance definitions without silently changing existing login checks." value="Explicit"/><Kpi label="Owner protection" note="The built-in Super Admin role and current authenticated-admin assignment cannot be disabled here." value="Protected"/><Kpi label="Draft by default" note="Every custom role starts disabled with no permissions." value="Required"/><Kpi label="Audit reason" note="Every permission, status and assignment change requires a written reason." value="Versioned"/></div>}
    </section>

    {roleOpen && <Modal onClose={() => setRoleOpen(false)} subtitle="Disabled by default" titleText="Create role draft"><div className="space-y-4 p-5"><label className="block text-[8px] font-bold">Role name<input className={field} value={roleDraft.name} onChange={(event) => setRoleDraft({...roleDraft,name:event.target.value})}/></label><label className="block text-[8px] font-bold">Job-purpose description<textarea className={area} value={roleDraft.description} onChange={(event) => setRoleDraft({...roleDraft,description:event.target.value})}/></label><label className="block text-[8px] font-bold">Audit reason<textarea className={area} value={roleDraft.reason} onChange={(event) => setRoleDraft({...roleDraft,reason:event.target.value})}/></label><label className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-[8px] text-amber-800"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)}/><span>I understand this creates a Draft with zero permissions and changes no login access.</span></label></div><footer className="flex justify-end gap-2 border-t p-4"><button className="h-10 rounded-xl border px-4 text-[8px] font-bold" onClick={() => setRoleOpen(false)}>Cancel</button><button className="h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-40" disabled={!confirmed || !roleDraft.name.trim() || !roleDraft.description.trim() || !roleDraft.reason.trim() || saving} onClick={() => void runAction(() => createRoleDraft(roleDraft), () => setRoleOpen(false))}>Save draft</button></footer></Modal>}
    {permissionRole && <Modal onClose={() => setPermissionRole(null)} subtitle="Versioned permission change" titleText={permissionRole.name}><div className="space-y-4 p-5"><div className="max-h-80 space-y-2 overflow-y-auto">{state?.permissions.map((item) => <label className="flex items-start gap-3 rounded-xl border p-3" key={item.id}><input className="mt-0.5" type="checkbox" checked={permissionIds.includes(item.id)} onChange={(event) => setPermissionIds((current) => event.target.checked ? [...current,item.id] : current.filter((id) => id !== item.id))}/><span className="text-[8px]"><b className="block text-[#405049]">{item.name}</b><small className="mt-1 block text-[6.5px] text-[#87928d]">{item.domainName} · {item.description}</small></span></label>)}</div><label className="block text-[8px] font-bold">Audit reason<textarea className={area} value={permissionReason} onChange={(event) => setPermissionReason(event.target.value)}/></label><label className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-[8px] text-amber-800"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)}/><span>I confirm this versioned registry change. Existing login enforcement remains unchanged.</span></label></div><footer className="flex justify-end gap-2 border-t p-4"><button className="h-10 rounded-xl border px-4 text-[8px] font-bold" onClick={() => setPermissionRole(null)}>Cancel</button><button className="h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-40" disabled={!confirmed || !permissionReason.trim() || saving} onClick={savePermissions}>Save version</button></footer></Modal>}
    {statusRole && <Modal onClose={() => setStatusRole(null)} subtitle="Versioned role state" titleText={statusRole.name}><div className="space-y-4 p-5"><label className="block text-[8px] font-bold">Next state<select className={field} value={statusDraft.status} onChange={(event) => setStatusDraft({...statusDraft,status:event.target.value as typeof statusDraft.status})}><option value="active">Active</option><option value="paused">Paused</option><option value="draft">Draft</option><option value="archived">Archived</option></select></label><label className="block text-[8px] font-bold">Audit reason<textarea className={area} value={statusDraft.reason} onChange={(event) => setStatusDraft({...statusDraft,reason:event.target.value})}/></label><label className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-[8px] text-amber-800"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)}/><span>I confirm this registry state change and understand it does not terminate any login session.</span></label></div><footer className="flex justify-end gap-2 border-t p-4"><button className="h-10 rounded-xl border px-4 text-[8px] font-bold" onClick={() => setStatusRole(null)}>Cancel</button><button className="h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-40" disabled={!confirmed || !statusDraft.reason.trim() || saving} onClick={saveRoleStatus}>Save state</button></footer></Modal>}
    {assignmentOpen && <Modal onClose={() => setAssignmentOpen(false)} subtitle="Governance registry only" titleText="Assign a role"><div className="grid gap-4 p-5 sm:grid-cols-2"><label className="text-[8px] font-bold">Subject name<input className={field} value={assignmentDraft.subject_name} onChange={(event) => setAssignmentDraft({...assignmentDraft,subject_name:event.target.value})}/></label><label className="text-[8px] font-bold">Reference / email<input className={field} value={assignmentDraft.subject_ref} onChange={(event) => setAssignmentDraft({...assignmentDraft,subject_ref:event.target.value})}/></label><label className="text-[8px] font-bold">Subject type<select className={field} value={assignmentDraft.subject_type} onChange={(event) => setAssignmentDraft({...assignmentDraft,subject_type:event.target.value})}><option value="staff">Staff</option><option value="service">Service account</option><option value="system">System identity</option></select></label><label className="text-[8px] font-bold">Role<select className={field} value={assignmentDraft.role_id} onChange={(event) => setAssignmentDraft({...assignmentDraft,role_id:Number(event.target.value)})}>{state?.roles.filter((item) => item.status === "active").map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="sm:col-span-2 text-[8px] font-bold">Audit reason<textarea className={area} value={assignmentDraft.reason} onChange={(event) => setAssignmentDraft({...assignmentDraft,reason:event.target.value})}/></label><label className="sm:col-span-2 flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-[8px] text-amber-800"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)}/><span>I verified this subject and understand this stores an access-governance assignment without changing current authentication.</span></label></div><footer className="flex justify-end gap-2 border-t p-4"><button className="h-10 rounded-xl border px-4 text-[8px] font-bold" onClick={() => setAssignmentOpen(false)}>Cancel</button><button className="h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-40" disabled={!confirmed || !assignmentDraft.subject_name.trim() || !assignmentDraft.subject_ref.trim() || !assignmentDraft.reason.trim() || saving} onClick={saveAssignment}>Record assignment</button></footer></Modal>}
    {statusAssignment && <Modal onClose={() => setStatusAssignment(null)} subtitle="Audited assignment state" titleText={statusAssignment.subjectName}><div className="space-y-4 p-5"><label className="block text-[8px] font-bold">Next state<select className={field} value={assignmentStatusDraft.status} onChange={(event) => setAssignmentStatusDraft({...assignmentStatusDraft,status:event.target.value as typeof assignmentStatusDraft.status})}><option value="active">Active</option><option value="paused">Paused</option><option value="revoked">Revoked</option></select></label><label className="block text-[8px] font-bold">Audit reason<textarea className={area} value={assignmentStatusDraft.reason} onChange={(event) => setAssignmentStatusDraft({...assignmentStatusDraft,reason:event.target.value})}/></label><label className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-[8px] text-amber-800"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)}/><span>I confirm this registry update. It does not end an active browser session.</span></label></div><footer className="flex justify-end gap-2 border-t p-4"><button className="h-10 rounded-xl border px-4 text-[8px] font-bold" onClick={() => setStatusAssignment(null)}>Cancel</button><button className="h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-40" disabled={!confirmed || !assignmentStatusDraft.reason.trim() || saving} onClick={saveAssignmentStatus}>Save state</button></footer></Modal>}
  </div>;
}
