"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { AdminShell } from "@/components/admin/AdminShell";
import { adminAuthHeaders } from "@/lib/admin-auth";
import { bnbApiUrl } from "@/lib/bnb-api";

type Summary={settled_cod:number;outstanding_cod:number;payable_obligations:number;delivered_revenue:number;direct_costs:number;operating_expenses:number;operating_profit:number;operational_cash_proxy:number;delivered_orders:number};
type Alert={severity:"critical"|"warning";title:string;count:number};
type Obligation={id:number;due_date:string;payee:string;category:string;description:string;amount:number;paid_amount:number;balance:number;status:string;reference?:string|null};
type Data={success:boolean;message?:string;period:{from:string;to:string};summary:Summary;alerts:Alert[];obligations:Obligation[]};
const ENDPOINT=bnbApiUrl("get_finance_control.php");
const money=(value:number)=>new Intl.NumberFormat("en-BD",{style:"currency",currency:"BDT",maximumFractionDigits:0}).format(value);
const field="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-3 text-sm outline-none focus:border-[#5E7F85]";

export function FinanceControlPage(){
  const[data,setData]=useState<Data|null>(null);const[message,setMessage]=useState("");const[saving,setSaving]=useState(false);
  const load=useCallback(async(signal?:AbortSignal)=>{try{const response=await fetch(ENDPOINT,{cache:"no-store",headers:adminAuthHeaders(),signal});const payload=await response.json();if(!response.ok||!payload.success)throw new Error(payload.message);setData(payload);}catch(error){if(!signal?.aborted)setMessage(error instanceof Error?error.message:"Finance control unavailable.");}},[]);
  useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort();},[load]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setSaving(true);setMessage("");try{const response=await fetch(ENDPOINT,{method:"POST",headers:adminAuthHeaders({"Content-Type":"application/json"}),body:JSON.stringify(Object.fromEntries(form.entries()))});const payload=await response.json();if(!response.ok||!payload.success)throw new Error(payload.message);setMessage(payload.message);event.currentTarget.reset();await load();}catch(error){setMessage(error instanceof Error?error.message:"Obligation could not be saved.");}finally{setSaving(false);}}
  const s=data?.summary;
  return <AdminShell><div className="space-y-6">
    <section className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#5E7F85]">Finance</p><h1 className="mt-2 text-2xl font-bold text-slate-950">Finance Control Center</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">One operational view of COD collections, receivables, obligations, profitability and finance data requiring attention.</p></section>
    {message?<div className="rounded-2xl border border-[#5E7F85]/20 bg-[#5E7F85]/5 px-5 py-4 text-sm font-semibold text-slate-700">{message}</div>:null}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["Settled COD",money(s?.settled_cod??0)],["Outstanding COD",money(s?.outstanding_cod??0)],["Open Payables",money(s?.payable_obligations??0)],["Operating Profit",money(s?.operating_profit??0)]].map(([label,value])=><div className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm" key={label}><div className="text-sm text-slate-500">{label}</div><div className="mt-2 text-2xl font-black text-slate-950">{value}</div></div>)}</section>
    <section className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><div className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold text-slate-950">This Month</h2><p className="mt-1 text-sm text-slate-500">{data?.period.from} — {data?.period.to}</p></div><a className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold text-[#5E7F85]" href="/finance/profit-loss">Open P&amp;L</a></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["Delivered revenue",s?.delivered_revenue??0],["Direct costs",s?.direct_costs??0],["Operating expenses",s?.operating_expenses??0],["Operational cash proxy",s?.operational_cash_proxy??0]].map(([label,value])=><div className="rounded-2xl bg-stone-50 p-4" key={String(label)}><div className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</div><div className="mt-2 text-xl font-black text-slate-950">{money(Number(value))}</div></div>)}</div><p className="mt-4 text-xs leading-5 text-slate-500">Cash proxy equals recorded settled COD less this month&apos;s operating expenses and ad spend. It is not a bank balance until bank/cash accounts are connected.</p></div>
    <div className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-slate-950">Attention Queue</h2><div className="mt-4 space-y-3">{data?.alerts.length?data.alerts.map((alert)=><div className={`flex items-center justify-between gap-4 rounded-2xl border p-4 ${alert.severity==="critical"?"border-rose-200 bg-rose-50":"border-amber-200 bg-amber-50"}`} key={alert.title}><div className="text-sm font-bold text-slate-800">{alert.title}</div><span className="rounded-full bg-white px-2.5 py-1 text-xs font-black text-slate-800">{alert.count}</span></div>):<div className="rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">No finance exceptions detected.</div>}</div></div></section>
    <section className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><form className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm" onSubmit={save}><h2 className="text-xl font-bold text-slate-950">Add Payable</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Due date<input className={field} name="due_date" required type="date" /></label><label className="text-sm font-semibold text-slate-700">Payee<input className={field} name="payee" placeholder="Supplier or service" required /></label><label className="text-sm font-semibold text-slate-700">Category<select className={field} name="category"><option value="supplier">Supplier</option><option value="salary">Salary</option><option value="courier">Courier</option><option value="tax">Tax</option><option value="service">Service</option><option value="other">Other</option></select></label><label className="text-sm font-semibold text-slate-700">Amount<input className={field} min="0" name="amount" required step="0.01" type="number" /></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Description<input className={field} name="description" required /></label><label className="text-sm font-semibold text-slate-700">Already paid<input className={field} defaultValue="0" min="0" name="paid_amount" step="0.01" type="number" /></label><label className="text-sm font-semibold text-slate-700">Reference<input className={field} name="reference" /></label></div><button className="mt-5 w-full rounded-xl bg-[#5E7F85] px-4 py-3 text-sm font-bold text-white disabled:bg-slate-300" disabled={saving} type="submit">{saving?"Saving...":"Save Payable"}</button></form>
    <div className="overflow-hidden rounded-[1.5rem] border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h2 className="text-xl font-bold text-slate-950">Open Obligations</h2></div>{data?.obligations.length?<div className="overflow-x-auto"><table className="min-w-[720px] w-full text-left text-sm"><thead className="bg-stone-50 text-slate-500"><tr>{["Due", "Payee", "Description", "Status", "Balance"].map(head=><th className="px-5 py-4 font-medium" key={head}>{head}</th>)}</tr></thead><tbody>{data.obligations.map(row=><tr className="border-t border-slate-100" key={row.id}><td className="px-5 py-4">{row.due_date}</td><td className="px-5 py-4 font-bold text-slate-950">{row.payee}</td><td className="px-5 py-4">{row.description}</td><td className={`px-5 py-4 capitalize ${row.status==="overdue"?"font-bold text-rose-700":""}`}>{row.status}</td><td className="px-5 py-4 font-bold">{money(row.balance)}</td></tr>)}</tbody></table></div>:<div className="p-10 text-center text-sm font-semibold text-slate-500">No open payable obligations.</div>}</div></section>
  </div></AdminShell>;
}
