"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { AdminShell } from "@/components/admin/AdminShell";
import { adminAuthHeaders } from "@/lib/admin-auth";
import { bnbApiUrl } from "@/lib/bnb-api";

type Summary = { delivered_revenue: number; cogs: number; gross_profit: number; other_direct_costs: number; contribution_profit: number; operating_expenses: number; advertising_spend: number; operating_profit: number; operating_margin: number | null; delivered_orders: number; returned_orders: number };
type Expense = { id: number; expense_date: string; category: string; description: string; amount: number; payment_method?: string | null; reference?: string | null };
type Payload = { success: boolean; message?: string; period: { from: string; to: string }; summary: Summary; expense_categories: Record<string, number>; expenses: Expense[] };
const ENDPOINT = bnbApiUrl("manage_profit_loss.php");
const today = new Date().toISOString().slice(0, 10);
const monthStart = `${today.slice(0, 7)}-01`;
const money = (value: number) => new Intl.NumberFormat("en-BD", { style: "currency", currency: "BDT", maximumFractionDigits: 0 }).format(value);
const field = "mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-3 text-sm outline-none focus:border-[#5E7F85]";

export function ProfitLossPage() {
  const [from, setFrom] = useState(monthStart); const [to, setTo] = useState(today);
  const [data, setData] = useState<Payload | null>(null); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(async (signal?: AbortSignal, start = from, end = to) => {
    try { const response = await fetch(`${ENDPOINT}?from=${encodeURIComponent(start)}&to=${encodeURIComponent(end)}`, { cache: "no-store", headers: adminAuthHeaders(), signal }); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.message); setData(payload); }
    catch (error) { if (!signal?.aborted) setMessage(error instanceof Error ? error.message : "P&L unavailable."); }
  }, [from, to]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  async function saveExpense(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const formData = new FormData(event.currentTarget); setSaving(true); setMessage("");
    try { const response = await fetch(ENDPOINT, { method: "POST", headers: adminAuthHeaders({ "Content-Type": "application/json" }), body: JSON.stringify(Object.fromEntries(formData.entries())) }); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.message); setMessage(payload.message); event.currentTarget.reset(); await load(); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Expense could not be saved."); } finally { setSaving(false); }
  }
  const s = data?.summary;
  return <AdminShell><div className="space-y-6">
    <section className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#5E7F85]">Finance</p><div className="mt-2 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><h1 className="text-2xl font-bold text-slate-950">Profit & Loss</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Operational P&L based on delivered revenue. Marketing spend is imported automatically, while salary, rent, software and other operating expenses are entered below.</p></div><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold text-slate-500">From<input className={field} max={to} onChange={(event) => setFrom(event.target.value)} type="date" value={from} /></label><label className="text-xs font-bold text-slate-500">To<input className={field} min={from} onChange={(event) => setTo(event.target.value)} type="date" value={to} /></label></div></div></section>
    {message ? <div className="rounded-2xl border border-[#5E7F85]/20 bg-[#5E7F85]/5 px-5 py-4 text-sm font-semibold text-slate-700">{message}</div> : null}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["Delivered Revenue", money(s?.delivered_revenue ?? 0)], ["Gross Profit", money(s?.gross_profit ?? 0)], ["Contribution Profit", money(s?.contribution_profit ?? 0)], ["Operating Profit", money(s?.operating_profit ?? 0)]].map(([label, value]) => <div className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm" key={label}><div className="text-sm text-slate-500">{label}</div><div className="mt-2 text-2xl font-black text-slate-950">{value}</div></div>)}</section>
    <section className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-slate-950">P&L Statement</h2><div className="mt-5 space-y-3 text-sm">{[["Delivered revenue", s?.delivered_revenue ?? 0, false], ["Product COGS", -(s?.cogs ?? 0), true], ["Gross profit", s?.gross_profit ?? 0, false], ["Other direct costs", -(s?.other_direct_costs ?? 0), true], ["Contribution profit", s?.contribution_profit ?? 0, false], ["Operating expenses", -(s?.operating_expenses ?? 0), true], ["Operating profit", s?.operating_profit ?? 0, false]].map(([label, value, muted], index) => <div className={`flex items-center justify-between gap-4 py-3 ${index >= 2 && [2,4,6].includes(index) ? "border-t border-slate-200 font-bold" : ""}`} key={String(label)}><span className={muted ? "text-slate-500" : "text-slate-900"}>{label}</span><span className={Number(value) < 0 ? "text-rose-700" : "text-slate-950"}>{money(Number(value))}</span></div>)}</div><div className="mt-5 grid grid-cols-3 gap-3 rounded-2xl bg-stone-50 p-4 text-center"><div><div className="text-xl font-black">{s?.delivered_orders ?? 0}</div><div className="text-xs text-slate-500">Delivered</div></div><div><div className="text-xl font-black text-rose-700">{s?.returned_orders ?? 0}</div><div className="text-xs text-slate-500">Returned</div></div><div><div className="text-xl font-black">{s?.operating_margin === null || s?.operating_margin === undefined ? "—" : `${s.operating_margin}%`}</div><div className="text-xs text-slate-500">Op. Margin</div></div></div></div>
    <form className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm" onSubmit={saveExpense}><h2 className="text-xl font-bold text-slate-950">Add Operating Expense</h2><p className="mt-1 text-sm text-slate-500">Do not add advertising here—it is synced from Marketing Performance to prevent double counting.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Date<input className={field} defaultValue={today} name="expense_date" required type="date" /></label><label className="text-sm font-semibold text-slate-700">Category<select className={field} name="category" required><option value="salary">Salary</option><option value="rent">Rent</option><option value="utilities">Utilities</option><option value="software">Software</option><option value="professional_fees">Professional fees</option><option value="office">Office</option><option value="other">Other</option></select></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Description<input className={field} name="description" placeholder="What was this expense for?" required /></label><label className="text-sm font-semibold text-slate-700">Amount (BDT)<input className={field} min="0" name="amount" required step="0.01" type="number" /></label><label className="text-sm font-semibold text-slate-700">Payment method<input className={field} name="payment_method" placeholder="Cash, bKash, bank" /></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Reference<input className={field} name="reference" placeholder="Invoice, transaction or receipt ID" /></label></div><button className="mt-5 w-full rounded-xl bg-[#5E7F85] px-4 py-3 text-sm font-bold text-white disabled:bg-slate-300" disabled={saving} type="submit">{saving ? "Saving..." : "Save Expense"}</button></form></section>
    <section className="overflow-hidden rounded-[1.5rem] border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h2 className="text-xl font-bold text-slate-950">Expense Ledger</h2><p className="mt-1 text-sm text-slate-500">Advertising in this period: {money(s?.advertising_spend ?? 0)}</p></div>{data?.expenses.length ? <div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left text-sm"><thead className="bg-stone-50 text-slate-500"><tr>{["Date", "Category", "Description", "Payment", "Reference", "Amount"].map((head) => <th className="px-5 py-4 font-medium" key={head}>{head}</th>)}</tr></thead><tbody>{data.expenses.map((expense) => <tr className="border-t border-slate-100" key={expense.id}><td className="px-5 py-4">{expense.expense_date}</td><td className="px-5 py-4 capitalize">{expense.category.replaceAll("_", " ")}</td><td className="px-5 py-4 font-semibold text-slate-950">{expense.description}</td><td className="px-5 py-4">{expense.payment_method || "—"}</td><td className="px-5 py-4">{expense.reference || "—"}</td><td className="px-5 py-4 font-bold">{money(expense.amount)}</td></tr>)}</tbody></table></div> : <div className="p-10 text-center text-sm font-semibold text-slate-500">No manually entered expenses in this period.</div>}</section>
  </div></AdminShell>;
}
