"use client";

import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { acknowledgeSecurityFinding, loadSecurityCenter, resolveSecurityFinding, runSecurityScan, saveSecurityControl, SecurityCenterState, SecurityControl, SecurityFinding } from "./security-center-client";

type Tab = "Findings" | "Controls" | "Scan history" | "Activity" | "Safety";
const tabs: Tab[] = ["Findings", "Controls", "Scan history", "Activity", "Safety"];
const field = "mt-1.5 h-10 w-full rounded-xl border border-[#dce4e0] bg-white px-3 text-[9px] text-[#405049] outline-none focus:border-[#9eb7b4]";
const area = "mt-1.5 min-h-24 w-full resize-none rounded-xl border border-[#dce4e0] bg-white p-3 text-[9px] text-[#405049] outline-none focus:border-[#9eb7b4]";
const dateTime = (value: string | null) => { if (!value) return "Never"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(date); };
const title = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

function Icon({ name, size = 16 }: { name: string; size?: number }) {
  const paths: Record<string, ReactNode> = {
    shield: <><path d="M12 3 4 6v6c0 5 3.5 8 8 9 4.5-1 8-4 8-9V6l-8-3Z"/><path d="m9 12 2 2 4-4"/></>,
    scan: <><path d="M4 7V4h3M17 4h3v3M20 17v3h-3M7 20H4v-3"/><path d="M8 12h8M12 8v8"/></>,
    refresh: <><path d="M20 11a8 8 0 1 0-2.34 5.66"/><path d="M20 4v7h-7"/></>,
    check: <path d="m5 12 4 4L19 6"/>,
    warning: <><path d="M10.3 3.6 2.8 17a2 2 0 0 0 1.7 3h15a2 2 0 0 0 1.7-3L13.7 3.6a2 2 0 0 0-3.4 0Z"/><path d="M12 9v4M12 17h.01"/></>,
    close: <><path d="m6 6 12 12M18 6 6 18"/></>,
    settings: <><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l-2.83 2.83a1.7 1.7 0 0 0-2.91 1.2V21h-4v-.09a1.7 1.7 0 0 0-2.91-1.2l-2.83-2.83A1.7 1.7 0 0 0 3 14v-4a1.7 1.7 0 0 0 1.26-2.88l2.83-2.83A1.7 1.7 0 0 0 10 3.09V3h4v.09a1.7 1.7 0 0 0 2.91 1.2l2.83 2.83A1.7 1.7 0 0 0 21 10v4a1.7 1.7 0 0 0-1.6 1Z"/></>,
    history: <><path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5M12 7v5l3 2"/></>,
    eye: <><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></>,
  };
  return <svg aria-hidden="true" fill="none" height={size} stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" viewBox="0 0 24 24" width={size}>{paths[name] ?? paths.shield}</svg>;
}

function Tone({ value }: { value: string }) {
  const key = value.toLowerCase();
  const tone = ["passed","ready","resolved","enabled","active"].includes(key) ? "bg-emerald-50 text-emerald-700 ring-emerald-200" : ["critical","high","open","failed"].includes(key) ? "bg-rose-50 text-rose-700 ring-rose-200" : ["medium","acknowledged","review_only"].includes(key) ? "bg-amber-50 text-amber-700 ring-amber-200" : "bg-slate-100 text-slate-600 ring-slate-200";
  return <span className={`${tone} inline-flex whitespace-nowrap rounded-full px-2 py-1 text-[7px] font-bold capitalize ring-1 ring-inset`}>{value.replaceAll("_", " ")}</span>;
}

function Kpi({ label, note, value, warning = false }: { label: string; note: string; value: string | number; warning?: boolean }) {
  return <article className="rounded-2xl border border-[#dfe6e2] bg-white p-5"><div className="flex items-start justify-between"><div><p className="text-[7px] font-bold uppercase tracking-[.12em] text-[#84908a]">{label}</p><b className="mt-4 block text-[22px] tracking-tight text-[#17231f]">{value}</b></div><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${warning ? "bg-amber-50 text-amber-700" : "bg-[#edf3f4] text-[#3b646d]"}`}><Icon name={warning ? "warning" : "shield"}/></span></div><p className="mt-4 border-t pt-3 text-[7px] leading-4 text-[#87928d]">{note}</p></article>;
}

function Modal({ children, onClose, subtitle, titleText }: { children: ReactNode; onClose: () => void; subtitle: string; titleText: string }) {
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-[#17231f]/40 p-4 backdrop-blur-sm" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><section aria-modal="true" className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl" role="dialog"><header className="flex items-start justify-between border-b p-5"><div><p className="text-[7px] font-bold uppercase tracking-[.12em] text-[#3b646d]">{subtitle}</p><h2 className="mt-1 text-[17px] font-bold text-[#23322b]">{titleText}</h2></div><button aria-label="Close" className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#f2f5f3]" onClick={onClose}><Icon name="close"/></button></header>{children}</section></div>;
}

export function LiveSecurityCenterWorkspace({ onNavigate }: { onNavigate: (page: string) => void }) {
  const [state, setState] = useState<SecurityCenterState | null>(null);
  const [tab, setTab] = useState<Tab>("Findings");
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState(false);
  const [statusFilter, setStatusFilter] = useState("Active findings");
  const [severityFilter, setSeverityFilter] = useState("All severity");
  const [scanOpen, setScanOpen] = useState(false);
  const [scanReason, setScanReason] = useState("");
  const [finding, setFinding] = useState<SecurityFinding | null>(null);
  const [findingNote, setFindingNote] = useState("");
  const [resolutionEvidence, setResolutionEvidence] = useState("");
  const [resolutionConfirmed, setResolutionConfirmed] = useState(false);
  const [control, setControl] = useState<SecurityControl | null>(null);
  const [controlValue, setControlValue] = useState("");
  const [controlReason, setControlReason] = useState("");
  const [controlConfirmed, setControlConfirmed] = useState(false);

  const refresh = async () => { setError(""); try { setState(await loadSecurityCenter()); } catch (problem) { setError(problem instanceof Error ? problem.message : "Security Center is unavailable."); } };
  useEffect(() => { let active = true; void loadSecurityCenter().then((value) => { if (active) setState(value); }).catch((problem: unknown) => { if (active) setError(problem instanceof Error ? problem.message : "Security Center is unavailable."); }); return () => { active = false; }; }, []);
  const act = async (operation: () => Promise<{ message: string; state: SecurityCenterState }>, close?: () => void) => { setBusy(true); setError(""); try { const result = await operation(); setState(result.state); setNotice(result.message); close?.(); setTimeout(() => setNotice(""), 5000); return true; } catch (problem) { setError(problem instanceof Error ? problem.message : "The protected security action failed."); return false; } finally { setBusy(false); } };

  const findings = useMemo(() => (state?.findings ?? []).filter((item) => (statusFilter === "All statuses" || item.status !== "resolved") && (severityFilter === "All severity" || item.severity === severityFilter.toLowerCase())), [severityFilter, state?.findings, statusFilter]);
  const chart = [...(state?.scans ?? [])].slice(0, 12).reverse();
  const score = state?.summary.score ?? 0;

  const openControl = (item: SecurityControl) => { setControl(item); setControlValue(item.controlValue); setControlReason(""); setControlConfirmed(false); };
  const saveControl = () => control && void act(() => saveSecurityControl(control.key, controlValue, controlReason), () => setControl(null));
  const scan = () => void act(() => runSecurityScan(scanReason), () => { setScanOpen(false); setScanReason(""); });
  const acknowledge = () => finding && void act(() => acknowledgeSecurityFinding(finding.id, findingNote), () => { setFinding(null); setFindingNote(""); });
  const resolve = () => finding && void act(() => resolveSecurityFinding(finding.id, resolutionEvidence), () => { setFinding(null); setResolutionEvidence(""); setResolutionConfirmed(false); });

  return <div className="space-y-5">
    <section className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500"/><p className="text-[9px] font-bold uppercase tracking-[.16em] text-[#3b646d]">Security control plane</p></div><h1 className="mt-2 text-[28px] font-bold tracking-[-.035em] text-[#17231f] sm:text-[32px]">Security Center command center</h1><p className="mt-1.5 max-w-3xl text-[11px] leading-5 text-[#66736d]">Verify authentication, access, audit, recovery and secret-handling posture with evidence—without silently locking out admins or changing business records.</p></div><div className="flex flex-wrap gap-2"><button className="flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-[8px] font-bold text-[#596962]" disabled={busy} onClick={() => void refresh()}><Icon name="refresh"/>Refresh</button><button className="flex h-10 items-center gap-2 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-50" disabled={busy} onClick={() => setScanOpen(true)}><Icon name="scan"/>Run protected scan</button></div></section>

    {error && <div className="flex items-center justify-between rounded-xl border border-rose-200 bg-rose-50 p-4 text-[8px] font-bold text-rose-700"><span>{error}</span><button className="underline" onClick={() => void refresh()}>Try again</button></div>}
    {notice && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-[8px] font-bold text-emerald-700">{notice}</div>}

    <section className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_auto]"><article className="flex flex-col gap-3 rounded-2xl border border-[#d8e4e1] bg-[#edf3f4] p-4 sm:flex-row sm:items-center"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white text-[#3b646d]"><Icon name="shield"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-[9px] text-[#304d4d]">Evidence-first · MySQL connected</b><span className="rounded-full bg-emerald-50 px-2 py-1 text-[6.5px] font-bold text-emerald-700">Authenticated API</span><span className="rounded-full bg-white px-2 py-1 text-[6.5px] font-bold text-[#65736c]">Last scan {dateTime(state?.engine.lastScanAt ?? null)}</span></div><p className="mt-1.5 text-[7px] text-[#647b77]">Secret values are never returned; scans write findings and audit evidence only.</p></div></article><div className={`flex items-center gap-2 rounded-2xl border px-4 py-3 ${(state?.summary.urgentFindings ?? 0)>0?"border-amber-200 bg-amber-50":"border-emerald-200 bg-emerald-50"}`}><Icon name={(state?.summary.urgentFindings ?? 0)>0?"warning":"check"}/><div><b className="block text-[8px] text-[#405049]">{state?.summary.urgentFindings ?? 0} urgent finding(s)</b><span className="mt-1 block text-[6.5px] text-[#718079]">Automatic lockout disabled</span></div></div></section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Kpi label="Security score" note={state?.engine.lastScanAt ? "Latest protected scan" : "Run the first protected scan"} value={state?.engine.lastScanAt ? `${score}/100` : "Not scanned"} warning={Boolean(state?.engine.lastScanAt && score < 80)}/><Kpi label="Open findings" note={`${state?.summary.acknowledgedFindings ?? 0} acknowledged`} value={state?.summary.openFindings ?? 0} warning={Boolean(state?.summary.openFindings)}/><Kpi label="Critical / high" note="Owner review required" value={state?.summary.urgentFindings ?? 0} warning={Boolean(state?.summary.urgentFindings)}/><Kpi label="Passed checks" note={`${state?.summary.totalChecks ?? 0} current checks`} value={state?.summary.passedChecks ?? 0}/><Kpi label="Verified backups" note="Private recovery points" value={state?.summary.verifiedBackups ?? 0} warning={!state?.summary.verifiedBackups}/><Kpi label="Policy controls" note="Versioned; review-only" value={state?.summary.activeControls ?? 0}/></section>

    <section className="grid gap-4 xl:grid-cols-[minmax(0,1.2fr)_minmax(350px,.8fr)]"><article className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-[8px] font-bold uppercase tracking-[.12em] text-[#84908a]">Security posture</p><h2 className="mt-1 text-[14px] font-bold text-[#33423b]">Protected scan score</h2></div><span className="rounded-full bg-[#edf3f4] px-2 py-1 text-[7px] font-bold text-[#3b646d]">Real evidence only</span></div><div className="mt-6 flex h-44 items-end gap-3 border-b px-2">{chart.map((item) => <div className="group relative flex h-full flex-1 items-end" key={item.id}><div className={`w-full rounded-t ${item.score>=80?"bg-[#5f8585]":item.score>=60?"bg-amber-300":"bg-rose-300"}`} style={{ height: `${Math.max(5,item.score)}%` }}/><span className="absolute -top-6 left-1/2 hidden -translate-x-1/2 whitespace-nowrap rounded bg-[#233f42] px-2 py-1 text-[6px] text-white group-hover:block">{item.score}/100 · {dateTime(item.createdAt)}</span></div>)}{!chart.length && <div className="flex h-full w-full items-center justify-center text-[8px] text-[#87928d]">Run the first protected scan to create posture history.</div>}</div></article><article className="rounded-2xl border border-[#d6e2df] bg-[#edf3f4] p-5"><p className="text-[8px] font-bold uppercase tracking-[.12em] text-[#5e7875]">Evidence readiness</p><h2 className="mt-1 text-[14px] font-bold text-[#304d4d]">Protected sources</h2><div className="mt-4 space-y-2">{state?.sources.map((item) => <div className="flex items-center justify-between rounded-xl bg-white p-3" key={item.key}><b className="text-[8px] text-[#405049]">{item.label}</b><Tone value={item.ready?"ready":"not ready"}/></div>)}</div><p className="mt-4 text-[7px] leading-4 text-[#647b77]">A missing source creates an honest finding. No sample result or security score is invented.</p></article></section>

    <section className="overflow-hidden rounded-2xl border border-[#dfe6e2] bg-white"><header className="flex flex-col gap-3 border-b p-4 xl:flex-row xl:items-center xl:justify-between"><div className="flex flex-wrap gap-1">{tabs.map((item) => <button className={`h-10 rounded-xl px-4 text-[8px] font-bold ${tab===item?"bg-[#3b646d] text-white":"bg-[#f2f5f3] text-[#74817b]"}`} key={item} onClick={() => setTab(item)}>{item}{item==="Findings"?` ${state?.summary.openFindings ?? 0}`:item==="Controls"?` ${state?.controls.length ?? 0}`:""}</button>)}</div><span className="text-[7px] font-semibold text-[#87928d]">Generated {dateTime(state?.generatedAt ?? null)}</span></header>

      {tab==="Findings" && <><div className="flex flex-wrap gap-2 border-b bg-[#fafbfa] p-4"><select className="h-9 rounded-xl border bg-white px-3 text-[8px]" onChange={(event)=>setStatusFilter(event.target.value)} value={statusFilter}><option>Active findings</option><option>All statuses</option></select><select className="h-9 rounded-xl border bg-white px-3 text-[8px]" onChange={(event)=>setSeverityFilter(event.target.value)} value={severityFilter}><option>All severity</option><option>Critical</option><option>High</option><option>Medium</option><option>Low</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left"><thead className="bg-[#fafbfa] text-[6.5px] font-bold uppercase tracking-[.1em] text-[#8a9590]"><tr><th className="px-5 py-3">Finding</th><th className="px-4 py-3">Domain</th><th className="px-4 py-3">Severity</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Occurrences</th><th className="px-4 py-3">Last seen</th><th className="px-5 py-3 text-right">Control</th></tr></thead><tbody className="divide-y">{findings.map((item)=><tr className="text-[8px] text-[#596861]" key={item.id}><td className="px-5 py-4"><b className="block text-[#35443d]">{item.title}</b><span className="mt-1 block text-[6.5px] text-[#929d97]">{item.checkKey} · {item.evidence}</span></td><td className="px-4 py-4">{item.domain}</td><td className="px-4 py-4"><Tone value={item.severity}/></td><td className="px-4 py-4"><Tone value={item.status}/></td><td className="px-4 py-4 font-bold">{item.occurrenceCount}</td><td className="px-4 py-4">{dateTime(item.lastSeenAt)}</td><td className="px-5 py-4 text-right"><button className="h-8 rounded-lg border px-3 text-[7px] font-bold" onClick={()=>{setFinding(item);setFindingNote("");setResolutionEvidence("");setResolutionConfirmed(false);}}>Review</button></td></tr>)}</tbody></table>{!findings.length && <div className="flex min-h-64 flex-col items-center justify-center text-[8px] text-[#87928d]"><Icon name="check"/><b className="mt-3">No finding matches this view.</b></div>}</div></>}

      {tab==="Controls" && <div className="divide-y">{state?.controls.map((item)=><div className="grid gap-3 p-5 text-[8px] lg:grid-cols-[minmax(240px,1fr)_150px_100px_120px_auto] lg:items-center" key={item.id}><div><b className="text-[9px] text-[#35443d]">{item.label}</b><p className="mt-1 text-[7px] leading-4 text-[#87928d]">{item.description}</p></div><code className="rounded-lg bg-[#f2f5f3] px-3 py-2 text-[7px]">{item.controlValue}</code><span>v{item.version}</span><Tone value={item.enforcementMode}/><button className="h-8 rounded-lg border px-3 text-[7px] font-bold" onClick={()=>openControl(item)}>Version policy</button></div>)}</div>}

      {tab==="Scan history" && <div className="divide-y">{state?.scans.length?state.scans.map((item)=><div className="grid gap-3 p-5 text-[8px] lg:grid-cols-[110px_1fr_180px_auto] lg:items-center" key={item.id}><b className={`${item.score>=80?"text-emerald-700":item.score>=60?"text-amber-700":"text-rose-700"} text-[15px]`}>{item.score}/100</b><div><b className="text-[#35443d]">{item.resultSummary}</b><p className="mt-1 text-[7px] text-[#87928d]">Reason: {item.reason}</p></div><span>{item.passedChecks} passed · {item.failedChecks} failed · {item.warningChecks} warning</span><span>{dateTime(item.createdAt)}</span></div>):<p className="p-16 text-center text-[9px] text-[#87928d]">No protected security scan has been recorded.</p>}</div>}

      {tab==="Activity" && <div className="divide-y">{state?.events.length?state.events.map((item)=><div className="grid gap-3 p-5 text-[8px] lg:grid-cols-[190px_1fr_170px] lg:items-center" key={item.id}><div><b className="text-[#35443d]">{title(item.eventType)}</b><span className="mt-1 block text-[6.5px] text-[#87928d]">{item.subjectLabel}</span></div><p className="leading-4 text-[#65736c]">{item.note}</p><span>{item.actorName} · {dateTime(item.createdAt)}</span></div>):<p className="p-16 text-center text-[9px] text-[#87928d]">No security control event has been recorded.</p>}</div>}

      {tab==="Safety" && <div className="grid gap-3 p-5 sm:grid-cols-2"><Kpi label="Evidence-first mode" note="Scans compare bounded server and database facts, then write reviewable findings." value="Enabled"/><Kpi label="Automatic lockout" note="This page cannot silently disable an admin account or change authentication." value="Disabled"/><Kpi label="Secret exposure" note="Connector secret values are never included in the Security Center response." value="Blocked"/><Kpi label="Business mutation" note="Orders, stock, courier, finance, customers and storefront data remain untouched." value="None"/></div>}
    </section>

    <section className="flex flex-col gap-3 rounded-2xl border border-[#d8e4e1] bg-[#edf3f4] p-5 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-[10px] text-[#304d4d]">Security evidence stays connected to recovery and audit</b><p className="mt-1 text-[7px] text-[#647b77]">Review source history in Audit Logs or confirm the latest recovery point in Backup & Restore.</p></div><div className="flex gap-2"><button className="h-10 rounded-xl bg-white px-4 text-[8px] font-bold text-[#3b646d] ring-1 ring-[#cad9d5]" onClick={()=>onNavigate("Audit Logs")}>Audit Logs</button><button className="h-10 rounded-xl bg-white px-4 text-[8px] font-bold text-[#3b646d] ring-1 ring-[#cad9d5]" onClick={()=>onNavigate("Backup & Restore")}>Backup & Restore</button></div></section>

    {scanOpen && <Modal onClose={()=>setScanOpen(false)} subtitle="Read-only protected verification" titleText="Run Security Center scan"><div className="space-y-4 p-5"><p className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-[8px] leading-4 text-emerald-800">The scan checks authentication, protected owner access, audit integrity, verified recovery, integration-secret redaction and PHP error exposure. It creates evidence only.</p><label className="block text-[8px] font-bold">Scan reason<textarea className={area} onChange={(event)=>setScanReason(event.target.value)} placeholder="Example: Phase 47 acceptance verification" value={scanReason}/></label></div><footer className="flex justify-end gap-2 border-t p-4"><button className="h-10 rounded-xl border px-4 text-[8px] font-bold" onClick={()=>setScanOpen(false)}>Cancel</button><button className="h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-40" disabled={busy||scanReason.trim().length<3} onClick={scan}>Run protected scan</button></footer></Modal>}

    {finding && <Modal onClose={()=>setFinding(null)} subtitle={`${finding.domain} · ${finding.severity}`} titleText={finding.title}><div className="space-y-4 p-5"><div className="rounded-xl border bg-[#fafbfa] p-4"><b className="text-[8px] text-[#405049]">Evidence</b><p className="mt-2 text-[8px] leading-4 text-[#718079]">{finding.evidence}</p></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><b className="text-[8px] text-amber-800">Recommended review</b><p className="mt-2 text-[8px] leading-4 text-amber-800">{finding.recommendation}</p></div>{finding.status==="open" && <label className="block text-[8px] font-bold">Acknowledgement note<textarea className={area} onChange={(event)=>setFindingNote(event.target.value)} value={findingNote}/></label>}{finding.status!=="resolved" && <><label className="block text-[8px] font-bold">Resolution evidence<textarea className={area} onChange={(event)=>setResolutionEvidence(event.target.value)} value={resolutionEvidence}/></label><label className="flex gap-3 rounded-xl border p-4 text-[8px]"><input checked={resolutionConfirmed} onChange={(event)=>setResolutionConfirmed(event.target.checked)} type="checkbox"/><span>I confirm the issue was reviewed and this evidence supports resolution. A later scan may reopen it if the condition remains.</span></label></>}</div><footer className="flex justify-end gap-2 border-t p-4"><button className="h-10 rounded-xl border px-4 text-[8px] font-bold" onClick={()=>setFinding(null)}>Close</button>{finding.status==="open" && <button className="h-10 rounded-xl border px-4 text-[8px] font-bold disabled:opacity-40" disabled={busy||findingNote.trim().length<3} onClick={acknowledge}>Acknowledge</button>}{finding.status!=="resolved" && <button className="h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-40" disabled={busy||!resolutionConfirmed||resolutionEvidence.trim().length<12} onClick={resolve}>Resolve with evidence</button>}</footer></Modal>}

    {control && <Modal onClose={()=>setControl(null)} subtitle={`Versioned review-only policy · v${control.version}`} titleText={control.label}><div className="space-y-4 p-5"><p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-[8px] leading-4 text-amber-800">Saving creates a reviewed policy version only. It does not silently change login enforcement or lock out an administrator.</p><label className="block text-[8px] font-bold">Control value{control.valueType==="toggle"?<select className={field} onChange={(event)=>setControlValue(event.target.value)} value={controlValue}><option value="enabled">enabled</option><option value="disabled">disabled</option></select>:<input className={field} onChange={(event)=>setControlValue(event.target.value)} type={control.valueType==="number"?"number":"text"} value={controlValue}/>}</label><label className="block text-[8px] font-bold">Change reason<textarea className={area} onChange={(event)=>setControlReason(event.target.value)} value={controlReason}/></label><label className="flex gap-3 rounded-xl border p-4 text-[8px]"><input checked={controlConfirmed} onChange={(event)=>setControlConfirmed(event.target.checked)} type="checkbox"/><span>I reviewed the proposed policy value and understand it remains review-only until the authentication layer explicitly adopts it.</span></label></div><footer className="flex justify-end gap-2 border-t p-4"><button className="h-10 rounded-xl border px-4 text-[8px] font-bold" onClick={()=>setControl(null)}>Cancel</button><button className="h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-40" disabled={busy||!controlConfirmed||!controlValue.trim()||controlReason.trim().length<8} onClick={saveControl}>Save policy version</button></footer></Modal>}
  </div>;
}
