<?php
declare(strict_types=1);
function journeyText(mixed $value,int $limit=1000):string{$text=trim(is_scalar($value)?(string)$value:'');return function_exists('mb_substr')?mb_substr($text,0,$limit):substr($text,0,$limit);}
function journeyTable(PDO $pdo,string $table):bool{$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=:table');$q->execute([':table'=>$table]);return(int)$q->fetchColumn()>0;}
function ensureSkinJourneySchema(PDO $pdo):void{
 $pdo->exec("CREATE TABLE IF NOT EXISTS skin_journeys (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,journey_key CHAR(32) NOT NULL,customer_reference_hash CHAR(64) NOT NULL,customer_mask VARCHAR(80) NOT NULL,concern VARCHAR(190) NOT NULL,secondary_goal VARCHAR(190) NULL,routine_reference VARCHAR(190) NULL,owner VARCHAR(190) NOT NULL,participation_consent_reference VARCHAR(190) NOT NULL,participation_consent_status ENUM('active','withdrawn') NOT NULL DEFAULT 'active',media_consent_status ENUM('not_requested','active','withdrawn') NOT NULL DEFAULT 'not_requested',status ENUM('draft','active','needs_review','paused','completed','withdrawn') NOT NULL DEFAULT 'draft',baseline_score TINYINT UNSIGNED NOT NULL,started_at DATE NULL,next_review_at DATE NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_skin_journey_key(journey_key),KEY idx_skin_journey_status(status,next_review_at),KEY idx_skin_journey_customer(customer_reference_hash,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("CREATE TABLE IF NOT EXISTS skin_journey_checkins (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,journey_id BIGINT UNSIGNED NOT NULL,progress_score TINYINT UNSIGNED NOT NULL,comfort ENUM('comfortable','mostly_comfortable','uncomfortable','reaction_reported') NOT NULL,adherence_percent TINYINT UNSIGNED NOT NULL,customer_wording TEXT NOT NULL,source_channel VARCHAR(80) NOT NULL,routine_snapshot VARCHAR(500) NULL,reported_at DATETIME NOT NULL,recorded_by VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_journey_checkin(journey_id,reported_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("CREATE TABLE IF NOT EXISTS skin_journey_media_register (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,journey_id BIGINT UNSIGNED NOT NULL,media_reference VARCHAR(500) NOT NULL,purpose ENUM('private_progress') NOT NULL DEFAULT 'private_progress',retention_until DATE NOT NULL,consent_reference VARCHAR(190) NOT NULL,status ENUM('private','access_blocked','expired') NOT NULL DEFAULT 'private',created_by VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_journey_media(journey_id,status,retention_until)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("CREATE TABLE IF NOT EXISTS skin_journey_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,journey_id BIGINT UNSIGNED NOT NULL,action_name VARCHAR(60) NOT NULL,before_json LONGTEXT NULL,after_json LONGTEXT NOT NULL,reason VARCHAR(1000) NOT NULL,actor VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_journey_event(journey_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
}
function readSkinJourneyState(PDO $pdo):array{
 $rows=$pdo->query("SELECT j.*,(SELECT COUNT(*) FROM skin_journey_checkins c WHERE c.journey_id=j.id) checkin_count,(SELECT COUNT(*) FROM skin_journey_media_register m WHERE m.journey_id=j.id AND m.status='private') media_count,(SELECT c.progress_score FROM skin_journey_checkins c WHERE c.journey_id=j.id ORDER BY c.reported_at DESC,c.id DESC LIMIT 1) current_score,(SELECT c.comfort FROM skin_journey_checkins c WHERE c.journey_id=j.id ORDER BY c.reported_at DESC,c.id DESC LIMIT 1) current_comfort,(SELECT c.adherence_percent FROM skin_journey_checkins c WHERE c.journey_id=j.id ORDER BY c.reported_at DESC,c.id DESC LIMIT 1) current_adherence,(SELECT c.customer_wording FROM skin_journey_checkins c WHERE c.journey_id=j.id ORDER BY c.reported_at DESC,c.id DESC LIMIT 1) latest_wording,(SELECT c.reported_at FROM skin_journey_checkins c WHERE c.journey_id=j.id ORDER BY c.reported_at DESC,c.id DESC LIMIT 1) last_checkin_at FROM skin_journeys j ORDER BY FIELD(j.status,'needs_review','active','draft','paused','completed','withdrawn'),j.updated_at DESC,j.id DESC LIMIT 500")->fetchAll(PDO::FETCH_ASSOC)?:[];
 $summary=['total'=>count($rows),'active'=>0,'checkin_due'=>0,'needs_review'=>0,'comfort_alerts'=>0,'completed'=>0];$today=date('Y-m-d');$journeys=[];
 foreach($rows as $r){$status=(string)$r['status'];if($status==='active')$summary['active']++;if($status==='needs_review')$summary['needs_review']++;if($status==='completed')$summary['completed']++;if(in_array($r['current_comfort'],['uncomfortable','reaction_reported'],true))$summary['comfort_alerts']++;if($r['next_review_at']&&$r['next_review_at']<=$today&&in_array($status,['active','needs_review'],true))$summary['checkin_due']++;$journeys[]=['id'=>(string)$r['id'],'journey_key'=>$r['journey_key'],'customer_reference'=>$r['customer_mask'],'concern'=>$r['concern'],'secondary_goal'=>$r['secondary_goal']?:'','routine_reference'=>$r['routine_reference']?:'Not connected','owner'=>$r['owner'],'participation_consent_status'=>$r['participation_consent_status'],'media_consent_status'=>$r['media_consent_status'],'status'=>$status,'baseline_score'=>(int)$r['baseline_score'],'current_score'=>$r['current_score']===null?(int)$r['baseline_score']:(int)$r['current_score'],'current_comfort'=>$r['current_comfort']?:'not_reported','current_adherence'=>$r['current_adherence']===null?null:(int)$r['current_adherence'],'latest_wording'=>$r['latest_wording']?:'','started_at'=>$r['started_at'],'next_review_at'=>$r['next_review_at'],'last_checkin_at'=>$r['last_checkin_at'],'checkin_count'=>(int)$r['checkin_count'],'media_count'=>(int)$r['media_count']];}
 return ['summary'=>$summary,'journeys'=>$journeys,'quality'=>['page_load'=>'read_only','customer_identity'=>'hashed','participation_media_consent'=>'separate','automatic_diagnosis'=>'disabled','automatic_routine_change'=>'disabled','automatic_publication'=>'disabled','seeded_journeys'=>0],'generated_at'=>date(DATE_ATOM)];
}
