"use client";

import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { attestSecurityAuditCheck, loadSecurityAudit, runSecurityAudit, signOffSecurityAudit } from "./security-audit-client";
import type { SecurityAuditCheck, SecurityAuditState } from "./security-audit-client";

type Tab = "Audit evidence" | "Audit history" | "Review activity" | "Safety";
const tabs: Tab[] = ["Audit evidence", "Audit history", "Review activity", "Safety"];
const field = "mt-1.5 h-10 w-full rounded-xl border border-[#dce4e0] bg-white px-3 text-[9px] text-[#405049] outline-none focus:border-[#9eb7b4]";
const area = "mt-1.5 min-h-24 w-full resize-none rounded-xl border border-[#dce4e0] bg-white p-3 text-[9px] text-[#405049] outline-none focus:border-[#9eb7b4]";
const dateTime = (value: string | null) => { if (!value) return "Never"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(date); };
const human = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

function Icon({ name, size = 16 }: { name: string; size?: number }) {
  const paths: Record<string, ReactNode> = {
    audit: <><path d="M9 3h6l1 2h3v16H5V5h3l1-2Z"/><path d="M9 12l2 2 4-4M9 18h6"/></>,
    refresh: <><path d="M20 11a8 8 0 1 0-2.34 5.66"/><path d="M20 4v7h-7"/></>,
    check: <path d="m5 12 4 4L19 6"/>,
    warning: <><path d="M10.3 3.6 2.8 17a2 2 0 0 0 1.7 3h15a2 2 0 0 0 1.7-3L13.7 3.6a2 2 0 0 0-3.4 0Z"/><path d="M12 9v4M12 17h.01"/></>,
    close: <><path d="m6 6 12 12M18 6 6 18"/></>,
    hash: <><path d="M5 9h14M4 15h14M10 3 8 21M16 3l-2 18"/></>,
    sign: <><path d="M3 17c3-5 5 3 8-2 2-3 3 1 5 0 1-.5 2-1 5-1"/><path d="M4 21h16"/></>,
  };
  return <svg aria-hidden="true" fill="none" height={size} stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" viewBox="0 0 24 24" width={size}>{paths[name] ?? paths.audit}</svg>;
}

function Tone({ value }: { value: string }) {
  const key = value.toLowerCase();
  const tone = ["passed","accepted","signed_off","ready","ready_for_signoff"].includes(key) ? "bg-emerald-50 text-emerald-700 ring-emerald-200" : ["failed","critical","high"].includes(key) ? "bg-rose-50 text-rose-700 ring-rose-200" : ["review","open","needs_follow_up","unreviewed","medium"].includes(key) ? "bg-amber-50 text-amber-700 ring-amber-200" : "bg-slate-100 text-slate-600 ring-slate-200";
  return <span className={`${tone} inline-flex whitespace-nowrap rounded-full px-2 py-1 text-[7px] font-bold capitalize ring-1 ring-inset`}>{value.replaceAll("_", " ")}</span>;
}

function Kpi({ label, note, value, warning = false }: { label: string; note: string; value: string | number; warning?: boolean }) {
  return <article className="rounded-2xl border border-[#dfe6e2] bg-white p-5"><div className="flex items-start justify-between"><div><p className="text-[7px] font-bold uppercase tracking-[.12em] text-[#84908a]">{label}</p><b className="mt-4 block text-[22px] tracking-tight text-[#17231f]">{value}</b></div><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${warning ? "bg-amber-50 text-amber-700" : "bg-[#edf3f4] text-[#3b646d]"}`}><Icon name={warning ? "warning" : "audit"}/></span></div><p className="mt-4 border-t pt-3 text-[7px] leading-4 text-[#87928d]">{note}</p></article>;
}

function Modal({ children, onClose, subtitle, titleText }: { children: ReactNode; onClose: () => void; subtitle: string; titleText: string }) {
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-[#17231f]/40 p-4 backdrop-blur-sm" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><section aria-modal="true" className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl" role="dialog"><header className="flex items-start justify-between border-b p-5"><div><p className="text-[7px] font-bold uppercase tracking-[.12em] text-[#3b646d]">{subtitle}</p><h2 className="mt-1 text-[17px] font-bold text-[#23322b]">{titleText}</h2></div><button aria-label="Close" className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#f2f5f3]" onClick={onClose}><Icon name="close"/></button></header>{children}</section></div>;
}

export function LiveSecurityAuditWorkspace({ onNavigate }: { onNavigate: (page: string) => void }) {
  const [state, setState] = useState<SecurityAuditState | null>(null);
  const [tab, setTab] = useState<Tab>("Audit evidence");
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState(false);
  const [auditOpen, setAuditOpen] = useState(false);
  const [scope, setScope] = useState("Control plane");
  const [reason, setReason] = useState("");
  const [check, setCheck] = useState<SecurityAuditCheck | null>(null);
  const [decision, setDecision] = useState<"accepted" | "needs_follow_up">("accepted");
  const [reviewNote, setReviewNote] = useState("");
  const [signOpen, setSignOpen] = useState(false);
  const [conclusion, setConclusion] = useState("");
  const [confirmed, setConfirmed] = useState(false);

  const refresh = async () => { setError(""); try { setState(await loadSecurityAudit()); } catch (problem) { setError(problem instanceof Error ? problem.message : "Security Audit is unavailable."); } };
  useEffect(() => { let active = true; void loadSecurityAudit().then((value) => { if (active) setState(value); }).catch((problem: unknown) => { if (active) setError(problem instanceof Error ? problem.message : "Security Audit is unavailable."); }); return () => { active = false; }; }, []);
  const act = async (operation: () => Promise<{ message: string; state: SecurityAuditState }>, close?: () => void) => { setBusy(true); setError(""); try { const result = await operation(); setState(result.state); setNotice(result.message); close?.(); setTimeout(() => setNotice(""), 5000); } catch (problem) { setError(problem instanceof Error ? problem.message : "The protected audit action failed."); } finally { setBusy(false); } };
  const chart = useMemo(() => [...(state?.audits ?? [])].slice(0, 12).reverse(), [state?.audits]);
  const latest = state?.latestAudit ?? null;

  const startAudit = () => void act(() => runSecurityAudit(scope, reason), () => { setAuditOpen(false); setReason(""); });
  const attest = () => check && void act(() => attestSecurityAuditCheck(check.id, decision, reviewNote), () => { setCheck(null); setReviewNote(""); setDecision("accepted"); });
  const signOff = () => latest && void act(() => signOffSecurityAudit(latest.id, conclusion), () => { setSignOpen(false); setConclusion(""); setConfirmed(false); });

  return <div className="space-y-5">
    <section className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500"/><p className="text-[9px] font-bold uppercase tracking-[.16em] text-[#3b646d]">Internal assurance plane</p></div><h1 className="mt-2 text-[28px] font-bold tracking-[-.035em] text-[#17231f] sm:text-[32px]">Security Audit command center</h1><p className="mt-1.5 max-w-3xl text-[11px] leading-5 text-[#66736d]">Capture immutable evidence snapshots, review every control outcome and preserve accountable sign-off—without claiming external certification or changing live business records.</p></div><div className="flex flex-wrap gap-2"><button className="flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-[8px] font-bold text-[#596962]" disabled={busy} onClick={() => void refresh()}><Icon name="refresh"/>Refresh</button>{latest?.status==="ready_for_signoff" && <button className="flex h-10 items-center gap-2 rounded-xl border border-[#3b646d] bg-white px-4 text-[8px] font-bold text-[#3b646d]" disabled={busy} onClick={()=>setSignOpen(true)}><Icon name="sign"/>Sign off</button>}<button className="flex h-10 items-center gap-2 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-50" disabled={busy} onClick={()=>setAuditOpen(true)}><Icon name="audit"/>Start evidence audit</button></div></section>

    {error && <div className="flex items-center justify-between rounded-xl border border-rose-200 bg-rose-50 p-4 text-[8px] font-bold text-rose-700"><span>{error}</span><button className="underline" onClick={() => void refresh()}>Try again</button></div>}
    {notice && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-[8px] font-bold text-emerald-700">{notice}</div>}

    <section className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_auto]"><article className="flex flex-col gap-3 rounded-2xl border border-[#d8e4e1] bg-[#edf3f4] p-4 sm:flex-row sm:items-center"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white text-[#3b646d]"><Icon name="audit"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-[9px] text-[#304d4d]">Internal evidence review · MySQL connected</b><span className="rounded-full bg-emerald-50 px-2 py-1 text-[6.5px] font-bold text-emerald-700">Authenticated API</span><span className="rounded-full bg-white px-2 py-1 text-[6.5px] font-bold text-[#65736c]">Latest {dateTime(latest?.openedAt ?? null)}</span></div><p className="mt-1.5 text-[7px] text-[#647b77]">Each audit freezes source facts and a SHA-256 evidence hash; later source changes do not rewrite that snapshot.</p></div></article><div className={`flex items-center gap-2 rounded-2xl border px-4 py-3 ${(state?.summary.followUpChecks ?? 0)>0?"border-amber-200 bg-amber-50":"border-emerald-200 bg-emerald-50"}`}><Icon name={(state?.summary.followUpChecks ?? 0)>0?"warning":"check"}/><div><b className="block text-[8px] text-[#405049]">{state?.summary.followUpChecks ?? 0} follow-up(s)</b><span className="mt-1 block text-[6.5px] text-[#718079]">No automatic access change</span></div></div></section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Kpi label="Latest score" note={latest?"Latest evidence snapshot":"Start the first audit"} value={latest?`${latest.score}/100`:"Not audited"} warning={Boolean(latest && latest.score<80)}/><Kpi label="Total audits" note="Immutable snapshots" value={state?.summary.totalAudits ?? 0}/><Kpi label="Open review" note="Not yet signed off" value={state?.summary.openAudits ?? 0} warning={Boolean(state?.summary.openAudits)}/><Kpi label="Unreviewed" note="Latest audit checks" value={state?.summary.unreviewedChecks ?? 0} warning={Boolean(state?.summary.unreviewedChecks)}/><Kpi label="Follow-ups" note="Evidence needs action" value={state?.summary.followUpChecks ?? 0} warning={Boolean(state?.summary.followUpChecks)}/><Kpi label="Signed off" note="Internal assurance only" value={state?.summary.signedOff ?? 0}/></section>

    <section className="grid gap-4 xl:grid-cols-[minmax(0,1.2fr)_minmax(350px,.8fr)]"><article className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-[8px] font-bold uppercase tracking-[.12em] text-[#84908a]">Audit history</p><h2 className="mt-1 text-[14px] font-bold text-[#33423b]">Evidence score trend</h2></div><span className="rounded-full bg-[#edf3f4] px-2 py-1 text-[7px] font-bold text-[#3b646d]">Observed evidence only</span></div><div className="mt-6 flex h-44 items-end gap-3 border-b px-2">{chart.map((item)=><div className="group relative flex h-full flex-1 items-end" key={item.id}><div className={`w-full rounded-t ${item.score>=80?"bg-[#5f8585]":item.score>=60?"bg-amber-300":"bg-rose-300"}`} style={{height:`${Math.max(5,item.score)}%`}}/><span className="absolute -top-6 left-1/2 hidden -translate-x-1/2 whitespace-nowrap rounded bg-[#233f42] px-2 py-1 text-[6px] text-white group-hover:block">{item.score}/100 · {dateTime(item.openedAt)}</span></div>)}{!chart.length && <div className="flex h-full w-full items-center justify-center text-[8px] text-[#87928d]">Start the first evidence audit to create review history.</div>}</div>{latest && <div className="mt-4 flex flex-wrap items-center gap-2 text-[7px] text-[#718079]"><Icon name="hash"/><code>{latest.evidenceHash.slice(0,24)}…</code><Tone value={latest.status}/><span>{latest.scope}</span></div>}</article><article className="rounded-2xl border border-[#d6e2df] bg-[#edf3f4] p-5"><p className="text-[8px] font-bold uppercase tracking-[.12em] text-[#5e7875]">Evidence readiness</p><h2 className="mt-1 text-[14px] font-bold text-[#304d4d]">Protected sources</h2><div className="mt-4 space-y-2">{state?.sources.map((item)=><div className="flex items-center justify-between rounded-xl bg-white p-3" key={item.key}><b className="text-[8px] text-[#405049]">{item.label}</b><Tone value={item.ready?"ready":"not ready"}/></div>)}</div><p className="mt-4 text-[7px] leading-4 text-[#647b77]">Source readiness is reported honestly. This page never creates a sample audit or invented certification result.</p></article></section>

    <section className="overflow-hidden rounded-2xl border border-[#dfe6e2] bg-white"><header className="flex flex-col gap-3 border-b p-4 xl:flex-row xl:items-center xl:justify-between"><div className="flex flex-wrap gap-1">{tabs.map((item)=><button className={`h-10 rounded-xl px-4 text-[8px] font-bold ${tab===item?"bg-[#3b646d] text-white":"bg-[#f2f5f3] text-[#74817b]"}`} key={item} onClick={()=>setTab(item)}>{item}{item==="Audit evidence"?` ${state?.checks.length ?? 0}`:""}</button>)}</div><span className="text-[7px] font-semibold text-[#87928d]">Generated {dateTime(state?.generatedAt ?? null)}</span></header>

      {tab==="Audit evidence" && <div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-left"><thead className="bg-[#fafbfa] text-[6.5px] font-bold uppercase tracking-[.1em] text-[#8a9590]"><tr><th className="px-5 py-3">Evidence check</th><th className="px-4 py-3">Domain</th><th className="px-4 py-3">Outcome</th><th className="px-4 py-3">Severity</th><th className="px-4 py-3">Review</th><th className="px-4 py-3">Source</th><th className="px-5 py-3 text-right">Control</th></tr></thead><tbody className="divide-y">{state?.checks.map((item)=><tr className="text-[8px] text-[#596861]" key={item.id}><td className="px-5 py-4"><b className="block text-[#35443d]">{item.title}</b><span className="mt-1 block max-w-xl text-[6.5px] leading-3.5 text-[#929d97]">{item.evidence}</span></td><td className="px-4 py-4">{item.domain}</td><td className="px-4 py-4"><Tone value={item.outcome}/></td><td className="px-4 py-4"><Tone value={item.severity}/></td><td className="px-4 py-4"><Tone value={item.attestationStatus}/></td><td className="px-4 py-4"><code className="text-[6.5px]">{item.sourceRef}</code></td><td className="px-5 py-4 text-right"><button className="h-8 rounded-lg border px-3 text-[7px] font-bold disabled:opacity-40" disabled={item.attestationStatus!=="unreviewed"} onClick={()=>{setCheck(item);setReviewNote("");setDecision("accepted");}}>Review</button></td></tr>)}</tbody></table>{!state?.checks.length && <div className="flex min-h-64 flex-col items-center justify-center text-[8px] text-[#87928d]"><Icon name="audit"/><b className="mt-3">No audit evidence exists yet.</b><span className="mt-1">Start the first evidence audit.</span></div>}</div>}

      {tab==="Audit history" && <div className="divide-y">{state?.audits.length?state.audits.map((item)=><div className="grid gap-3 p-5 text-[8px] lg:grid-cols-[100px_1fr_180px_180px] lg:items-center" key={item.id}><b className={`${item.score>=80?"text-emerald-700":item.score>=60?"text-amber-700":"text-rose-700"} text-[15px]`}>{item.score}/100</b><div><b className="text-[#35443d]">{item.scope}</b><p className="mt-1 text-[7px] text-[#87928d]">{item.reason}</p><code className="mt-1 block text-[6px] text-[#8a9590]">{item.evidenceHash.slice(0,20)}…</code></div><span>{item.passedChecks} passed · {item.reviewChecks} review · {item.failedChecks} failed</span><div><Tone value={item.status}/><span className="mt-2 block">{dateTime(item.openedAt)}</span></div></div>):<p className="p-16 text-center text-[9px] text-[#87928d]">No security audit has been captured.</p>}</div>}

      {tab==="Review activity" && <div className="divide-y">{state?.events.length?state.events.map((item)=><div className="grid gap-3 p-5 text-[8px] lg:grid-cols-[190px_1fr_180px] lg:items-center" key={item.id}><div><b className="text-[#35443d]">{human(item.eventType)}</b><span className="mt-1 block text-[6.5px] text-[#87928d]">{item.subjectLabel}</span></div><p className="leading-4 text-[#65736c]">{item.note}</p><span>{item.actorName} · {dateTime(item.createdAt)}</span></div>):<p className="p-16 text-center text-[9px] text-[#87928d]">No audit review event has been recorded.</p>}</div>}

      {tab==="Safety" && <div className="grid gap-3 p-5 sm:grid-cols-2"><Kpi label="Assurance type" note="An evidence-backed internal review, not an external compliance certificate." value="Internal"/><Kpi label="External certification" note="This page never claims ISO, PCI, SOC or another third-party certification." value="None"/><Kpi label="Secret exposure" note="Connector secret values and backup contents are excluded from responses." value="Blocked"/><Kpi label="Business mutation" note="Orders, stock, courier, finance and customer records remain untouched." value="None"/></div>}
    </section>

    <section className="flex flex-col gap-3 rounded-2xl border border-[#d8e4e1] bg-[#edf3f4] p-5 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-[10px] text-[#304d4d]">Audit evidence remains connected to source controls</b><p className="mt-1 text-[7px] text-[#647b77]">Run posture scans in Security Center and inspect source events in Audit Logs.</p></div><div className="flex gap-2"><button className="h-10 rounded-xl bg-white px-4 text-[8px] font-bold text-[#3b646d] ring-1 ring-[#cad9d5]" onClick={()=>onNavigate("Security Center")}>Security Center</button><button className="h-10 rounded-xl bg-white px-4 text-[8px] font-bold text-[#3b646d] ring-1 ring-[#cad9d5]" onClick={()=>onNavigate("Audit Logs")}>Audit Logs</button></div></section>

    {auditOpen && <Modal onClose={()=>setAuditOpen(false)} subtitle="Immutable internal evidence snapshot" titleText="Start security audit"><div className="space-y-4 p-5"><p className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-[8px] leading-4 text-emerald-800">Captures current security scan, finding, access, audit-integrity, recovery, credential-boundary and runtime evidence. It does not alter those sources.</p><label className="block text-[8px] font-bold">Audit scope<select className={field} onChange={(event)=>setScope(event.target.value)} value={scope}><option>Control plane</option><option>Launch readiness</option><option>Access and recovery</option></select></label><label className="block text-[8px] font-bold">Audit reason<textarea className={area} onChange={(event)=>setReason(event.target.value)} placeholder="Example: Phase 48 acceptance evidence" value={reason}/></label></div><footer className="flex justify-end gap-2 border-t p-4"><button className="h-10 rounded-xl border px-4 text-[8px] font-bold" onClick={()=>setAuditOpen(false)}>Cancel</button><button className="h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-40" disabled={busy||reason.trim().length<8} onClick={startAudit}>Start evidence audit</button></footer></Modal>}

    {check && <Modal onClose={()=>setCheck(null)} subtitle={`${check.domain} · ${check.severity} · ${check.outcome}`} titleText={check.title}><div className="space-y-4 p-5"><div className="rounded-xl border bg-[#fafbfa] p-4"><b className="text-[8px] text-[#405049]">Captured evidence</b><p className="mt-2 text-[8px] leading-4 text-[#718079]">{check.evidence}</p><code className="mt-3 block text-[7px] text-[#87928d]">Source: {check.sourceRef}</code></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><b className="text-[8px] text-amber-800">Review guidance</b><p className="mt-2 text-[8px] leading-4 text-amber-800">{check.recommendation}</p></div><label className="block text-[8px] font-bold">Review decision<select className={field} onChange={(event)=>setDecision(event.target.value as "accepted"|"needs_follow_up")} value={decision}><option value="accepted">Accept captured evidence</option><option value="needs_follow_up">Needs follow-up</option></select></label><label className="block text-[8px] font-bold">Evidence review note<textarea className={area} onChange={(event)=>setReviewNote(event.target.value)} value={reviewNote}/></label></div><footer className="flex justify-end gap-2 border-t p-4"><button className="h-10 rounded-xl border px-4 text-[8px] font-bold" onClick={()=>setCheck(null)}>Cancel</button><button className="h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-40" disabled={busy||reviewNote.trim().length<8} onClick={attest}>Record review</button></footer></Modal>}

    {signOpen && latest && <Modal onClose={()=>setSignOpen(false)} subtitle={`Internal sign-off · Audit #${latest.id}`} titleText="Sign off evidence review"><div className="space-y-4 p-5"><p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-[8px] leading-4 text-amber-800">This confirms an internal evidence review only. It does not claim external certification and does not change any security enforcement.</p><label className="block text-[8px] font-bold">Audit conclusion<textarea className={area} onChange={(event)=>setConclusion(event.target.value)} value={conclusion}/></label><label className="flex gap-3 rounded-xl border p-4 text-[8px]"><input checked={confirmed} onChange={(event)=>setConfirmed(event.target.checked)} type="checkbox"/><span>I confirm every captured evidence check was reviewed and this conclusion is linked to the preserved evidence hash.</span></label></div><footer className="flex justify-end gap-2 border-t p-4"><button className="h-10 rounded-xl border px-4 text-[8px] font-bold" onClick={()=>setSignOpen(false)}>Cancel</button><button className="h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-40" disabled={busy||!confirmed||conclusion.trim().length<12} onClick={signOff}>Sign off audit</button></footer></Modal>}
  </div>;
}
