"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AuditEvent, AuditLogsState, createAuditInvestigation, loadAuditLogs, requestAuditExport, verifyAuditIntegrity } from "./audit-logs-client";

type Tab = "Activity" | "Sensitive" | "Investigations" | "Integrity" | "Exports" | "Safety";
const tabs: Tab[] = ["Activity", "Sensitive", "Investigations", "Integrity", "Exports", "Safety"];
const field = "mt-1.5 h-10 w-full rounded-xl border border-[#dce4e0] bg-white px-3 text-[9px] text-[#405049] outline-none focus:border-[#9eb7b4]";
const area = "mt-1.5 min-h-24 w-full resize-none rounded-xl border border-[#dce4e0] bg-white p-3 text-[9px] text-[#405049] outline-none focus:border-[#9eb7b4]";
const title = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const dateTime = (value: string | null) => { if (!value) return "Never"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(date); };

function Icon({ name, size = 16 }: { name: string; size?: number }) {
  const paths: Record<string, React.ReactNode> = {
    alert: <><path d="M10.3 3.6 2.8 17a2 2 0 0 0 1.7 3h15a2 2 0 0 0 1.7-3L13.7 3.6a2 2 0 0 0-3.4 0Z"/><path d="M12 9v4M12 17h.01"/></>,
    check: <path d="m5 12 4 4L19 6"/>, close: <><path d="m6 6 12 12M18 6 6 18"/></>,
    download: <><path d="M12 3v12M7 10l5 5 5-5"/><path d="M5 21h14"/></>,
    eye: <><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></>,
    refresh: <><path d="M20 11a8 8 0 1 0-2.34 5.66"/><path d="M20 4v7h-7"/></>,
    search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,
    shield: <><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></>,
  };
  return <svg aria-hidden="true" fill="none" height={size} stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" viewBox="0 0 24 24" width={size}>{paths[name] ?? paths.shield}</svg>;
}

function Tone({ value }: { value: string }) {
  const tone = value === "passed" || value === "success" || value === "resolved" || value === "available" ? "bg-emerald-50 text-emerald-700 ring-emerald-200" : value === "critical" || value === "failed" ? "bg-rose-50 text-rose-700 ring-rose-200" : value === "high" || value === "blocked" || value === "pending" || value === "open" ? "bg-amber-50 text-amber-700 ring-amber-200" : "bg-slate-100 text-slate-600 ring-slate-200";
  return <span className={`inline-flex rounded-full px-2 py-1 text-[6.5px] font-bold ring-1 ring-inset ${tone}`}>{title(value || "unknown")}</span>;
}

function Kpi({ label, note, value, warning = false }: { label: string; note: string; value: string; warning?: boolean }) {
  return <article className="rounded-2xl border border-[#e2e8e5] bg-white p-5"><div className="flex items-start justify-between"><div><p className="text-[7px] font-bold uppercase tracking-[.12em] text-[#7c8983]">{label}</p><strong className="mt-4 block text-[21px] tracking-tight text-[#182720]">{value}</strong></div><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${warning ? "bg-amber-50 text-amber-700" : "bg-[#edf3f4] text-[#477579]"}`}><Icon name={warning ? "alert" : "shield"}/></span></div><p className="mt-4 border-t border-[#edf0ee] pt-3 text-[7px] leading-4 text-[#87928d]">{note}</p></article>;
}

function Modal({ children, onClose, subtitle, titleText }: { children: React.ReactNode; onClose: () => void; subtitle: string; titleText: string }) {
  return <div className="fixed inset-0 z-[150] flex items-center justify-center bg-[#17231f]/35 p-4 backdrop-blur-sm" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><section aria-label={titleText} aria-modal="true" className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-[0_30px_90px_rgba(17,35,30,.24)]" role="dialog"><header className="flex items-start justify-between border-b p-5"><div><p className="text-[8px] font-bold uppercase tracking-[.14em] text-[#3b646d]">{subtitle}</p><h2 className="mt-1.5 text-[18px] font-bold text-[#23322b]">{titleText}</h2></div><button aria-label="Close dialog" className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#f2f5f3]" onClick={onClose}><Icon name="close"/></button></header>{children}</section></div>;
}

function downloadRedactedCsv(events: AuditEvent[]) {
  const escape = (value: string) => `"${value.replaceAll('"', '""')}"`;
  const header = ["Event reference","Time","Domain","Action","Subject","Actor","Risk","Outcome","Source"];
  const lines = [header, ...events.map((item) => [item.eventRef,item.occurredAt ?? "",item.domain,item.action,item.subject,item.actor,item.risk,item.outcome,item.sourceLabel])].map((row) => row.map(escape).join(","));
  const blob = new Blob(["\uFEFF" + lines.join("\r\n")], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `BrandnBeauty-Audit-Logs-${new Date().toISOString().slice(0,10)}.csv`; document.body.appendChild(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url);
}

export function LiveAuditLogsWorkspace({ onNavigate }: { onNavigate: (page: string) => void }) {
  const [state, setState] = useState<AuditLogsState | null>(null);
  const [tab, setTab] = useState<Tab>("Activity");
  const [query, setQuery] = useState("");
  const [domain, setDomain] = useState("All domains");
  const [risk, setRisk] = useState("All risk");
  const [outcome, setOutcome] = useState("All outcomes");
  const [selectedRef, setSelectedRef] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [investigationOpen, setInvestigationOpen] = useState(false);
  const [investigation, setInvestigation] = useState({ title: "", severity: "high", owner_name: "Owner", note: "", confirmed: false });
  const [exportOpen, setExportOpen] = useState(false);
  const [exportReason, setExportReason] = useState("");
  const [exportConfirmed, setExportConfirmed] = useState(false);

  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 4200); };
  const refresh = useCallback(async () => { setLoading(true); setError(""); try { const result = await loadAuditLogs(); setState(result); setSelectedRef((current) => current || result.events[0]?.eventRef || ""); } catch (problem) { setError(problem instanceof Error ? problem.message : "Audit Logs could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void refresh(), 0); return () => window.clearTimeout(timer); }, [refresh]);
  const runAction = async (operation: () => Promise<{ message: string; state: AuditLogsState }>, close?: () => void) => { setSaving(true); setError(""); try { const result = await operation(); setState(result.state); close?.(); flash(result.message); return result; } catch (problem) { setError(problem instanceof Error ? problem.message : "Audit action could not be completed."); return null; } finally { setSaving(false); } };

  const domains = useMemo(() => Array.from(new Set((state?.events ?? []).map((item) => item.domain))), [state?.events]);
  const visible = useMemo(() => (state?.events ?? []).filter((item) => (tab !== "Sensitive" || ["critical","high"].includes(item.risk)) && (domain === "All domains" || item.domain === domain) && (risk === "All risk" || item.risk === risk) && (outcome === "All outcomes" || item.outcome === outcome) && `${item.eventRef} ${item.actor} ${item.action} ${item.subject} ${item.note}`.toLowerCase().includes(query.toLowerCase())), [domain, outcome, query, risk, state?.events, tab]);
  const selected = visible.find((item) => item.eventRef === selectedRef) ?? visible[0] ?? null;
  const maxDaily = Math.max(1,...(state?.daily ?? []).map((item) => item.events));
  const openInvestigation = (item: AuditEvent) => { setSelectedRef(item.eventRef); setInvestigation({ title: `${title(item.action)} review`, severity: item.risk === "critical" ? "critical" : "high", owner_name: "Owner", note: "", confirmed: false }); setInvestigationOpen(true); };
  const saveInvestigation = () => selected && void runAction(() => createAuditInvestigation({ event_ref: selected.eventRef, note: investigation.note, owner_name: investigation.owner_name, severity: investigation.severity, title: investigation.title }), () => setInvestigationOpen(false));
  const exportCsv = async () => { const snapshot = visible; const result = await runAction(() => requestAuditExport(exportReason), () => setExportOpen(false)); if (result) { downloadRedactedCsv(snapshot); setExportReason(""); setExportConfirmed(false); } };
  const summary = state?.summary;

  return <div className="space-y-5">
    <section className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500"/><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#3b646d]">Unified evidence ledger</p></div><h1 className="mt-2 text-[28px] font-bold tracking-[-.035em] text-[#17231f] sm:text-[32px]">Audit Logs command center</h1><p className="mt-1.5 max-w-3xl text-[12.5px] leading-5 text-[#66736d]">Read real evidence from installed modules, verify the current fingerprint segment and open investigations without editing source history.</p></div><div className="flex flex-wrap gap-2"><button className="flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-[9px] font-bold text-[#596962]" onClick={() => void refresh()}><Icon name="refresh"/>Refresh</button><button className="flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-[9px] font-bold text-[#3b646d] disabled:opacity-40" disabled={saving} onClick={() => void runAction(verifyAuditIntegrity)}><Icon name="check"/>Verify segment</button><button className="flex h-10 items-center gap-2 rounded-xl bg-[#3b646d] px-4 text-[9px] font-bold text-white" onClick={() => { setExportReason(""); setExportConfirmed(false); setExportOpen(true); }}><Icon name="download"/>Redacted CSV</button></div></section>
    {error && <div className="flex items-center justify-between rounded-2xl border border-rose-200 bg-rose-50 px-5 py-4 text-[8px] font-bold text-rose-700"><span>{error}</span><button className="underline" onClick={() => void refresh()}>Try again</button></div>}
    {notice && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-[8px] font-bold text-emerald-700">{notice}</div>}

    <section className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_auto]"><article className="flex flex-col gap-3 rounded-2xl border border-[#d9e4e1] bg-white p-4 sm:flex-row sm:items-center"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#edf3f4] text-[#3b646d]"><Icon name="shield"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-[9px] text-[#405049]">Read-only source aggregation</b><span className="rounded-full bg-emerald-50 px-2 py-1 text-[6.5px] font-bold text-emerald-700">MySQL connected</span><span className="rounded-full bg-[#f2f4f3] px-2 py-1 text-[6.5px] font-bold text-[#65736c]">{summary?.sourcesAvailable ?? 0}/{summary?.sourcesTotal ?? 0} sources ready</span></div><p className="mt-1.5 text-[7px] text-[#87928d]">Raw JSON, credentials, tracking payloads and public identity are excluded from this response</p></div></article><div className="flex items-center gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3"><Icon name="check"/><div><b className="block text-[8px] text-[#405049]">Source mutation disabled</b><span className="mt-1 block text-[6.5px] text-[#718079]">Controls write only investigations, export requests and verification evidence</span></div></div></section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Kpi label="Recorded events" note="Total rows across available evidence sources" value={String(summary?.eventsTotal ?? 0)}/><Kpi label="Current segment" note="Latest normalized rows loaded for review" value={String(summary?.currentSegment ?? 0)}/><Kpi label="Last 24H" note="Server-timestamped source records" value={String(summary?.events24h ?? 0)}/><Kpi label="Sensitive" note="Derived critical or high-risk records" value={String(summary?.sensitiveSegment ?? 0)} warning={(summary?.sensitiveSegment ?? 0)>0}/><Kpi label="Failed / blocked" note="Evidence requiring review in this segment" value={String(summary?.failedSegment ?? 0)} warning={(summary?.failedSegment ?? 0)>0}/><Kpi label="Integrity" note={`${summary?.openInvestigations ?? 0} open investigation(s)`} value={title(summary?.integrityStatus ?? "not_checked")} warning={summary?.integrityStatus === "failed"}/></section>

    <section className="grid gap-4 xl:grid-cols-[minmax(0,1.2fr)_minmax(350px,.8fr)]"><article className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-[8px] font-bold uppercase tracking-[.12em] text-[#84908a]">Real event volume</p><h2 className="mt-1 text-[14px] font-bold text-[#33423b]">All vs sensitive · last 14 days</h2></div><span className="rounded-full bg-[#edf3f4] px-2 py-1 text-[7px] font-bold text-[#3b646d]">Loaded segment</span></div><div className="mt-6 flex h-44 items-end gap-2 border-b px-1">{state?.daily.map((item) => <div className="group relative flex h-full flex-1 items-end gap-1" key={item.eventDate}><div className="w-1/2 rounded-t bg-[#5f8585]" style={{ height: `${Math.max(3,item.events/maxDaily*100)}%` }}/><div className="w-1/2 rounded-t bg-[#d5aaa2]" style={{ height: `${Math.max(3,item.sensitive/maxDaily*100)}%` }}/><span className="absolute -top-6 left-1/2 hidden -translate-x-1/2 whitespace-nowrap rounded bg-[#233f42] px-2 py-1 text-[6px] text-white group-hover:block">{item.eventDate} · {item.events}/{item.sensitive}</span></div>)}</div><div className="mt-3 flex gap-4 text-[7px] font-bold text-[#718079]"><span className="flex items-center gap-2"><i className="h-2 w-2 rounded bg-[#5f8585]"/>Events</span><span className="flex items-center gap-2"><i className="h-2 w-2 rounded bg-[#d5aaa2]"/>Sensitive</span></div></article><article className="rounded-2xl border border-[#d6e2df] bg-[#edf3f4] p-5"><p className="text-[8px] font-bold uppercase tracking-[.12em] text-[#5e7875]">Source readiness</p><h2 className="mt-1 text-[14px] font-bold text-[#304d4d]">Installed evidence modules</h2><div className="mt-4 max-h-52 space-y-2 overflow-y-auto">{state?.sources.map((item) => <div className="flex items-center justify-between rounded-xl bg-white p-3" key={item.table}><div><b className="block text-[8px] text-[#405049]">{item.label}</b><span className="mt-1 block text-[6.5px] text-[#87928d]">{item.eventCount} record(s) · {dateTime(item.latestAt)}</span></div><Tone value={item.available ? "available" : "not_ready"}/></div>)}</div><p className="mt-4 text-[7px] leading-4 text-[#647b77]">A missing source produces zero events. This page never creates sample history.</p></article></section>

    <section className="overflow-hidden rounded-2xl border border-[#e2e8e5] bg-white"><div className="flex flex-col gap-3 border-b p-4 xl:flex-row xl:items-center xl:justify-between"><div className="flex gap-1 overflow-x-auto">{tabs.map((item) => <button className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-[9px] font-bold ${tab===item?"bg-[#3b646d] text-white":"bg-[#f3f6f4] text-[#68766f]"}`} key={item} onClick={() => setTab(item)}>{item}{item === "Investigations" ? ` ${state?.investigations.length ?? 0}` : item === "Integrity" ? ` ${state?.integrityRuns.length ?? 0}` : ""}</button>)}</div>{["Activity","Sensitive"].includes(tab) && <div className="flex flex-wrap gap-2"><label className="relative min-w-64"><span className="absolute left-3 top-3 text-[#8a9590]"><Icon name="search"/></span><input className="h-10 w-full rounded-xl border pl-9 pr-3 text-[9px]" onChange={(event) => setQuery(event.target.value)} placeholder="Search actor, action or subject…" value={query}/></label><select className="h-10 rounded-xl border bg-white px-3 text-[8px] font-bold" onChange={(event) => setDomain(event.target.value)} value={domain}><option>All domains</option>{domains.map((item) => <option key={item}>{item}</option>)}</select><select className="h-10 rounded-xl border bg-white px-3 text-[8px] font-bold" onChange={(event) => setRisk(event.target.value)} value={risk}><option>All risk</option>{["critical","high","medium","low"].map((item) => <option key={item}>{item}</option>)}</select><select className="h-10 rounded-xl border bg-white px-3 text-[8px] font-bold" onChange={(event) => setOutcome(event.target.value)} value={outcome}><option>All outcomes</option>{["success","failed","blocked","pending"].map((item) => <option key={item}>{item}</option>)}</select></div>}</div>
      {loading && !state ? <div className="flex min-h-96 items-center justify-center text-[9px] font-semibold text-[#87928d]">Loading real audit evidence…</div> : null}
      {["Activity","Sensitive"].includes(tab) && state && <div className="grid xl:grid-cols-[minmax(0,1fr)_390px]"><div className="divide-y">{visible.length ? visible.map((item) => <button className={`grid w-full gap-3 px-5 py-4 text-left [contain-intrinsic-size:64px] [content-visibility:auto] sm:grid-cols-[minmax(210px,1.3fr)_100px_90px_120px_auto] sm:items-center ${selected?.eventRef===item.eventRef?"bg-[#f4f8f7]":"hover:bg-[#fafbfa]"}`} key={`${item.sourceTable}-${item.sourceId}`} onClick={() => setSelectedRef(item.eventRef)}><div><b className="text-[9px] text-[#405049]">{title(item.action)}</b><span className="mt-1 block text-[6.5px] text-[#87928d]">{item.eventRef} · {item.subject || "No subject"}</span></div><span className="text-[7px] font-bold text-[#65736c]">{item.domain}</span><Tone value={item.risk}/><Tone value={item.outcome}/><span className="text-[7px] text-[#718079]">{dateTime(item.occurredAt)}</span></button>) : <div className="flex min-h-64 items-center justify-center text-[8px] text-[#87928d]">No real event matches this filter.</div>}</div>{selected && <aside className="border-l bg-[#fbfcfb] p-5"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf3f4] text-[#3b646d]"><Icon name="eye"/></span><div className="flex gap-2"><Tone value={selected.risk}/><Tone value={selected.outcome}/></div></div><h2 className="mt-4 text-[15px] font-bold text-[#30413a]">{title(selected.action)}</h2><p className="mt-2 text-[8px] leading-4 text-[#718079]">{selected.note || "No explanatory note was recorded by the source module."}</p><dl className="mt-4 space-y-2 text-[7px]"><div className="rounded-xl border bg-white p-3"><dt className="font-bold text-[#87928d]">Actor and source</dt><dd className="mt-1 text-[#405049]">{selected.actor} · {selected.sourceLabel}</dd></div><div className="rounded-xl border bg-white p-3"><dt className="font-bold text-[#87928d]">Subject</dt><dd className="mt-1 break-all text-[#405049]">{selected.subject || "Not recorded"}</dd></div><div className="rounded-xl border bg-white p-3"><dt className="font-bold text-[#87928d]">Source identity</dt><dd className="mt-1 break-all font-mono text-[#405049]">{selected.sourceTable} · #{selected.sourceId}</dd></div><div className="rounded-xl border bg-white p-3"><dt className="font-bold text-[#87928d]">Fingerprint</dt><dd className="mt-1 break-all font-mono text-[#405049]">sha256:{selected.fingerprint}</dd></div></dl><button className="mt-4 h-10 w-full rounded-xl bg-[#3b646d] text-[8px] font-bold text-white" onClick={() => openInvestigation(selected)}>Open investigation</button></aside>}</div>}
      {tab === "Investigations" && state && <div className="divide-y">{state.investigations.length ? state.investigations.map((item) => <div className="grid gap-3 px-5 py-4 text-[8px] lg:grid-cols-[1.4fr_100px_120px_110px_auto] lg:items-center" key={item.id}><div><b className="text-[#405049]">{item.title}</b><span className="mt-1 block text-[6.5px] text-[#87928d]">{item.eventRef} · {item.note}</span></div><Tone value={item.severity}/><span>{item.ownerName}</span><Tone value={item.status}/><span>{dateTime(item.createdAt)}</span></div>) : <div className="flex min-h-64 items-center justify-center text-[8px] text-[#87928d]">No investigation has been opened.</div>}</div>}
      {tab === "Integrity" && state && <div className="divide-y">{state.integrityRuns.length ? state.integrityRuns.map((item) => <div className="grid gap-3 px-5 py-4 text-[8px] lg:grid-cols-[190px_90px_1fr_auto] lg:items-center" key={item.id}><div><b className="text-[#405049]">Current segment · {item.eventCount} rows</b><span className="mt-1 block text-[6.5px] text-[#87928d]">{item.newCount} new · {item.verifiedCount} verified · {item.mismatchCount} mismatch</span></div><Tone value={item.result}/><span className="break-all font-mono text-[6.5px]">sha256:{item.chainHead}</span><span>{dateTime(item.createdAt)}</span></div>) : <div className="flex min-h-64 items-center justify-center text-[8px] text-[#87928d]">Run Verify segment to create the first fingerprint evidence.</div>}</div>}
      {tab === "Exports" && state && <div className="divide-y">{state.exportRequests.length ? state.exportRequests.map((item) => <div className="grid gap-3 px-5 py-4 text-[8px] lg:grid-cols-[1fr_120px_100px_auto] lg:items-center" key={item.id}><div><b className="text-[#405049]">{item.scopeName} · {item.exportFormat}</b><span className="mt-1 block text-[6.5px] text-[#87928d]">Purpose: {item.reason}</span></div><span>{item.requestedBy}</span><Tone value={item.redacted ? "passed" : "failed"}/><span>{dateTime(item.createdAt)}</span></div>) : <div className="flex min-h-64 items-center justify-center text-[8px] text-[#87928d]">No export request has been recorded.</div>}</div>}
      {tab === "Safety" && <div className="grid gap-3 p-5 md:grid-cols-2"><Kpi label="Read-only aggregation" note="The API uses fixed allowlisted SELECT queries; no source audit table can be edited here." value="Enforced"/><Kpi label="Bounded integrity" note="Verification fingerprints the latest 2,000 normalized rows. It does not claim full-history immutability." value="Honest"/><Kpi label="Payload minimization" note="Raw JSON, credentials, tokens, tracking payloads and source configuration snapshots are excluded." value="Redacted"/><Kpi label="Controlled exports" note="Only a purpose-recorded, normalized and redacted CSV can be generated from the browser." value="Purpose-bound" warning/></div>}
    </section>

    <section className="flex flex-col gap-3 rounded-2xl border border-[#d8e4e1] bg-[#edf3f4] p-5 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-[10px] text-[#304d4d]">Need to change who can view this evidence?</b><p className="mt-1 text-[7px] text-[#647b77]">Audit history stays read-only here. Access governance remains in Roles & Permissions.</p></div><button className="h-10 rounded-xl bg-white px-4 text-[8px] font-bold text-[#3b646d] ring-1 ring-[#cad9d5]" onClick={() => onNavigate("Roles & Permissions")}>Open access controls</button></section>

    {investigationOpen && selected && <Modal onClose={() => setInvestigationOpen(false)} subtitle="Evidence-only workflow" titleText={`Investigate ${selected.eventRef}`}><div className="grid gap-4 p-5 sm:grid-cols-2"><label className="text-[8px] font-bold sm:col-span-2">Title<input className={field} value={investigation.title} onChange={(event) => setInvestigation({...investigation,title:event.target.value})}/></label><label className="text-[8px] font-bold">Severity<select className={field} value={investigation.severity} onChange={(event) => setInvestigation({...investigation,severity:event.target.value})}>{["critical","high","medium","low"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-[8px] font-bold">Owner<input className={field} value={investigation.owner_name} onChange={(event) => setInvestigation({...investigation,owner_name:event.target.value})}/></label><label className="text-[8px] font-bold sm:col-span-2">Investigation note<textarea className={area} value={investigation.note} onChange={(event) => setInvestigation({...investigation,note:event.target.value})}/></label><label className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-[8px] leading-4 text-amber-800 sm:col-span-2"><input checked={investigation.confirmed} onChange={(event) => setInvestigation({...investigation,confirmed:event.target.checked})} type="checkbox"/><span>I understand this opens an internal investigation only and does not alter the source evidence.</span></label></div><footer className="flex justify-end gap-2 border-t p-4"><button className="h-10 rounded-xl border px-4 text-[8px] font-bold" onClick={() => setInvestigationOpen(false)}>Cancel</button><button className="h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-40" disabled={saving || !investigation.confirmed || !investigation.title.trim() || !investigation.owner_name.trim() || !investigation.note.trim()} onClick={saveInvestigation}>Open investigation</button></footer></Modal>}
    {exportOpen && <Modal onClose={() => setExportOpen(false)} subtitle="Purpose-bound local export" titleText="Request redacted CSV"><div className="space-y-4 p-5"><p className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-[8px] leading-4 text-emerald-800">The CSV includes normalized event reference, time, domain, action, subject, actor, risk, outcome and source. Notes, payloads, credentials and fingerprints are excluded.</p><label className="block text-[8px] font-bold">Business purpose<textarea className={area} value={exportReason} onChange={(event) => setExportReason(event.target.value)}/></label><label className="flex gap-3 rounded-xl border p-4 text-[8px]"><input checked={exportConfirmed} onChange={(event) => setExportConfirmed(event.target.checked)} type="checkbox"/><span>I confirm this export is required for an authorized business review and will remain protected.</span></label></div><footer className="flex justify-end gap-2 border-t p-4"><button className="h-10 rounded-xl border px-4 text-[8px] font-bold" onClick={() => setExportOpen(false)}>Cancel</button><button className="h-10 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white disabled:opacity-40" disabled={saving || !exportConfirmed || !exportReason.trim() || visible.length===0} onClick={() => void exportCsv()}>Record request & download</button></footer></Modal>}
  </div>;
}
