"use client";

import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { getBnbApiRuntime } from "@/lib/bnb-api";
import { loadProductionReadiness, runProductionReadinessScan } from "./production-readiness-client";
import type { ProductionReadinessState, ReadinessOutcome } from "./production-readiness-client";

type Tab="Checks"|"Environments"|"Scan history"|"Release gates"|"Safety";
const tabs:Tab[]=["Checks","Environments","Scan history","Release gates","Safety"];
const human=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,(letter)=>letter.toUpperCase());
const dateTime=(value:string|null)=>{if(!value)return "Never";const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(date)};

function Icon({name,size=16}:{name:string;size?:number}){const paths:Record<string,ReactNode>={rocket:<><path d="M14 4c3-1 5-1 6-1 0 1 0 3-1 6l-5 5-5-5 5-5Z"/><path d="m9 10-4 1-2 3 6 1M14 15l-1 4-3 2-1-6M7 17l-2 2"/></>,refresh:<><path d="M20 11a8 8 0 1 0-2.34 5.66"/><path d="M20 4v7h-7"/></>,check:<path d="m5 12 4 4L19 6"/>,warning:<><path d="M10.3 3.6 2.8 17a2 2 0 0 0 1.7 3h15a2 2 0 0 0 1.7-3L13.7 3.6a2 2 0 0 0-3.4 0Z"/><path d="M12 9v4M12 17h.01"/></>,shield:<><path d="M12 3 5 6v5c0 5 3 8 7 10 4-2 7-5 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-4"/></>};return <svg aria-hidden="true" fill="none" height={size} stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" viewBox="0 0 24 24" width={size}>{paths[name]??paths.rocket}</svg>}
function Tone({value}:{value:string}){const key=value.toLowerCase();const style=key==="passed"||key==="ready"||key==="active"?"bg-emerald-50 text-emerald-700 ring-emerald-200":key==="failed"||key.includes("blocked")?"bg-rose-50 text-rose-700 ring-rose-200":"bg-amber-50 text-amber-700 ring-amber-200";return <span className={`${style} inline-flex whitespace-nowrap rounded-full px-2 py-1 text-[7px] font-bold ring-1 ring-inset`}>{human(value)}</span>}
function Kpi({label,note,value,tone="normal"}:{label:string;note:string;value:string|number;tone?:"normal"|"warn"|"danger"}){return <article className="rounded-2xl border border-[#dfe6e2] bg-white p-5"><div className="flex items-start justify-between"><div><p className="text-[7px] font-bold uppercase tracking-[.12em] text-[#84908a]">{label}</p><b className="mt-4 block text-[22px] tracking-tight text-[#17231f]">{value}</b></div><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${tone==="danger"?"bg-rose-50 text-rose-700":tone==="warn"?"bg-amber-50 text-amber-700":"bg-[#edf3f4] text-[#3b646d]"}`}><Icon name={tone==="normal"?"rocket":"warning"}/></span></div><p className="mt-4 border-t pt-3 text-[7px] leading-4 text-[#87928d]">{note}</p></article>}

export function LiveProductionReadinessWorkspace({onNavigate}:{onNavigate:(page:string)=>void}){
  const [state,setState]=useState<ProductionReadinessState|null>(null);const [tab,setTab]=useState<Tab>("Checks");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
  const runtime=useMemo(()=>getBnbApiRuntime(),[]);
  const refresh=async()=>{setError("");try{setState(await loadProductionReadiness())}catch(problem){setError(problem instanceof Error?problem.message:"Readiness evidence is unavailable.")}};
  useEffect(()=>{let active=true;void loadProductionReadiness().then((value)=>{if(active)setState(value)}).catch((problem:unknown)=>{if(active)setError(problem instanceof Error?problem.message:"Readiness evidence is unavailable.")});return()=>{active=false}},[]);
  const runScan=async()=>{setBusy(true);setError("");try{const result=await runProductionReadinessScan("Phase 51 protected acceptance scan");setState(result.state);setNotice(result.message);setTimeout(()=>setNotice(""),5000)}catch(problem){setError(problem instanceof Error?problem.message:"Protected readiness scan failed.")}finally{setBusy(false)}};
  const latest=state?.runs[0]??null;const checks=state?.checks??[];
  const outcomeColor=(outcome:ReadinessOutcome)=>outcome==="passed"?"text-emerald-700":outcome==="failed"?"text-rose-700":"text-amber-700";
  return <div className="space-y-5">
    <section className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500"/><p className="text-[9px] font-bold uppercase tracking-[.16em] text-[#3b646d]">Release control plane</p></div><h1 className="mt-2 text-[28px] font-bold tracking-[-.035em] text-[#17231f] sm:text-[32px]">Production Readiness command center</h1><p className="mt-1.5 max-w-3xl text-[11px] leading-5 text-[#66736d]">Prove API, HTTPS, authentication, recovery and operational readiness before launch—without deploying, changing DNS or switching production automatically.</p></div><div className="flex flex-wrap gap-2"><button className="flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-[8px] font-bold text-[#596962]" disabled={busy} onClick={()=>void refresh()}><Icon name="refresh"/>Refresh</button><button className="flex h-10 items-center gap-2 rounded-xl bg-[#3b646d] px-4 text-[8px] font-bold text-white" disabled={busy} onClick={()=>void runScan()}><Icon name="shield"/>Run protected scan</button></div></section>
    {error&&<div className="flex items-center justify-between rounded-xl border border-rose-200 bg-rose-50 p-4 text-[8px] font-bold text-rose-700"><span>{error}</span><button className="underline" onClick={()=>void refresh()}>Try again</button></div>}{notice&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-[8px] font-bold text-emerald-700">{notice}</div>}
    <section className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_auto]"><article className="flex flex-col gap-3 rounded-2xl border border-[#d8e4e1] bg-[#edf3f4] p-4 sm:flex-row sm:items-center"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white text-[#3b646d]"><Icon name="rocket"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-[9px] text-[#304d4d]">Public API configuration</b><Tone value={runtime.source}/><Tone value={runtime.secure?"passed":"review"}/></div><p className="mt-1.5 break-all font-mono text-[7px] text-[#647b77]">{runtime.baseUrl}</p></div></article><div className={`flex items-center gap-2 rounded-2xl border px-4 py-3 ${state?.summary.releaseStatus==="ready"?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50"}`}><Icon name={state?.summary.releaseStatus==="ready"?"check":"warning"}/><div><b className="block text-[8px] text-[#405049]">{human(state?.summary.releaseStatus||"not_scanned")}</b><span className="mt-1 block text-[6.5px] text-[#718079]">Human release approval required</span></div></div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Kpi label="Readiness score" note="Latest evidence snapshot" value={latest?`${state?.summary.latestScore??0}/100`:"—"}/><Kpi label="Passed" note="Verified release controls" value={state?.summary.passedChecks??0}/><Kpi label="Review" note="Evidence or configuration needed" tone="warn" value={state?.summary.reviewChecks??0}/><Kpi label="Failed" note="Hard launch blockers" tone={(state?.summary.failedChecks??0)>0?"danger":"normal"} value={state?.summary.failedChecks??0}/><Kpi label="Scan runs" note="Immutable readiness evidence" value={state?.summary.totalRuns??0}/><Kpi label="Release" note="No automatic deployment" tone={state?.summary.releaseStatus==="ready"?"normal":"warn"} value={human(state?.summary.releaseStatus||"not_scanned")}/></section>
    <section className="overflow-hidden rounded-2xl border border-[#dfe6e2] bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div className="flex flex-wrap gap-1.5">{tabs.map((item)=><button className={`rounded-xl px-4 py-3 text-[8px] font-bold ${tab===item?"bg-[#3b646d] text-white":"bg-[#f2f5f3] text-[#718079]"}`} key={item} onClick={()=>setTab(item)}>{item}{item==="Checks"&&` ${checks.length}`}</button>)}</div><span className="text-[7px] text-[#8a9690]">Generated {dateTime(state?.generatedAt??null)}</span></div>
      {tab==="Checks"&&<div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left"><thead><tr className="border-b bg-[#fafcfb] text-[6.5px] font-bold uppercase tracking-[.1em] text-[#87928d]">{["Check","Domain","Severity","Outcome","Evidence","Action"].map(item=><th className="px-5 py-3" key={item}>{item}</th>)}</tr></thead><tbody>{checks.length?checks.map((item)=><tr className="border-b last:border-0" key={item.id}><td className="px-5 py-4"><b className="block text-[8px] text-[#304039]">{item.title}</b><span className="mt-1 block font-mono text-[6.5px] text-[#8a9690]">{item.checkKey}</span></td><td className="px-5 py-4 text-[7px] text-[#65736c]">{item.domain}</td><td className="px-5 py-4 text-[7px] capitalize text-[#65736c]">{item.severity}</td><td className="px-5 py-4"><Tone value={item.outcome}/></td><td className="max-w-sm px-5 py-4 text-[7px] leading-4 text-[#65736c]">{item.evidence}</td><td className={`max-w-xs px-5 py-4 text-[7px] leading-4 ${outcomeColor(item.outcome)}`}>{item.remediation}</td></tr>):<tr><td className="px-5 py-16 text-center text-[8px] text-[#87928d]" colSpan={6}>Run the first protected readiness scan.</td></tr>}</tbody></table></div>}
      {tab==="Environments"&&<div className="grid gap-3 p-5 md:grid-cols-2">{(state?.environments??[]).map(item=><article className="rounded-2xl border p-5" key={item.id}><div className="flex items-center justify-between"><b className="text-[10px] text-[#304039]">{item.label}</b><Tone value={item.status}/></div><p className="mt-4 font-mono text-[7px] text-[#65736c]">{item.baseLabel}</p><p className="mt-3 text-[7px] text-[#8a9690]">{item.isActive?"Current evidence source":"Requires explicit human configuration"}</p></article>)}</div>}
      {tab==="Scan history"&&<div className="divide-y">{(state?.runs??[]).length?(state?.runs??[]).map(item=><article className="grid gap-3 p-5 sm:grid-cols-[1fr_auto_auto] sm:items-center" key={item.id}><div><b className="text-[9px] text-[#304039]">Scan #{item.id} · {item.reason}</b><p className="mt-1 font-mono text-[6.5px] text-[#87928d]">{item.runKey.slice(0,12)} · {dateTime(item.createdAt)}</p></div><b className="text-[18px] text-[#304039]">{item.score}/100</b><Tone value={item.status}/></article>):<div className="p-16 text-center text-[8px] text-[#87928d]">No protected scan exists yet.</div>}</div>}
      {tab==="Release gates"&&<div className="grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-3">{(state?.releaseGates??[]).map(item=><article className="flex items-center justify-between gap-3 rounded-xl border p-4" key={item.checkKey}><div><b className="block text-[8px] text-[#405049]">{item.label}</b><span className="mt-1 block text-[6.5px] text-[#87928d]">{item.required?"Required before release":"Advisory"}</span></div><Tone value={item.outcome}/></article>)}</div>}
      {tab==="Safety"&&<div className="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-5">{[["Automatic deployment",state?.safety.automaticDeployment],["Automatic DNS change",state?.safety.automaticDnsChange],["Automatic production switch",state?.safety.automaticProductionSwitch],["Secret values returned",state?.safety.secretValuesReturned],["Business data mutation",state?.safety.businessDataMutation]].map(([label,value])=><article className="rounded-xl border bg-[#fafcfb] p-4" key={String(label)}><Icon name="check"/><b className="mt-3 block text-[8px] text-[#405049]">No {String(label).toLowerCase()}</b><p className="mt-2 text-[6.5px] text-[#87928d]">{value?"Unexpected—review required":"Protected boundary verified"}</p></article>)}</div>}
    </section>
    <section className="flex flex-col gap-3 rounded-2xl border border-[#d8e4e1] bg-[#edf3f4] p-5 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-[9px] text-[#304d4d]">Release evidence remains connected to security, backup and operations</b><p className="mt-1.5 text-[7px] text-[#647b77]">A readiness scan records evidence only. It cannot deploy code, modify DNS or change customer records.</p></div><div className="flex gap-2"><button className="rounded-xl border bg-white px-4 py-3 text-[8px] font-bold text-[#3b646d]" onClick={()=>onNavigate("Security Audit")}>Security Audit</button><button className="rounded-xl border bg-white px-4 py-3 text-[8px] font-bold text-[#3b646d]" onClick={()=>onNavigate("Backup & Restore")}>Backup & Restore</button></div></section>
  </div>;
}
