"use client";

import { useCallback, useEffect, useState, type ReactNode } from "react";

import { loadLaunchVerification, runLaunchVerification, type LaunchOutcome, type LaunchVerificationState } from "@/features/launch-verification/launch-verification-client";

type Props = { onNavigate: (page: string) => void };
type IconName = "alert" | "check" | "close" | "database" | "eye" | "history" | "lock" | "refresh" | "rocket" | "search" | "shield";
const paths: Record<IconName, ReactNode> = {
  alert: <><path d="M10.3 3.6 2.8 17a2 2 0 0 0 1.7 3h15a2 2 0 0 0 1.7-3L13.7 3.6a2 2 0 0 0-3.4 0Z"/><path d="M12 9v4M12 17h.01"/></>,
  check: <path d="m5 12 4 4L19 6"/>, close: <path d="m6 6 12 12M18 6 6 18"/>,
  database: <><ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v6c0 1.7 3.6 3 8 3s8-1.3 8-3V5M4 11v6c0 1.7 3.6 3 8 3s8-1.3 8-3v-6"/></>,
  eye: <><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></>,
  history: <><path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5M12 7v5l3 2"/></>,
  lock: <><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></>,
  refresh: <><path d="M20 11a8 8 0 1 0-2.3 5.7"/><path d="M20 4v7h-7"/></>,
  rocket: <><path d="M14 4c3-2 5-1 6 0 1 1 2 3 0 6l-5 5-6-6Z"/><path d="m9 9-4 1-2 3 6 2M15 15l-1 4-3 2-2-6M6 18l-2 2"/></>,
  search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,
  shield: <><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></>,
};
function Icon({ name, size = 16 }: { name: IconName; size?: number }) { return <svg aria-hidden="true" fill="none" height={size} stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" viewBox="0 0 24 24" width={size}>{paths[name]}</svg>; }

const outcomeLabel: Record<LaunchOutcome, string> = { blocked: "Blocked", passed: "Passed", review: "Review" };
function outcomeTone(outcome: LaunchOutcome) { return outcome === "passed" ? "bg-emerald-50 text-emerald-700 ring-emerald-200" : outcome === "blocked" ? "bg-rose-50 text-rose-700 ring-rose-200" : "bg-amber-50 text-amber-700 ring-amber-200"; }
function releaseLabel(status: string) { return status === "eligible_for_approval" ? "Eligible for human approval" : status === "review_required" ? "Human review required" : status === "blocked" ? "Go-live blocked" : "Protected scan required"; }
function dateTime(value: string | null) { if (!value) return "Not available"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-BD", { dateStyle: "medium", timeStyle: "short" }).format(date); }
function Kpi({ helper, icon, label, value }: { helper: string; icon: IconName; label: string; value: string | number }) { return <article className="rounded-2xl border border-[#dfe6e2] bg-white p-4"><div className="flex items-start justify-between"><div><p className="text-[8px] font-bold uppercase tracking-[.1em] text-[#7b8781]">{label}</p><p className="mt-3 text-[24px] font-bold tracking-[-.04em] text-[#17231f]">{value}</p></div><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#edf3f4] text-[#416e72]"><Icon name={icon} size={15}/></span></div><p className="mt-3 border-t border-[#edf1ef] pt-2.5 text-[7px] leading-4 text-[#849089]">{helper}</p></article>; }

export function LiveLaunchVerificationWorkspace({ onNavigate }: Props) {
  const [state, setState] = useState<LaunchVerificationState | null>(null);
  const [selectedKey, setSelectedKey] = useState("");
  const [tab, setTab] = useState<"Current gates" | "Run history" | "Evidence contract">("Current gates");
  const [modalOpen, setModalOpen] = useState(false);
  const [reason, setReason] = useState("Final launch evidence verification before human go-live review");
  const [confirmed, setConfirmed] = useState(false);
  const [loading, setLoading] = useState(true);
  const [working, setWorking] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");

  const apply = useCallback((next: LaunchVerificationState) => { setState(next); setSelectedKey((current) => next.gates.some((gate) => gate.gateKey === current) ? current : next.gates[0]?.gateKey ?? ""); }, []);
  const load = useCallback(async () => {
    setLoading(true); setError("");
    try { apply(await loadLaunchVerification()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Launch verification evidence could not be loaded."); }
    finally { setLoading(false); }
  }, [apply]);
  useEffect(() => { const task = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(task); }, [load]);

  const selected = state?.gates.find((gate) => gate.gateKey === selectedKey) ?? null;
  const completeScan = async () => {
    setWorking(true); setError("");
    try {
      const result = await runLaunchVerification(reason); apply(result.state); setModalOpen(false); setConfirmed(false); setNotice(result.message); window.setTimeout(() => setNotice(""), 4200);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Protected launch verification failed safely."); }
    finally { setWorking(false); }
  };
  const openScan = () => { setConfirmed(false); setModalOpen(true); };
  const summary = state?.summary;
  const status = summary?.releaseStatus ?? "not_scanned";

  return <div className="space-y-5">
    <section className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500"/><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#3b646d]">Live go-live evidence</p></div><h1 className="mt-2 text-[28px] font-bold tracking-[-.035em] text-[#17231f] sm:text-[32px]">Launch verification command center</h1><p className="mt-1.5 max-w-3xl text-[12.5px] leading-5 text-[#66736d]">Consolidate tracking, SEO, commerce, operations, recovery and security proof without deploying, switching DNS or approving launch automatically.</p></div><div className="flex flex-wrap gap-2"><button className="flex h-10 items-center gap-2 rounded-xl border border-[#dce4e0] bg-white px-4 text-[9px] font-bold text-[#596962]" disabled={loading || working} onClick={() => void load()}><Icon name="refresh"/>Refresh evidence</button><button className="flex h-10 items-center gap-2 rounded-xl bg-[#3b646d] px-4 text-[9px] font-bold text-white disabled:opacity-50" disabled={working} onClick={openScan}><Icon name="shield"/>Run protected verification</button></div></section>

    <section className="rounded-2xl border border-[#d3e2df] bg-[#edf4f4] p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white text-[#416f73]"><Icon name="database"/></span><div><b className="block text-[9px] text-[#35524f]">Tracking + SEO + commerce + control evidence · MySQL connected</b><p className="mt-1 text-[7px] leading-4 text-[#72827c]">Every scan is append-only evidence. It never sends tracking events or changes products, orders, stock, finance, DNS or deployment state.</p></div></div><span className="w-fit rounded-full bg-white px-3 py-2 text-[7px] font-bold text-[#496b68]">Evidence → human review → separate launch decision</span></div></section>

    {error && <div className="flex items-center justify-between rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-[9px] font-semibold text-rose-800"><span>{error}</span><button className="underline" onClick={() => void load()}>Try again</button></div>}

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi helper="Append-only evidence runs" icon="history" label="Scan runs" value={summary?.totalRuns ?? 0}/><Kpi helper="Weighted evidence posture" icon="eye" label="Readiness score" value={`${summary?.latestScore ?? 0}/100`}/><Kpi helper="Observed evidence satisfies gate" icon="check" label="Passed" value={summary?.passedChecks ?? 0}/><Kpi helper="Needs human or provider proof" icon="search" label="Review" value={summary?.reviewChecks ?? 0}/><Kpi helper="Required evidence is missing" icon="alert" label="Blocked" value={summary?.blockedChecks ?? 0}/></section>

    <section className={`rounded-2xl border p-4 sm:p-5 ${status === "blocked" ? "border-rose-200 bg-rose-50" : status === "eligible_for_approval" ? "border-emerald-200 bg-emerald-50" : "border-amber-200 bg-amber-50"}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white"><Icon name={status === "blocked" ? "alert" : status === "eligible_for_approval" ? "check" : "lock"}/></span><div><h2 className="text-[12px] font-bold text-[#263b35]">{releaseLabel(status)}</h2><p className="mt-1 text-[7px] leading-4 text-[#6e7c76]">{status === "not_scanned" ? "Run the first protected verification to capture current evidence." : `${summary?.blockedChecks ?? 0} blocked · ${summary?.reviewChecks ?? 0} review · ${summary?.passedChecks ?? 0} passed. Human approval remains separate.`}</p></div></div><button className="w-fit rounded-xl border border-white bg-white px-4 py-2.5 text-[8px] font-bold text-[#3b646d]" onClick={() => setTab("Current gates")}>Open gate evidence</button></div></section>

    <section className="grid gap-4 xl:grid-cols-[minmax(0,1.35fr)_minmax(330px,.65fr)]"><article className="min-h-[560px] overflow-hidden rounded-2xl border border-[#dfe6e2] bg-white"><header className="flex gap-1 overflow-x-auto border-b border-[#e8ecea] px-4 pt-4 sm:px-5">{(["Current gates", "Run history", "Evidence contract"] as const).map((item) => <button className={`${tab === item ? "border-[#3b646d] text-[#3b646d]" : "border-transparent text-[#87928d]"} whitespace-nowrap border-b-2 px-3 pb-3 text-[8px] font-bold`} key={item} onClick={() => setTab(item)}>{item}</button>)}</header>
      {tab === "Current gates" ? <div>{state?.gates.map((gate) => <button className={`${selectedKey === gate.gateKey ? "bg-[#f0f5f4]" : "bg-white"} grid w-full gap-3 border-b border-[#edf1ef] p-4 text-left sm:grid-cols-[minmax(0,1.2fr)_110px_110px_95px] sm:items-center sm:px-5`} key={gate.id} onClick={() => setSelectedKey(gate.gateKey)}><div><b className="block text-[9px] text-[#364740]">{gate.label}</b><span className="mt-1 block text-[7px] text-[#8a9690]">{gate.domain} · {gate.owner}</span></div><span className="text-[7px] font-semibold capitalize text-[#6c7c75]">{gate.severity}</span><span className="truncate text-[7px] font-semibold text-[#59716a]">{gate.linkedWorkspace}</span><span className={`${outcomeTone(gate.outcome)} w-fit rounded-full px-2 py-1 text-[6.5px] font-bold ring-1 ring-inset`}>{outcomeLabel[gate.outcome]}</span></button>)}{!state?.gates.length && <div className="flex min-h-[460px] flex-col items-center justify-center text-center"><Icon name="shield" size={24}/><h3 className="mt-4 text-sm font-bold text-[#34443d]">No verification run found</h3><p className="mt-1 text-[8px] text-[#87938d]">Run the first protected verification; no sample evidence is seeded.</p><button className="mt-5 rounded-xl bg-[#3b646d] px-4 py-3 text-[8px] font-bold text-white" onClick={openScan}>Run protected verification</button></div>}</div>
      : tab === "Run history" ? <div>{state?.runs.map((run) => <article className="grid gap-3 border-b border-[#edf1ef] p-4 sm:grid-cols-[70px_minmax(0,1fr)_110px_130px] sm:items-center sm:px-5" key={run.id}><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#edf3f4] text-[12px] font-bold text-[#416f73]">{run.score}</span><div><b className="block text-[9px] text-[#364740]">Verification run #{run.id}</b><p className="mt-1 text-[7px] leading-4 text-[#7f8c86]">{run.reason}</p></div><span className="text-[7px] font-bold text-[#64746d]">{run.passedChecks}/{run.totalChecks} passed</span><span className="text-[7px] text-[#87938d]">{dateTime(run.createdAt)}</span></article>)}{!state?.runs.length && <p className="p-16 text-center text-[9px] text-[#87938d]">No protected verification has been recorded.</p>}</div>
      : <div className="grid gap-3 p-5 sm:grid-cols-2">{[
        ["Tracking", "Configured identifiers, valid ledger events, value/currency and provider-side deduplication proof."], ["SEO", "Published HTTPS configuration, audit, crawlability, canonical, sitemap, robots and visible schema."],
        ["Commerce", "One traceable order-to-delivered outcome; ordered revenue is not treated as delivered truth."], ["Operations", "Inventory movement, controlled purchasing and COD reconciliation ledgers remain the sources of truth."],
        ["Recovery & security", "Verified backup, restore drill, security audit and dispositioned critical/high findings."], ["Human release", "No score can deploy, switch DNS or approve go-live. An authorized owner makes the separate decision."],
      ].map(([title, body]) => <div className="rounded-xl border border-[#e5ebe8] bg-[#fafbfa] p-4" key={title}><b className="text-[9px] text-[#3d5048]">{title}</b><p className="mt-2 text-[7px] leading-4 text-[#78867f]">{body}</p></div>)}</div>}
    </article>

    <aside className="rounded-2xl border border-[#dfe6e2] bg-white p-5">{selected ? <><div className="flex items-start justify-between gap-3"><div><p className="text-[7px] font-bold uppercase tracking-[.12em] text-[#3b646d]">Selected launch gate</p><h2 className="mt-1.5 text-[16px] font-bold text-[#2c3e37]">{selected.label}</h2><p className="mt-1 text-[7px] text-[#8a9690]">{selected.owner} owner</p></div><span className={`${outcomeTone(selected.outcome)} rounded-full px-2 py-1 text-[6.5px] font-bold ring-1 ring-inset`}>{outcomeLabel[selected.outcome]}</span></div><div className="mt-5 rounded-xl border border-[#d6e4e1] bg-[#edf4f4] p-4"><b className="text-[8px] text-[#3e5d58]">Observed evidence</b><p className="mt-2 text-[7.5px] leading-4 text-[#627770]">{selected.evidence}</p></div><div className="mt-4 rounded-xl border border-[#e4eae7] p-4"><b className="text-[8px] text-[#45564f]">Required proof</b><p className="mt-2 text-[7.5px] leading-4 text-[#75827c]">{selected.proof}</p></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-[#f6f8f7] p-3"><span className="text-[6px] uppercase tracking-[.08em] text-[#87938d]">Domain</span><b className="mt-1 block text-[8px] text-[#52655d]">{selected.domain}</b></div><div className="rounded-xl bg-[#f6f8f7] p-3"><span className="text-[6px] uppercase tracking-[.08em] text-[#87938d]">Severity</span><b className="mt-1 block text-[8px] capitalize text-[#52655d]">{selected.severity}</b></div></div><button className="mt-4 flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-[#3b646d] text-[8px] font-bold text-white" onClick={() => onNavigate(selected.linkedWorkspace)}>Open linked workspace<Icon name="rocket" size={13}/></button><div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><b className="text-[8px] text-amber-800">Human decision boundary</b><p className="mt-2 text-[7px] leading-4 text-amber-700">This evidence can support a release decision; it cannot make or execute that decision.</p></div></> : <div className="flex min-h-[500px] flex-col items-center justify-center text-center"><Icon name="shield" size={24}/><h3 className="mt-4 text-sm font-bold">Select a launch gate</h3><p className="mt-1 text-[8px] text-[#87938d]">Run a verification to inspect real evidence.</p></div>}</aside></section>

    <section className="grid gap-3 md:grid-cols-3"><div className="rounded-2xl border border-[#e1e8e5] bg-white p-4"><p className="text-[7px] font-bold uppercase tracking-[.1em] text-[#7b8882]">Source of truth</p><b className="mt-2 block text-[9px] text-[#3f5149]">Existing live module ledgers</b><p className="mt-2 text-[7px] leading-4 text-[#849089]">No invented provider success and no seeded launch result.</p></div><div className="rounded-2xl border border-[#e1e8e5] bg-white p-4"><p className="text-[7px] font-bold uppercase tracking-[.1em] text-[#7b8882]">Immutable evidence</p><b className="mt-2 block text-[9px] text-[#3f5149]">Append-only hashed snapshots</b><p className="mt-2 text-[7px] leading-4 text-[#849089]">Every run preserves its gate outcome and evidence hash.</p></div><div className="rounded-2xl border border-[#d5e3e0] bg-[#edf4f4] p-4"><p className="text-[7px] font-bold uppercase tracking-[.1em] text-[#607873]">Safety boundary</p><b className="mt-2 block text-[9px] text-[#3c5b56]">Zero automatic launch action</b><p className="mt-2 text-[7px] leading-4 text-[#6e817c]">No deploy, DNS change, tracking send or business-data mutation.</p></div></section>

    {modalOpen && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-[#10211d]/45 p-4" onMouseDown={(event) => { if (event.currentTarget === event.target) setModalOpen(false); }}><section className="w-full max-w-xl overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex items-start justify-between border-b border-[#e5ebe8] p-5"><div><p className="text-[7px] font-bold uppercase tracking-[.12em] text-[#3b646d]">Read-only protected action</p><h2 className="mt-1 text-[17px] font-bold text-[#2b3e36]">Run launch verification</h2><p className="mt-1 text-[7px] text-[#87938d]">Capture current evidence; do not approve or launch.</p></div><button className="rounded-xl bg-[#f1f4f2] p-2.5 text-[#60716a]" onClick={() => setModalOpen(false)}><Icon name="close"/></button></header><div className="space-y-4 p-5"><label className="block text-[8px] font-bold text-[#5d6e66]">Verification reason<textarea className="mt-2 min-h-24 w-full rounded-xl border border-[#dce4e0] p-3 text-[9px] leading-5 outline-none focus:border-[#719294]" maxLength={1200} onChange={(event) => setReason(event.target.value)} value={reason}/></label><div className="rounded-xl border border-[#d6e4e1] bg-[#edf4f4] p-4 text-[8px] leading-5 text-[#5d756f]">The scan reads existing ledgers and writes only a hashed verification run plus gate evidence. It never calls an ad provider, deploys code, changes DNS or mutates commerce records.</div><label className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-[8px] leading-4 text-amber-800"><input className="mt-0.5 accent-[#3b646d]" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} type="checkbox"/><span>I understand this records evidence only; human go-live approval and deployment remain separate.</span></label></div><footer className="flex justify-end gap-2 border-t border-[#e5ebe8] p-4"><button className="h-10 rounded-xl border border-[#dce4e0] px-4 text-[8px] font-bold text-[#61716a]" onClick={() => setModalOpen(false)}>Cancel</button><button className="h-10 rounded-xl bg-[#3b646d] px-5 text-[8px] font-bold text-white disabled:opacity-40" disabled={!confirmed || reason.trim().length < 12 || working} onClick={() => void completeScan()}>{working ? "Verifying…" : "Record protected run"}</button></footer></section></div>}
    {notice && <div className="fixed bottom-6 right-6 z-[120] max-w-sm rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-[9px] font-semibold text-emerald-800 shadow-xl">{notice}</div>}
  </div>;
}
